### ISSUE TITLE
Clickable Link in Direct Message

### ISSUE THREAD

**Issue by ChrisJSt** [instagram4j/instagram4j#104]
Is it possible to add a clickable link in the DM ?

As of now url's are just being formatted as a strings when using executing this request. Can we add links when sending DM's?

**Comment by itemimg** [comment]
You put them into the DM with http:// or rather https://?

**Comment by ChrisJSt** [comment]
Yes I did, but it just translated into a string. There is a link attribute as part of the message object that we need to update when creating a DM message object

**Comment by dcmdeivid** [comment]
The same problem happened to me, I saw the node version and for this case we need to extract the link and send it on another field on payload 

https://github.com/huttarichard/instagram-private-api/commit/c3ce0313ac0b7467f36e3347b54f095fa2b3e04c#diff-52c89d8e9fb6c561f9a241e65b60fdaf

if(link_urls.length > 0) {
 +        payload.link.text = text;
 +        payload.link_urls = link_urls;
 +        endpoint = 'threadsBrodcastLink';
 +    } else {
 +        payload.text = text;
 +    }

I will send a pull request with this fix soon

**Comment by justindelisle** [comment]
@dcmdeivid care to share your code?

I tried:
		map = new HashMap<String, String>();
		map.put("type", "form-data");
		map.put("name", "link_text");
		map.put("data", "testing testing");
		data.add(map);
		
		map = new HashMap<String, String>();
		map.put("type", "form-data");
		map.put("name", "link_urls");
		map.put("data", "['www.google.com']");
		data.add(map);

When pointing to direct_v2/threads/broadcast/link/ gives a 500 with no much information.

How did you solve the issue?

**Comment by justindelisle** [comment]
I forked and was able to get it work by creating a new class of InstagramDirectLinkRequest which is very similar to ShareRequest with the following changes:

Endpoint -> direct_v2/threads/broadcast/link/

Adding link text & url to data list
map.put("name", "link_text");
map.put("data", message);

map.put("name", "link_urls");
map.put("data", "url");

If i find time to clean it up ill do a PR but i suggest doing the same thing if you want a solution straight away.

**Comment by juandelia** [comment]
@justindelisle Hey justindelisle! thanks for your contribution.

I changed the endpoint to 'direct_v2/threads/broadcast/link/' and added: 

 map = new HashMap();
      map.put("name", "link_text");
      map.put("data", this.message == null ? "" : this.message);
      data.add(map);

      map = new HashMap();
      map.put("name", "link_urls");
      map.put("data", "https://www.google.com");
      data.add(map);
to the public StatusResult execute() method, but I get always '500 Oops, an error occurred.'

Could you please, share more details on your working implementation?

Thanks for your time!!
Juan

**Comment by juandelia** [comment]
@justindelisle Hi there!

Did you go the chance to check on your example so we could all use it? It would be of souch great help here :) 

Thanks for your time!

**Comment by juandelia** [comment]
hey @justindelisle @brunocvcunha did you got the chance to copy your working code for this feature?

I will really apreciate it!

thanks!

**Comment by alcharo** [comment]
@juandelia I would need your fix. Do you have the whole class?
