### ISSUE TITLE
NullPointer on Instagram4j.login()

### ISSUE THREAD

**Issue by ghost** [instagram4j/instagram4j#113]
Hi, since I use Version 1.6 instead of 1.4 I receive an error when a user logs in:

Exception in thread "Timer-0" java.lang.NullPointerException
	at org.brunocvcunha.instagram4j.Instagram4j.login(Instagram4j.java:191)

It works with 2 other accounts. But only this one throws an error. Maybe because of the endless checkout required loop?

**Comment by itemimg** [comment]
I tried "Gramista" today and what the hell.. All accounts that I had trouble with at login (regardless of wheter with Python, Java or PHP API), Gramista has no problem to log in. I didnt even received an activation code via Email or a challenge warning.. nothing. How?

**Comment by ChrisJSt** [comment]
Yeah I get a null pointer exception too when the user has to authenticate before me being able to login. I just wait for their authentication and then the null isnt thrown

**Comment by itemimg** [comment]
So the user has to authenticate first and after you start the script again, the NPE is gone?

**Comment by patriotaki** [comment]
@ChrisJSt  how do you make it wait?
am getting nullpointer exception for wrong pass and proxy/authentication how can i differntiate them so i can have correct output? i mean i want to show that the pass is correct or no
