### ISSUE TITLE
How to fetch chat history with spesific user

### ISSUE THREAD

**Issue by tayfunyasar** [instagram4j/instagram4j#117]
I'm having my chat thread list with InstagramGetInboxRequest. This response provides me latest(1) message.

Everything is OK until now.

How can I fetch chat history for each user? For example last 10 message for each user.

**Comment by jemand771** [comment]
The example code provided in #154 may be helpful for you. You can add checks to match user id and break out of the loop after 10 iterations if you only want 10 messages
