### ISSUE TITLE
BasicClientConnectionManager causes problems

### ISSUE THREAD

**Issue by whitepigeonsoftware** [instagram4j/instagram4j#118]
> java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
> 2018-02-12 01:00:47.120Make sure to release the connection before allocating another one.
>  	at org.apache.http.util.Asserts.check(Asserts.java:34)
>  INFO	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:163)
>  	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:145)
> 9035	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:422)
>  	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
> ---	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
>  	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> [nio-8080-exec-7]	at org.brunocvcunha.instagram4j.requests.InstagramGetRequest.execute(InstagramGetRequest.java:48)
>  	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:272)
>

**Comment by brunocvcunha** [comment]
Context? Details of what you're doing?

**Comment by whitepigeonsoftware** [comment]
I have the following simple REST Service 

`package com.whitepigeongallery.com.whitepigeongallery.webpage;

import org.brunocvcunha.instagram4j.Instagram4j;
import org.brunocvcunha.instagram4j.requests.InstagramSearchUsernameRequest;
import org.brunocvcunha.instagram4j.requests.InstagramUserFeedRequest;
import org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem;
import org.brunocvcunha.instagram4j.requests.payload.InstagramSearchUsernameResult;
import org.brunocvcunha.instagram4j.requests.payload.InstagramUser;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.util.List;

@RestController
@CrossOrigin(origins="*")
public class InstagramController {

    private final InstagramUser instagramUser;
    private Instagram4j instagram;

    public static String USER_NAME = "yyy";

    public InstagramController() throws IOException {
        this.instagram = Instagram4j.builder()
                .username("xxx")
                .password("XXX\n").build();
        instagram.setup();
        instagram.login();

        this.instagramUser = getInstagramUser();
    }

    @RequestMapping("/instagramuser")
    public InstagramUser getInstagramUser() throws IOException {
        if (instagramUser != null) {
            return instagramUser;
        }
        try {
            final InstagramSearchUsernameResult instagramSearchUsernameResult = this.instagram
                    .sendRequest(new InstagramSearchUsernameRequest(USER_NAME));
            return instagramSearchUsernameResult.getUser();
        }
    }

    @RequestMapping("/feed")
    public List<InstagramFeedItem> getFeed() throws IOException {
        try {
            return this.instagram.sendRequest(new InstagramUserFeedRequest(getInstagramUser().getPk())).getItems();
        }
    }

}
`

by multiple calls to my service the exception from above is quite often thrown from 
this line 

> at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:272)

I think using the BasicClientConnManager in the library is not the best idea.

**Comment by krismorte** [comment]
I start an upgradeto 4.5.6 until now wotks fine @brunocvcunha  any tips to teste this new version?

**Comment by sergeevichvn** [comment]
same problem
