### ISSUE TITLE
use this code in android 

### ISSUE THREAD

**Issue by sajadabasi** [instagram4j/instagram4j#12]
Can I use this library in android?

**Comment by joaoArmando** [comment]
I would also like to use this lib on android, have you figured out the answer yet? Can we use it in android studio too? Thank you!

**Comment by charlieNiekirk** [comment]
Seeing as this is still open, I made a new project called [Instagram4Android](https://github.com/charlieNiekirk/Instagram4Android) which is extremely heavily based in this project but also has many modifications.  For example it internally uses OkHttp for the requests and I've fixed many of the bugs that Android was facing with this project.  It's still very early days though and I haven't done much of a readme :)

**Comment by brunocvcunha** [comment]
More at https://github.com/brunocvcunha/instagram4j/issues/5
