### ISSUE TITLE
Instagram Login Result

### ISSUE THREAD

**Issue by patriotaki** [instagram4j/instagram4j#120]
`InstagramLoginResult(super=StatusResult(status=fail, message=, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), logged_in_user=null,`

why all variables are null? shouldnt they have some value so we can indicate the cause of  a failed login?

for example if it requires sms code, or it was me?

**Comment by brunocvcunha** [comment]
Can you paste the raw response that you get from Instagram? It should be printed on the log if you enable DEBUG level.

**Comment by patriotaki** [comment]
hello, how exactly do i enable debug level? all i get in the console is this (reegarding my issue)
 the fail status is because i have two factor on,
and then i relogin with the code provided by sms, my concern is that those variables should have some value so we can know the exact error..

**Comment by patriotaki** [comment]
i really dont know how to solve this issue.. i get NPE when assigning value to login result variable from instagram.login 
`login_res = instagram.login();`
and i also get null pointer exception when i try to read ` login_res.getMessage()`

how can i catch the cases when login fails due to it was me or sms?
