### ISSUE TITLE
How i can watch stories ?

### ISSUE THREAD

**Issue by lelonco** [instagram4j/instagram4j#122]
Can i watch stories with that API. I can get some information about it. But after getting information view is not counted.

**Comment by ozankaraali** [comment]
You might need to use another scraper project to pass reel media ID to fetch picture.

**Comment by Mike497** [comment]
Hi, I've implemented smth similar you're looking for with this library for one of my projects.
But it requires calling instagram api v2 endpoint.

First I've extended original v1 post request class to call v2 instagram api:
`public abstract class InstagramPostRequestV2<T> extends InstagramPostRequest<T> {

   // originally taken form
   // https://github.com/brunocvcunha/instagram4j/blob/master/src/main/java/org/brunocvcunha/instagram4j/requests/InstagramPostRequest.java
   // changed api version to v2, removed debug loggers
   @Override
   public T execute() throws ClientProtocolException, IOException {
      HttpPost post = new HttpPost("https://i.instagram.com/api/v2/" + getUrl());
      post.addHeader("Connection", "close");
      post.addHeader("Accept", "*/*");
      post.addHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
      post.addHeader("Cookie2", "$Version=2");
      post.addHeader("Accept-Language", "en-US");
      post.addHeader("User-Agent", InstagramConstants.USER_AGENT);

      String payload = getPayload();

      if (isSigned()) {
         payload = InstagramHashUtil.generateSignature(payload);
      }
      post.setEntity(new StringEntity(payload));

      HttpResponse response = api.getClient().execute(post);
      api.setLastResponse(response);

      int resultCode = response.getStatusLine().getStatusCode();
      String content = EntityUtils.toString(response.getEntity());

      post.releaseConnection();

      return parseResult(resultCode, content);
   }

}
`

Then I've created 'watch story' request class. Implementation of this class is actually taken from PHP Instagram library: https://github.com/mgp25/Instagram-API. From 'Internal' class: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php, this class executes Instagram internal functions, 'markStoryMediaSeen' is one of them. Here's request class that was created according to that method:
`public class InstagramWatchStoryRequest extends InstagramPostRequestV2<StatusResult> {

   private List<InstagramItem> reels;

   public InstagramWatchStoryRequest(final List<InstagramItem> items) {
      this.reels = items;
   }

   @Override
   public String getUrl() {
      return "media/seen/?reel=1&live_vod=0";
   }

   @Override
   public String getMethod() {
      return "POST";
   }

   @Override
   public String getPayload() {
      final Map<String, Object> params = new LinkedHashMap<>();

      params.put("_uuid", api.getUuid());
      params.put("_uid", api.getUserId());
      try {
         params.put("_csrftoken", api.getOrFetchCsrf());
      }
      catch (IOException e) {
         e.printStackTrace();
      }
      params.put("container_module", "feed_timeline");
      params.put("reels", parseReelsAndCalculateSeenAt(reels));
      params.put("reel_media_skipped", Collections.emptyList());
      params.put("live_vods", Collections.emptyList());
      params.put("live_vods_skipped", Collections.emptyList());
      params.put("nuxes", Collections.emptyList());
      params.put("nuxes_skipped", Collections.emptyList());

      final ObjectMapper mapper = new ObjectMapper();
      String payloadJson = null;
      try {
         payloadJson = mapper.writeValueAsString(params);
      }
      catch (JsonProcessingException e) {
         e.printStackTrace();
      }

      return payloadJson;
   }

   @Override
   public StatusResult parseResult(final int statusCode, final String content) {
      return parseJson(statusCode, content, StatusResult.class);
   }

   // taken from https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php
   private Map<String, List<String>> parseReelsAndCalculateSeenAt(final List<InstagramItem> reels) {
      final Map<String, List<String>> result = new LinkedHashMap<>();

      // Build the list of seen media, with human randomization of seen-time.

      final long maxSeenAt = System.currentTimeMillis() / 1000; // Get current global UTC timestamp.
      long seenAt = maxSeenAt - (3 * reels.size()); // Start seenAt in the past.

      for (InstagramItem reel : reels) {
         // Raise "seenAt" if it's somehow older than the item's "takenAt".
         // NOTE: Can only happen if you see a story instantly when posted.
         final long itemTakenAt = Long.valueOf(reel.getTaken_at());
         if (seenAt < itemTakenAt) {
            seenAt = itemTakenAt + 2;
         }

         // Do not let "seenAt" exceed the current global UTC time.
         if (seenAt > maxSeenAt) {
            seenAt = maxSeenAt;
         }

         // Determine the source ID for this item. This is where the item was
         // seen from, such as a UserID or a Location-StoryTray ID.
         final long itemSourceId = reel.getUser().getPk();

         // Key Format: "mediaPk_userPk_sourceId".
         // NOTE: In case of seeing stories on a user's profile, their
         // userPk is used as the sourceId, as "mediaPk_userPk_userPk".
         final String reelId = reel.getId() + "_" + itemSourceId;

         // Value Format: ["mediaTakenAt_seenAt"] (array with single string).
         result.put(reelId, Collections.singletonList(itemTakenAt + "_" + seenAt));

         // Randomly add 1-3 seconds to next seenAt timestamp, to act human.
         seenAt += Utils.randomLongBetween(1, 3);
      }

      return result;
   }

}
`
Pay attention: I'm not using in the above class annotations related to this library (that are from 'lombok' lib). It is just a raw implementation, so can be enhanced.

Above class takes as constructor argument reel of user stories. That can be fetched via 'InstagramGetUserReelMediaFeedRequest' class of this library.

Hope someone finds it useful. Maybe it will a good idea to make a pull request with enhancements to the above code in a way of code style and conventions of this library.

**Comment by Mike497** [comment]
Hi, I've implemented smth similar you're looking for with this library for one of my projects.
But it requires calling instagram api v2 endpoint.

First I've extended original v1 post request class to call v2 instagram api:

```public abstract class InstagramPostRequestV2<T> extends InstagramPostRequest<T> {

   // originally taken form
   // https://github.com/brunocvcunha/instagram4j/blob/master/src/main/java/org/brunocvcunha/instagram4j/requests/InstagramPostRequest.java
   // changed api version to v2, removed debug loggers
   @Override
   public T execute() throws ClientProtocolException, IOException {
      HttpPost post = new HttpPost("https://i.instagram.com/api/v2/" + getUrl());
      post.addHeader("Connection", "close");
      post.addHeader("Accept", "*/*");
      post.addHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
      post.addHeader("Cookie2", "$Version=2");
      post.addHeader("Accept-Language", "en-US");
      post.addHeader("User-Agent", InstagramConstants.USER_AGENT);

      String payload = getPayload();

      if (isSigned()) {
         payload = InstagramHashUtil.generateSignature(payload);
      }
      post.setEntity(new StringEntity(payload));

      HttpResponse response = api.getClient().execute(post);
      api.setLastResponse(response);

      int resultCode = response.getStatusLine().getStatusCode();
      String content = EntityUtils.toString(response.getEntity());

      post.releaseConnection();

      return parseResult(resultCode, content);
   }

}
```
Then I've created 'watch story' request class. Implementation of this class is actually taken from PHP Instagram library: https://github.com/mgp25/Instagram-API. From 'Internal' class: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php, this class executes Instagram internal functions, 'markStoryMediaSeen' is one of them. Here's request class that was created according to that method:
```public class InstagramWatchStoryRequest extends InstagramPostRequestV2<StatusResult> {

   private List<InstagramItem> reels;

   public InstagramWatchStoryRequest(final List<InstagramItem> items) {
      this.reels = items;
   }

   @Override
   public String getUrl() {
      return "media/seen/?reel=1&live_vod=0";
   }

   @Override
   public String getMethod() {
      return "POST";
   }

   @Override
   public String getPayload() {
      final Map<String, Object> params = new LinkedHashMap<>();

      params.put("_uuid", api.getUuid());
      params.put("_uid", api.getUserId());
      try {
         params.put("_csrftoken", api.getOrFetchCsrf());
      }
      catch (IOException e) {
         e.printStackTrace();
      }
      params.put("container_module", "feed_timeline");
      params.put("reels", parseReelsAndCalculateSeenAt(reels));
      params.put("reel_media_skipped", Collections.emptyList());
      params.put("live_vods", Collections.emptyList());
      params.put("live_vods_skipped", Collections.emptyList());
      params.put("nuxes", Collections.emptyList());
      params.put("nuxes_skipped", Collections.emptyList());

      final ObjectMapper mapper = new ObjectMapper();
      String payloadJson = null;
      try {
         payloadJson = mapper.writeValueAsString(params);
      }
      catch (JsonProcessingException e) {
         e.printStackTrace();
      }

      return payloadJson;
   }

   @Override
   public StatusResult parseResult(final int statusCode, final String content) {
      return parseJson(statusCode, content, StatusResult.class);
   }

   // taken from https://github.com/mgp25/Instagram-API/blob/master/src/Request/Internal.php
   private Map<String, List<String>> parseReelsAndCalculateSeenAt(final List<InstagramItem> reels) {
      final Map<String, List<String>> result = new LinkedHashMap<>();

      // Build the list of seen media, with human randomization of seen-time.

      final long maxSeenAt = System.currentTimeMillis() / 1000; // Get current global UTC timestamp.
      long seenAt = maxSeenAt - (3 * reels.size()); // Start seenAt in the past.

      for (InstagramItem reel : reels) {
         // Raise "seenAt" if it's somehow older than the item's "takenAt".
         // NOTE: Can only happen if you see a story instantly when posted.
         final long itemTakenAt = Long.valueOf(reel.getTaken_at());
         if (seenAt < itemTakenAt) {
            seenAt = itemTakenAt + 2;
         }

         // Do not let "seenAt" exceed the current global UTC time.
         if (seenAt > maxSeenAt) {
            seenAt = maxSeenAt;
         }

         // Determine the source ID for this item. This is where the item was
         // seen from, such as a UserID or a Location-StoryTray ID.
         final long itemSourceId = reel.getUser().getPk();

         // Key Format: "mediaPk_userPk_sourceId".
         // NOTE: In case of seeing stories on a user's profile, their
         // userPk is used as the sourceId, as "mediaPk_userPk_userPk".
         final String reelId = reel.getId() + "_" + itemSourceId;

         // Value Format: ["mediaTakenAt_seenAt"] (array with single string).
         result.put(reelId, Collections.singletonList(itemTakenAt + "_" + seenAt));

         // Randomly add 1-3 seconds to next seenAt timestamp, to act human.
         seenAt += Utils.randomLongBetween(1, 3);
      }

      return result;
   }

}
```
Pay attention: I'm not using in the above class annotations related to this library (that are from 'lombok' lib). It is just a raw implementation, so can be enhanced.

Above class takes as constructor argument reel of user stories. That can be fetched via 'InstagramGetUserReelMediaFeedRequest' class of this library.

Hope someone finds it useful. Maybe it will a good idea to make a pull request with enhancements to the above code in a way of code style and conventions of this library.

**Comment by murakas** [comment]
Still no such opportunity?
