### ISSUE TITLE
Following activity

### ISSUE THREAD

**Issue by mehmaj** [instagram4j/instagram4j#123]
Hi
Thanks 4 ur useful library.
I wanna monitor following activity (tab that is next to the notification tab)!
Is there any function that return following activity?

**Comment by krismorte** [comment]
Have you seen this request `InstagramGetRecentActivityRequest`?

**Comment by mehmaj** [comment]
I think there is problem parsing result to wrong model ...

**Comment by cloud777** [comment]
Hi all
Activity tab contains 2 sections => "You" & "Following"
Function "InstagramGetRecentActivityRequest" returns "you" tab 
How about "following" tab???

**Comment by DarkPrompt** [comment]
Hi all
I have the same question, is there a function that returns list of users that i follow.
I already get a list of users who following my account and that's all good. I need list of users that i follow.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
