### ISSUE TITLE
Missing Elements in InstagramItem Response

### ISSUE THREAD

**Issue by gokhancelikkaya** [instagram4j/instagram4j#127]
Although the response of InstagramGetReelsTrayFeedRequest contains `image_versions2": {"candidates": [{"width": , "height": , "url": "} .. ]]`, it is not mapped in `InstagramItem` entity. Can be fixed just by adding this object to the class as a new variable. So at the moment there is no way to get user story pictures or videos

**Comment by justindelisle** [comment]
It's mapped into InstagramFeedItem of which is the return type of InstagramUserFeedRequest.
