### ISSUE TITLE
Get second page of results

### ISSUE THREAD

**Issue by ventskus-roman** [instagram4j/instagram4j#13]
Is there any possibility to get second (and third...) page of results? For tag feed for example

**Comment by BondarenkoEvgeny** [comment]
Hi @ventskus-roman. Watch for pull request #22, if it is accepted it will solve your problem

**Comment by brunocvcunha** [comment]
It was fixed by @BondarenkoEvgeny 

Thanks a lot!
Will release a new version later this week.

**Comment by mehhrad** [comment]
sorry i didn't get it.
how to get the second page now?

**Comment by patriotaki** [comment]
i have the same problem cant get next pages results for getmedialikers,followers and followings

**Comment by iagoizi** [comment]
Hey! To get a second (and third...) page of results, you should use the method <b>getNext_max_id()</b> and pass its return to a new <b>InstagramTagFeedRequest</b> object. Something like this:
`//gets the first page of results`
`InstagramFeedResult tagFeed = instaClient.sendRequest(new InstagramTagFeedRequest("cute")); `

`//gets the second page of results for this request`
`tagFeed = instaClient.sendRequest(new InstagramTagFeedRequest("cute",  tagFeed.getNext_max_id())); `

`//gets the third page of results for this request`
`tagFeed = instaClient.sendRequest(new InstagramTagFeedRequest("cute",  tagFeed.getNext_max_id())); `
