### ISSUE TITLE
Direct Message Problem :(

### ISSUE THREAD

**Issue by MarvenX97** [instagram4j/instagram4j#131]
hello i'm trying to send messages to my followers . but the message where not delivered :(
this my code :
```

List<String> sN = new ArrayList<String>();
                for (InstagramUserSummary user : users) {
                    sN.add(String.valueOf(user.getPk()));
                    System.out.println("User " + String.valueOf(user.getPk()) + " follows ME!");
                }

                try {
                    instagram.sendRequest(InstagramDirectShareRequest.builder(InstagramDirectShareRequest.ShareType.MESSAGE,sN ).message("Hello").build());
                } catch (IOException e) {
                    e.printStackTrace();
                }
				
```
my logs :

I/System.out: User 7141544461 follows ME!
I/System.out: NULLHello
I/System.out: EXECUTED

**Comment by Mykke24** [comment]
Use:

ArrayList<String> recipients = new ArrayList<String>();
recipients.add(RECIPIENT_ID);

sendRequest(InstagramDirectShareRequest.builder(ShareType.MESSAGE, recipients).message(message).build());

**Comment by justindelisle** [comment]
From your output its clear your problem is that String.valueOf(user.getPk() is returning null so you're trying to send the DM to an empty string as your recipient.
