### ISSUE TITLE
How I can get time when photo was upload

### ISSUE THREAD

**Issue by lelonco** [instagram4j/instagram4j#134]
How I can get time when photo was upload? (sorry for my English )

**Comment by justindelisle** [comment]
On the InstagramGetMediaInfoResult -> InstagramFeedItem -> taken_at 
That's the closest thing to a status date that i know of.

**Comment by lelonco** [comment]
Thx, but how convert it to normal time

**Comment by Seriusam** [comment]
Can you define normal time ?
