### ISSUE TITLE
how get list messages from directmessage 

### ISSUE THREAD

**Issue by Pipka091** [instagram4j/instagram4j#135]
how get list messages from directmessage ?

**Comment by justindelisle** [comment]
InstagramGetInboxRequest

**Comment by Pipka091** [comment]
how to use it correctly? I did it and he does not return anything
kotlin:

val instagram = Instagram4j.builder().username("login").password("password").build()
	instagram.setup()
	instagram.login()

val test =  instagram.sendRequest(InstagramGetInboxRequest());

object test empty

**Comment by justindelisle** [comment]
I watched the output of Instagram4j:this.sendRequest(new InstagramGetInboxRequest());
This returned the inbox of my user, so not sure about your set up sorry.

**Comment by Pipka091** [comment]
In my case, it returns an object
StatusResult(status=ok, message=null, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null)

**Comment by Pipka091** [comment]
Where list?

**Comment by justindelisle** [comment]
@Pipka091 you're right!

InstagramGetInboxRequest simply returns StatusResult which is simply the generic status result type. You'll need to fork the project and change that to return a result type specific for the inbox request.

**Comment by Pipka091** [comment]
ok, thx

**Comment by tayfunyasar** [comment]
It only returns latest message of all conversations.

Is it possible to view each user's message thread-history?

**Comment by krismorte** [comment]
@tayfunyasar can show your code for us?
