### ISSUE TITLE
Archive pic

### ISSUE THREAD

**Issue by MiguelEcar** [instagram4j/instagram4j#146]
Hello, I would like to know if is it possible to set a photo as archived/hidden using instagram4j?

**Comment by jvogit** [comment]
I do not think Instagram4J has the capabilities right now... but you can try to make your own request referencing the instagram php api and port it over. It is what this project is based on and i hope to port over some features.

https://github.com/mgp25/Instagram-API/blob/67d5eacbcaf52f155e048c7b9738cb848f9b40a8/src/Request/Timeline.php

**Comment by MiguelEcar** [comment]
Oh.. ok.. thabks for your reply...
I have one more question..
what parameter should I pass to delete a media? I tried to pass media pk, media id, upload id, but none worked. the InstagramDeleteMediaRequest receives a long parameter but the media id returned when creating is like xxx_xxx..

**Comment by jvogit** [comment]
Hello I fixed this issue here #139 

You may build to form current version or just copy the class.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
