### ISSUE TITLE
How can i contribute ?

### ISSUE THREAD

**Issue by tayfunyasar** [instagram4j/instagram4j#147]
How can I contribute ? 

@Wiki page is not loading and I couldn't find how to simulate Android development environment in my local machine.

**Comment by jvogit** [comment]
some requests features are missing and need to port over into java.

https://github.com/mgp25/Instagram-API

You can use this as reference and port it over into java. some etiquette would be to keep code style same, organized, documented, etc. Open a pull request after!

**Comment by brunocvcunha** [comment]
Yes, there are many things that we are still not supporting. For Android check #5.

You can submit PRs, I'm looking at them more frequently than issues, due to lack of time available.
