### ISSUE TITLE
Cannot setup Instagram4j object

### ISSUE THREAD

**Issue by Gaurav-Punjabi** [instagram4j/instagram4j#148]
Hey I'm new to using 3rd party API's and I'm getting an exception while setting up the Instagram4J object
The exception is: "Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/CookieStore"

What should I do ??? I cant find a solution

**Comment by jvogit** [comment]
make sure you have dependencies needed. are you using maven?

**Comment by Gaurav-Punjabi** [comment]
No, I'm not using maven.But I have provided it HTTP-client, logger,comms-3 jars still it is giving me some exception.

**Comment by jordanbancino** [comment]
I have this issue as well. Even when using Maven to build my project, there are missing dependencies.

**Comment by jordanbancino** [comment]
UPDATE: I solved my issue by compiling instagram4j with all dependencies included, and I also switched from JDK 10 to JDK 8. @Gaurav-Punjabi, what java version are you using?

**Comment by Gaurav-Punjabi** [comment]
I'm using java version "1.8.0_151". Still getting the same problem.
