### ISSUE TITLE
How can I store login information?

### ISSUE THREAD

**Issue by ffurkanhas** [instagram4j/instagram4j#150]
I want to store login information. Everytime I run the application I do not want to login my instagram account. Can I strore login information and reuse again?

**Comment by jvogit** [comment]
this api requires username and password to login. You can store it somewhere and in your app retrieve it.

**Comment by colpomatteo** [comment]
`Instagram4j instagram = Instagram4j.builder().username(USERNAME).password(PASSWORD).build();
        instagram.setup();
        instagram.login();
        
        File cookieLogin = new File(USERNAME + ".txt");
        ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(cookieLogin));
        oos.writeObject(instagram.getCookieStore());
        oos.close();
        
        
        ObjectInputStream ois = new ObjectInputStream(new FileInputStream(cookieLogin));
        CookieStore cookieStore = (CookieStore) ois.readObject();
        ois.close();
        
        Instagram4j instagram2 = Instagram4j.builder().username(USERNAME)
                .password(PASSWORD)
                .uuid(instagram.getUuid())
                .cookieStore(cookieStore)
                .build();
        instagram2.setup();
        
        InstagramGetMediaLikersResult tagFeed = instagram2.sendRequest(new InstagramGetMediaLikersRequest(1020304050L));`

**Comment by ffurkanhas** [comment]
@colpomatteo thank you. It is enough for me.

**Comment by colpomatteo** [comment]
@ffurkanhas no problem. Actually i asked the same question time ago.. that's why i know the answer 😂

**Comment by ValeraT1982** [comment]
@colpomatteo Yes. 
The question was how to store login information and (as I understand) how to create instance of Instagram4j without USERNAME and PASSWORD.

**Comment by colpomatteo** [comment]
You can’t, I think. But if you have stored the previous login you should be able to store username and password as well.. so you can read them every time

**Comment by deniben** [comment]
> @colpomatteo Yes. I can. What is stored in the cookieStore in your example.
> Second time instead of calling login you set uuid and cookieStore. Still do not see the reason of doing it.

But you dont use method login() just setup()
