### ISSUE TITLE
 The username you entered doesn't belong to an account. Please check your username and try again

### ISSUE THREAD

**Issue by psouda** [instagram4j/instagram4j#156]
It cannot login in the code but it lets me log in using my browers and from mobile phone.
The login info is correct, but i get this msg:
"The username you entered doesn't belong to an account. Please check your username and try again"
Anyone know what's going on??

**Comment by krismorte** [comment]
What is the username?

**Comment by soudaa** [comment]
It's "nazarac_72"

**Comment by DzianisH** [comment]
Have you tried your email or phone number instead? Also, please, check the case of your username if it the same as in instagram (i'm not sure if it case sansative or not).

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
