### ISSUE TITLE
How to download media?

### ISSUE THREAD

**Issue by ValeraT1982** [instagram4j/instagram4j#173]
Is it possible to download media?

**Comment by krismorte** [comment]
I asked and I answered in this issue below

#103

**Comment by yamelsenih** [comment]
Hi this really work for latest version?

**Comment by jvogit** [comment]
> Hi this really work for latest version?

The concept is the same, but there is different methods. Sorry for lack of documentation, I'll try to write some. Youd want to get FeedItems then filter out photos or videos (or both) then cast the TimelineFeedItem to the respect item. I think there will be a better way but for now this sample code.

```java
client.actions().timeline()
        .feed().stream()
        .limit(2) // 2 requests
        .forEach(res -> {
            res.getFeed_items().stream()
            .filter(TimelineImageMedia.class::isInstance)
            .map(TimelineImageMedia.class::cast)
            .forEach(image -> {
                // 
                log.info("Download link : {}", image.getImage_versions2().getCandidates().get(0).getUrl());
            });
        });
```

**Comment by yamelsenih** [comment]
Hi @jvogit thanks for your reply

Have you some docunentation for all api? I wish help to contribute

**Comment by jvogit** [comment]
> Hi @jvogit thanks for your reply
> 
> Have you some docunentation for all api? I wish help to contribute

I am planning to write up a CONTRIBUTING doc where all the steps necessary to contribute are explained.

To add requests, it's recommended to follow the guide to intercept and document requests [here](https://github.com/itsMoji/Instagram_SSL_Pinning). Then translate over to Java. For now, look at some requests to get an idea of how requests are formed/responses are modeled [here](https://github.com/instagram4j/instagram4j/tree/develop/src/main/java/com/github/instagram4j/instagram4j/requests). The library uses jackson to aid in translating over json data to POJOs (and vice versa) so it's relatively simple. I'll have a better explanation on this soon. A great idea is to document the new reels endpoint.

For library actions [here](https://github.com/instagram4j/instagram4j/tree/develop/src/main/java/com/github/instagram4j/instagram4j/actions), it would be great to wrap requests into something more meaningful and obvious. There are examples of sending requests [here](https://github.com/instagram4j/instagram4j/tree/develop/src/examples/java) and most are not supported in actions yet. An example would be writing up a Direct inbox action to access direct messages easier.

Anything else that can be helpful or improve quality of life in general is appreciated and welcome.

**Comment by drtibo** [comment]
> > Hi this really work for latest version?
> 
> The concept is the same, but there is different methods. Sorry for lack of documentation or a clear way, I'll try to write some. Youd want to get FeedItems then filter out photos or videos (or both) then cast the TimelineFeedItem to the respect item. This also applies generally to other feed items. I think there will be a better way to filter out feed itmes but for now this sample code.
> 
> ```java
> client.actions().timeline()
>         .feed().stream()
>         .limit(2) // 2 requests
>         .forEach(res -> {
>             res.getFeed_items().stream()
>             .filter(TimelineImageMedia.class::isInstance)
>             .map(TimelineImageMedia.class::cast)
>             .forEach(image -> {
>                 // Different resolutions available, this just picks the first one
>                 log.info("Download link : {}", image.getImage_versions2().getCandidates().get(0).getUrl());
>             });
>         });
> ```

Hi,

Is it possible to get the timeline feed of an other user (providing username or id) and how ? This to retrieve some information like display_url, taken_at_timestamp, location and collections for likes and comments ?

Regards

**Comment by jvogit** [comment]
> > > Hi this really work for latest version?
> > 
> > 
> > The concept is the same, but there is different methods. Sorry for lack of documentation or a clear way, I'll try to write some. Youd want to get FeedItems then filter out photos or videos (or both) then cast the TimelineFeedItem to the respect item. This also applies generally to other feed items. I think there will be a better way to filter out feed itmes but for now this sample code.
> > ```java
> > client.actions().timeline()
> >         .feed().stream()
> >         .limit(2) // 2 requests
> >         .forEach(res -> {
> >             res.getFeed_items().stream()
> >             .filter(TimelineImageMedia.class::isInstance)
> >             .map(TimelineImageMedia.class::cast)
> >             .forEach(image -> {
> >                 // Different resolutions available, this just picks the first one
> >                 log.info("Download link : {}", image.getImage_versions2().getCandidates().get(0).getUrl());
> >             });
> >         });
> > ```
> 
> Hi,
> 
> Is it possible to get the timeline feed of an other user (providing username or id) and how ? This to retrieve some information like display_url, taken_at_timestamp, location and collections for likes and comments ?
> 
> Regards

Yes. Please join our discord for more help instead of commenting on issues.

[![Discord](https://img.shields.io/discord/777326687326044171?label=chat)](https://discord.com/invite/gR2EPwZGEZ)

The request you are looking for is [FeedUserRequest](https://github.com/instagram4j/instagram4j/blob/8402c82d08603356298c85d1ae6348164f017a4e/src/examples/java/feed/FeedUserRequestTest.java#L27)

**Comment by spapapan** [comment]
> > > > Hi this really work for latest version?
> > > 
> > > 
> > > The concept is the same, but there is different methods. Sorry for lack of documentation or a clear way, I'll try to write some. Youd want to get FeedItems then filter out photos or videos (or both) then cast the TimelineFeedItem to the respect item. This also applies generally to other feed items. I think there will be a better way to filter out feed itmes but for now this sample code.
> > > ```java
> > > client.actions().timeline()
> > >         .feed().stream()
> > >         .limit(2) // 2 requests
> > >         .forEach(res -> {
> > >             res.getFeed_items().stream()
> > >             .filter(TimelineImageMedia.class::isInstance)
> > >             .map(TimelineImageMedia.class::cast)
> > >             .forEach(image -> {
> > >                 // Different resolutions available, this just picks the first one
> > >                 log.info("Download link : {}", image.getImage_versions2().getCandidates().get(0).getUrl());
> > >             });
> > >         });
> > > ```
> > 
> > 
> > Hi,
> > Is it possible to get the timeline feed of an other user (providing username or id) and how ? This to retrieve some information like display_url, taken_at_timestamp, location and collections for likes and comments ?
> > Regards
> 
> Yes. Please join our discord for more help instead of commenting on issues.
> 
> [![Discord](https://camo.githubusercontent.com/70ecd2ab56468045fee895d8251bf21d45315e8cf71740976a6e1277bfe81d90/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3737373332363638373332363034343137313f6c6162656c3d63686174)](https://discord.com/invite/gR2EPwZGEZ)
> 
> The request you are looking for is [FeedUserRequest](https://github.com/instagram4j/instagram4j/blob/8402c82d08603356298c85d1ae6348164f017a4e/src/examples/java/feed/FeedUserRequestTest.java#L27)

FeedUserRequest doesn't provide information about the image url, if it is media time 1. How can I access the raw url of the image from FeedUserRequest?
