### ISSUE TITLE
User recent media

### ISSUE THREAD

**Issue by nastae** [instagram4j/instagram4j#179]
I want to get the most recent media posted by target user. 
I tried:
`InstagramGetUserReelMediaFeedResult instagramGetMediaInfo = instagram.sendRequest(new InstagramGetUserReelMediaFeedRequest(userID));`

instagramGetMediaInfo.getItems().size() always equal 0.

**Comment by WinSide** [comment]
Hello, @nastae, what do you want? Your code returned recent Stories by user
For get recent Feed by user use:
`InstagramFeedResult instagramGetMediaInfo = instagram.sendRequest(new InstagramUserFeedRequest(usedID));`
