### ISSUE TITLE
Get feed with location

### ISSUE THREAD

**Issue by armin37** [instagram4j/instagram4j#183]
is there any way to get feed with location?
something like this node js code:

```
Insta.commonSearch('Kyiv').then(r =>
  {
    //get location id for Kyiv
    let locationId = r.places[0].place.location['pk']
    //search posts from Kyiv
    Insta.searchBy('location', locationId, '0', 12).then(r => console.log(r))
  })
```

**Comment by ChrisJSt** [comment]
Any update on adding location feed as another request?

**Comment by tayfunyasar** [comment]
up..

**Comment by jemand771** [comment]
I don't know how it works since I'm new here, but there seems to be a `LocationFeedRequest` if that's what you're looking for
