### ISSUE TITLE
NextMaxID for GetMediaComments returns json [Bug]

### ISSUE THREAD

**Issue by jessrix** [instagram4j/instagram4j#184]
Hey
The NextMaxID feature seems to be working fine with GetFollowerRequest , but it seems to have a bug in GetMediaComments  . In which NextMaxID is returned as a json .
This will lead into a "java.net.URISyntaxException: Illegal character in query" Exception which is caused by json characters ("{}" and space character) 

The full exception description : 
`Caused by: java.net.URISyntaxException: Illegal character in query at index 106: https://i.instagram.com/api/v1/media/1797253869312684639_1296464116/comments/?ig_sig_key_version=4&max_id={"server_cursor": "AQCAT4EDcxAlIIAqDFR4sVdmOOARc1b_XKz4fdhaGEJ9bqDMU1iVKcC2EZQVK7kOUTH-ctDa7zcihPB5T1Xs1bmrhZUbniUkW39U4irtjaOOPA", "is_server_cursor_inverse": false}`

well i hope i didn't give away private keys in that exception 😂 anyways here it is

thanks .

**Comment by brunocvcunha** [comment]
@jessrix it seems that you are sending more than it asks for in the max_id. You should be sending just the `server_cursor`. Can you post your code for me to take a look if there's something wrong in the library or in your implementation?

**Comment by jessrix** [comment]
Here is the original code that generated the exception 
`String nextMaxId = null;
            while(true) {
                InstagramGetMediaCommentsResult comments = instagram.sendRequest(new InstagramGetMediaCommentsRequest(lastpost.getId(), nextMaxId));

                for (InstagramComment c : comments.getComments()) {
                    //some code here
                }
                nextMaxId = comments.getNext_max_id();
                if (nextMaxId == null) {
                    break;
                }
                
            }`
The problem here was that nextmaxid is not the server_cursor itself , but a json containing it so i did this

`JSONParser jsonParser = new JSONParser();
                JSONObject jo = (JSONObject) jsonParser.parse(comments.getNext_max_id());
                nextMaxId =  (String) jo.get("server_cursor");`

And it perfectly worked ! 

The problem is that i found "InstagramGetMediaCommentsResult" returning json as nextmaxid a little bit weird because all the other payloads return only the server cursor and not the whole json . 

Thanks again

**Comment by RodionKorneev** [comment]
Hello
I try to do it in my project, but I get the same set of 20 comments on each iteration of loop... and it works endlessly, despite the fact that the `server_cursor` is changing.
Help me if you know the reason of this problem please.
The code i used below:
```
        String nextMaxId = null;
        String postId = post.getId();

        while(true){
            InstagramGetMediaCommentsRequest request = new InstagramGetMediaCommentsRequest(postId, nextMaxId);
            InstagramGetMediaCommentsResult commentsResult = instagram.sendRequest(request);
            List<InstagramComment> comments = commentsResult.getComments();

            if(comments != null) {
                for (InstagramComment comment : comments) {
                    System.out.println(
                        comment.getUser().getUsername() + ":  " +
                        comment.getText()
                    );
                }
            }

            nextMaxId = parseCommentsNextValue(commentsResult.getNext_max_id());
            System.out.println(nextMaxId);
            
            if(nextMaxId == null) break;
        }
```
`parseCommentsNextValue` function:

```
private static String parseCommentsNextValue(String next){
        if(next == null) return null;
        JsonParser parser = new JsonParser();
        JsonElement parsed = parser.parse(next);
        JsonObject jsonObject = parsed.getAsJsonObject();
        String server_cursor = jsonObject.get("server_cursor").getAsString();
        return server_cursor;
    }
```
The result in console looks like:

```
[20 comments]
QVFEU3RiWG1WX1NvbkNmNjBRYXhVZjVGbTYxbk9GcFdFbHlzM2MzZGh4MVZrTUdEMUFsSk9MVExIb3lRa3FPYjJfQWY2dnJSR0dJSHVlR0VmamtvcDJrMA==
[the same 20 comments]
QVFDTC1mSDVtTTdQU1lnRWJQTVVIRjg1OUNzZWg1SVU2blNjNWxZV2U2LWx6ZFNJUGFHZHlYNmxFY0F2Tm53b21WYlFwVVVjc2hvWDdQNUNUb3RYMkNOdQ==
[the same 20 again]
QVFCUThfUS1XcDItRHhUNE93anBRMzU5U1NoQlVuNjh0Um4yNS0zTVN5VXpST2hqQW1iVEpGWE5YbXh5T3d3R2dvU1J2alNhODFnTHBjZzl0eFFEM0NnYQ==
. . . [endleess loop]
```

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
