### ISSUE TITLE
InstagramTagFeedRequest error when retrieving feeds from users with dot in the name

### ISSUE THREAD

**Issue by terrysulivan** [instagram4j/instagram4j#187]
There is an issue  when looking for user feed with dot in username.

```
 InstagramFeedResult tagFeed = instagram.sendRequest(new InstagramTagFeedRequest("diario.ole"));
 for (InstagramFeedItem feedResult : tagFeed.getItems()) {
   System.out.println("Post ID: " + feedResult.getPk());
 }
```

> 2018-06-13 13:55:59,042 INFO main InstagramRequest:132  - Reading InstagramFeedResult from <!DOCTYPE html>
<html lang="en" class="no-js logged-in ">
    <head><meta charset="utf-8">
        <meta http-equiv="X-UA-Compat
2018-06-13 13:55:59,044 ERROR main InstagramClient:50  - com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!DOCTYPE html>
<html lang="en" class="no-js logged-in ">
    <head><meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
                  Page Not Found &bull; Instagram
                </title>

        
        <meta name="robots" content="noimageindex, noarchive">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="theme-color" content="#000000">
        <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=5, viewport-fit=cover">
        

        <link rel="manifest" href="/data/manifest.json">

**Comment by brunocvcunha** [comment]
You're getting a tag feed `InstagramTagFeedRequest`. Probably you should be using `InstagramUserFeedRequest`
