### ISSUE TITLE
Date create post

### ISSUE THREAD

**Issue by zdotfive** [instagram4j/instagram4j#196]
Hello,
But there is no way to have the post timestamp?
In InstagramFeedResult al date are 01/01/1970.

**Comment by Rimander** [comment]
tagFeed = instagram.sendRequest(new InstagramTagFeedRequest(tag, maxidFollowings));
for (InstagramFeedItem feedResult : tagFeed.getItems()) {
                    System.out.println(feedResult.getPk());

                    Map<String, Object> ars = feedResult.getCaption();

                    long timestamp = Long.parseLong(ars.get("created_at") + "000");
                    long timestamp_utc = Long.parseLong(ars.get("created_at_utc") + "000");
                    Time date = new Time(timestamp);
                    System.out.println(date.toString());
                    date = new Time(timestamp_utc);
                    System.out.println(date.toString());ç

}

**Comment by vadimTovstik** [comment]
> ```
> 
> tagFeed = instagram.sendRequest(new InstagramTagFeedRequest(tag, maxidFollowings));
> for (InstagramFeedItem feedResult : tagFeed.getItems()) {
>                     System.out.println(feedResult.getPk());
> 
>                     Map<String, Object> ars = feedResult.getCaption();
> 
>                     long timestamp = Long.parseLong(ars.get("created_at") + "000");
>                     long timestamp_utc = Long.parseLong(ars.get("created_at_utc") + "000");
>                     Time date = new Time(timestamp);
>                     System.out.println(date.toString());
>                     date = new Time(timestamp_utc);
>                     System.out.println(date.toString());
> }
> ```

What is tag in "new InstagramTagFeedRequest(tag, maxidFollowings)"?

**Comment by vadimTovstik** [comment]
How to get when the post was created?

```
InstagramFeedResult feedResult = mApiInstagram.sendRequest(
                        new InstagramUserFeedRequest(userId, nextPageToken, 0));
                long taken_at = feedResult.getItems().get(0).getTaken_at();
                Date data = new Date(taken_at * 1000);
                Log.d("mytag", "Post created: " + data);
```
