### ISSUE TITLE
InstagramInboxThread items size are always at one

### ISSUE THREAD

**Issue by ghost** [instagram4j/instagram4j#197]
`
InstagramInboxThread thread = this.getGroups().get(0); 
System.out.println(thread.getThread_title());  
System.out.println(thread.getItems().size());
`

Im getting the first one of all my groups on instagram in the first line. After that I print the group name to make sure that the group contains more than one message. The third line always shows that the itemSize is 1. The first item is just the latest message.

How can I get the last 10 or all messages from a instagram direct messages group?

**Comment by krismorte** [comment]
Not really, you need to pagination the result. The Pull request below has an example

#154
