### ISSUE TITLE
InstagramGetFriendshipsRequest returning invalid parameters error

### ISSUE THREAD

**Issue by melihculha** [instagram4j/instagram4j#207]
InstagramGetUserFollowersResult followers = instagram.sendRequest(new 
        InstagramGetUserFollowersRequest(instagram.getUserId()));
        List<InstagramUserSummary> users = followers.getUsers();
        List<Long> list = new ArrayList<>();
        for (InstagramUserSummary user : users) {
            list.add(user.getPk());
        }
        InstagramGetFriendshipsResult result =instagram.sendRequest(new 
        InstagramGetFriendshipsRequest(list));
        System.out.println(result.getFriendship_statuses().get(0).blocking);

In the above code I get a {"message": "Invalid parameters", "status": "fail"} error. Any solution?

**Comment by Sebastian-git** [comment]
Did you ever find a solution? I saw that now in InstagramGetUserFollowersRequest, there is no longer .getUsers(), which is really confusing so maybe they forgot to update the home page on Github to show the new way to create a follow request?? Please, let me know if you figured this out. Thank you!
