### ISSUE TITLE
Fetch story

### ISSUE THREAD

**Issue by hassen66** [instagram4j/instagram4j#208]
how i can fetch story of instagram user and display url of media

**Comment by nazarimilad** [comment]
Here's how I do it:

```
public static void downloadStories(InstagramUser user) throws IOException {
    InstagramGetUserReelMediaFeedResult result = instagram.sendRequest(new InstagramGetUserReelMediaFeedRequest(user.getPk()));
    // transform recent media items object list into list of valid URL's
    List<URL> listUrlStories = result.getItems().stream().map(item -> getUrlFromStory(item.getCode(), item.getMedia_type()))
                                                         .filter(url -> url != null)      // filter out invalid URL's
                                                         .collect(Collectors.toList());
    for (URL url: listUrlStories) {
        downloadMedia(url, user.getUsername());
    }
}
```

The method getUrlFromStory() is a method which gets the URL of the mp4 file (if it's a video) or the JPG file (if it's a photo) of the story and the method downloadMedia() is a method which creates a folder for the specific user and download the file specified by the URL argument passed

**Comment by nazarimilad** [comment]
@brunocvcunha Can you close this one?

**Comment by viktordart** [comment]
Hello,
Can you post the metod getUrlFromStory()? All item from "InstagramGetUserReelMediaFeedResult result" have the url null.
Thanks
