### ISSUE TITLE
Liking comments

### ISSUE THREAD

**Issue by Aulig** [instagram4j/instagram4j#214]
Is liking comments supported? I tried it with an InstagramLikeRequest, but I think that only works for posts, as I get the following response: InstagramLikeResult(super=StatusResult(status=fail, message=Sorry, you cannot like this media, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), spam=false, feedback_ignore_label=null, feedback_title=null, feedback_message=null, feedback_url=null, feedback_action=null, feedback_appeal_label=null)

Thanks :)

**Comment by hellasengineering** [comment]
I am also having this issue. It would be nice to like comments on posts. Any ideas?

**Comment by hellasengineering** [comment]
Anyone have ideas on this?

**Comment by LearnJava** [comment]
import com.fasterxml.jackson.databind.ObjectMapper
import org.apache.log4j.Logger
import org.brunocvcunha.instagram4j.requests.InstagramPostRequest
import org.brunocvcunha.instagram4j.requests.payload.InstagramLikeResult

class InstagramLikeCommentRequest(private val commentId: Long) : InstagramPostRequest<InstagramLikeResult>() {
    private val log = Logger.getLogger(InstagramLikeCommentRequest::class.java)

    override fun getUrl(): String {
//        return "comment/" + this.commentId + "/like/"
        return "media/$commentId/comment_like/"
    }

    override fun getPayload(): String {
        try {
            val likeMap = mutableMapOf<String, Any>()
            likeMap.put("_uuid", this.api.uuid)
            likeMap.put("_uid", this.api.userId)
            likeMap.put("_csrftoken", this.api.orFetchCsrf)
//            likeMap.put("comment_id", this.commentId)
            val mapper = ObjectMapper()
            return mapper.writeValueAsString(likeMap)
        } catch (var4: Throwable) {
            throw var4
        }

    }

    override fun parseResult(statusCode: Int, content: String): InstagramLikeResult {
        try {
            return this.parseJson(statusCode, content, InstagramLikeResult::class.java) as InstagramLikeResult
        } catch (var4: Throwable) {
            throw var4
        }

    }

//    companion object {
//        private val log = Logger.getLogger(InstagramLikeCommentRequest::class.java)
//    }
}
