### ISSUE TITLE
Video View + Impressions?

### ISSUE THREAD

**Issue by patriotaki** [instagram4j/instagram4j#218]
how does a view and an impression count on instagram? can an account submit multiple views and impressions to the same video? is it nescescarry to have an account to increase the view counter and impressions? i want to be able to increase the views and impressions from my accounts with the help of your API

oh and how is it possible to add impressions from different categories?
"from other"
"from explore"
thank you

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
