### ISSUE TITLE
Search media by Latitude and Longitude

### ISSUE THREAD

**Issue by tote88** [instagram4j/instagram4j#220]
Hi there!

In the development of my final thesis, I'm using some features of this library, so firstly I would like to thank all the contributors for this awesome work.

A feature that I'm trying to implement is to search media by lat/lng in a given radius, but unfortunately I do not know the correct url. So, if someone facilitates me this url, or how can it be obtained, I would try to develop this.

Thank you

**Comment by andrefsianipar** [comment]
You may want to check https://www.instagram.com/developer/endpoints/locations/ and follow the steps given.

**Comment by tote88** [comment]
Hi Andre, and thank you for your suggestion. After checking the page, it may be a possible solution, firstly obtaining the venues using the location endpoint and then performing a media search on each returned venue.

What would be absolutely helpful is something similar to https://www.instagram.com/developer/endpoints/media/#get_media_search which performs a search of media by coordinates.

The main impediment comes when using the URLs proposed in this documentation, because as far as I'm concerned, these are not valid while using this library. 

Does somebody have a method to obtain the valid URLs?

Thanks!

**Comment by OmidPvh** [comment]
Hi friends..
now both URL are in top are unavailable so how can we catch location feed by name not Latitude and Longitude???
