### ISSUE TITLE
is there any way to repost a user's posts ?

### ISSUE THREAD

**Issue by osmanmmz** [instagram4j/instagram4j#222]

**Comment by henriqueblobato** [comment]
@osmanmmz Did you find a way to get users media to repost?

**Comment by osmanmmz** [comment]
when get "feedResult.getImage_versions2()" it returns a json it have a link witch contains jpg or mp4. get the link and download than post like its your content. 

try (BufferedInputStream in = new BufferedInputStream(new URL(link).openStream());
             FileOutputStream fileOutputStream =new FileOutputStream("file.mp4"/*or jpg*/)) {
            byte dataBuffer[] = new byte[1024];
            int bytesRead;
            while ((bytesRead = in.read(dataBuffer, 0, 1024)) != -1) {
                fileOutputStream.write(dataBuffer, 0, bytesRead);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

**Comment by krismorte** [comment]
@osmanmmz if you colud take a look in my project above I appreciate

**Comment by osmanmmz** [comment]
@krismorte thanks i will.
