### ISSUE TITLE
Get followers by UserId?

### ISSUE THREAD

**Issue by DevSett** [instagram4j/instagram4j#224]
I'm trying to get a list of followers, in response comes from 7000 followers - only 200 comes followers. Can I get a complete list. You need to check for the presence of the user in the followers.

**Comment by IntrumHuBd** [comment]
You need to iterate and use pagination
List<InstagramUserSummary> users = new ArrayList<>();

		String nextMaxId = null;
		while (true) {
			InstagramGetUserFollowersResult fr = instagram
					.sendRequest(new InstagramGetUserFollowersRequest(pk, nextMaxId));
			users.addAll(fr.getUsers());
			nextMaxId = fr.getNext_max_id();
			if (nextMaxId == null) {
				break;
			}
		}

**Comment by farkascsanad** [comment]
You need to iterate and use pagination
List users = new ArrayList<>();

	String nextMaxId = null;
	while (true) {
		InstagramGetUserFollowersResult fr = instagram
				.sendRequest(new InstagramGetUserFollowersRequest(pk, nextMaxId));
		users.addAll(fr.getUsers());
		nextMaxId = fr.getNext_max_id();
		if (nextMaxId == null) {
			break;
		}
	}
