### ISSUE TITLE
Samsung SM-G935F · Instagram app

### ISSUE THREAD

**Issue by changbaishan** [instagram4j/instagram4j#229]
Hi,

I uploaded an image from my PC with Instagram4J. Then I received an email: "New login to Instagram from Instagram app on Samsung SM-G935F". I was surprised because I know nothing about  Samsung SM-G935F.

The reason I submit this new issue is to ask if it is possible for the author to explain the necessity of connecting through "Samsung SM-G935F". With security headlines everyday, other people may well have same concerns. Checking previous issues list, I have not found explanations. 

Thank you very much.

**Comment by brunocvcunha** [comment]
https://github.com/brunocvcunha/instagram4j/blob/f160d136b3e5c632c04d5cb7ba0fd38d42542a08/src/main/java/org/brunocvcunha/instagram4j/InstagramConstants.java

Instagram has some keys and features that are specific to some devices, so this was just a set of configurations that I got from another repository that works fine. 
They don't allow usage through API, so you basically have to pretend you are coming from the mobile app.
Others would have the same concern if we use iPhone and they don't use Apple, so I don't see this as a concern.

**Comment by changbaishan** [comment]
Thank you very much for you answer!

Instagram is indeed very mobile limited. After I had my test post with instagram4j. I was trying to delete it with logging in. It turned out logging in was not enough. You have to do it on mobile. 

This proves usefulness of Instagram4j. It enables against the limitation of Instagram. For that I thank you for your contribution.

Best regards,

Yong
