### ISSUE TITLE
Authenticate proxy

### ISSUE THREAD

**Issue by armin37** [instagram4j/instagram4j#237]
is there any way to use authenticated proxy with username and password?

**Comment by disayner** [comment]
[file:///D:/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B/%D0%B5%D1%89%D1%91%20%D0%BD%D0%B5%20%D0%BF%D1%80%D0%B8%D0%B4%D1%83%D0%BC%D0%B0%D0%BB%20%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D0%BA%D0%B8/%D0%A1%D1%82%D0%B0%D1%82%D1%8C%D0%B8/proxy%20%20%C2%B7%20Issue%20%2369%20%C2%B7%20brunocvcunha_instagram4j.htm](url)

**Comment by disayner** [comment]
[https://github.com/brunocvcunha/instagram4j/issues/69](url)

**Comment by disayner** [comment]
[https://github.com/brunocvcunha/instagram4j/issues/69](url)

**Comment by disayner** [comment]
#69
