### ISSUE TITLE
Search Users

### ISSUE THREAD

**Issue by drsoosmar** [instagram4j/instagram4j#240]
Hello
How can I search a text among all the usernames?
Exactly the same as the search part in the Instagram itself

**Comment by RodionKorneev** [comment]
if I understand you correctly, you are looking for it:
```
String query = "some name";
InstagramSearchUsersResult searchUsersResult = instagram.sendRequest(new InstagramSearchUsersRequest(query));
List<InstagramSearchUsersResultUser> users = searchUsersResult.getUsers();
```

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
