### ISSUE TITLE
How to use 'paging' in InstagramSearchUsersRequest?

### ISSUE THREAD

**Issue by RodionKorneev** [instagram4j/instagram4j#247]
Hello, 
When I use the InstagramSearchUsersRequest class I get a list of 50 users, there is also an option 'isHasMore', but there is no function to get another piece of data. How can i get more users in my list?
If you have any suggestions for solving this problem, even without using this library, please write.

I looked at the Json that the Instagram's site sends me when I search, there are 100 records, but there is no link to the next piece of data. However, the description of the new API says that this Json will have the link to the next piece of data.
Perhaps future changes in the service will contribute to the emergence of this function in this project, or is it already there?

Thanks a lot for your work.

**Comment by bvn13** [comment]
An instance is posted as comment to issue https://github.com/brunocvcunha/instagram4j/issues/252
Try to examine it.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
