### ISSUE TITLE
Get latest Activitys

### ISSUE THREAD

**Issue by jumaskow** [instagram4j/instagram4j#248]
Hey everyone,

Is it possible to get the "recent activity" tab from Instagram?
I've already found the "InstagramGetRecentActivityRequest" but I'm stuck with getting the results from this request, because it only returns a "StatusResult" and not a "InstagramGetRecentActivityResult". 

Thanks for your help! 👍

**Comment by gstroligo** [comment]
I'm stuck with that too =/
Does anyone got the solution or alternative for that?

**Comment by jumaskow** [comment]
Would be nice. I can see that the results in the activity tab gets shown as a JSON when logging is enabled.

Is it possible to get the JSON "answer" from Instagram?

**Comment by gstroligo** [comment]
You can print something like 

System.out.println(instagram.sendRequest(new InstagramGetRecentActivityRequest()));

 and it will also display the json on console.. tho I have no idea on how to get that Json =?

Need something like 'getItems()' or something...

StatusResult return something like that:

Reading StatusResult from {"aymf": {"items": [{"user": {"pk": "9241238143", "username": "amanda1994kjk", "full_name":

**Comment by jumaskow** [comment]
Anyone has a fix for that?

**Comment by rodrigae** [comment]
I just submitted the pull request for this, I needed this feature as well. Decided to alter the one someone had already started but didn't provide any data. below is how you call it.

InstagramGetRecentActivityResult recent = login.sendRequest(new InstagramGetRecentActivityRequest());

**Comment by vadimTovstik** [comment]
> I just submitted the pull request for this, I needed this feature as well. Decided to alter the one someone had already started but didn't provide any data. below is how you call it.
> 
> InstagramGetRecentActivityResult recent = login.sendRequest(new InstagramGetRecentActivityRequest());

Can you share InstagramGetRecentActivityResult class?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
