### ISSUE TITLE
Retrieve posts of the last year

### ISSUE THREAD

**Issue by zdotfive** [instagram4j/instagram4j#252]
Hi,
is it possible to get the posts of the last year or last six months?

**Comment by JoaoGarcez** [comment]
Hey man. Yeah i think i know how you can do it, try this:

`instagram.setup();
			instagram.login();

			InstagramSearchUsernameResult userResult = instagram.sendRequest(new InstagramSearchUsernameRequest("github"));


			long chave_primaria = userResult.getUser().getPk();


			String nextMaxId = null;
			long minTimeStamp = 1407278400;  //use this, i don't know why



			while (true) {
				InstagramFeedResult feedResult = instagram.sendRequest(new InstagramUserFeedRequest(chave_primaria, nextMaxId, minTimeStamp));

				for(InstagramFeedItem item : feedResult.getItems()) {

					Date time=new java.util.Date((long)item.getTaken_at()*1000);  //use item.getTaken_at to get timestamp of the post, then convert timestamp to datetime

					System.out.println("data: ->>>>>>>>>>>>>>>>>>>" + time);


				}


				try {
					Thread.sleep(1000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				nextMaxId = feedResult.getNext_max_id();

				if (nextMaxId == null) {
					break;
				}

			}`

**Comment by zdotfive** [comment]
Wow. It work. 
Thank you so much

**Comment by chachoe** [comment]
And do you know how to get the likers users list of each post?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
