### ISSUE TITLE
something error!

### ISSUE THREAD

**Issue by MohammadeMBi** [instagram4j/instagram4j#254]
When i add instagram4j.jar to my project and click on add to library, get the following errors after run my project:

1. Error: Invoke-customs are only supported starting with Android O (--min-api 26)
2. Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\user\AndroidStudioProjects\MyApplication\app\libs\instagram4j-1.8.jar
3. Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
4. Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
5. Caused by: com.android.tools.r8.utils.AbortException: Error: Invoke-customs are only supported starting with Android O (--min-api 26)

how to resolve this problems?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
