### ISSUE TITLE
OAuth login?

### ISSUE THREAD

**Issue by fabriziomorello** [instagram4j/instagram4j#258]
Is there any chance to login or get Instagram4j object with access token instead of username and password? I'd like to manage user authentication with instagram authorization url, and then pass only the access token received

**Comment by jxin19** [comment]
I guess how to use OAuth(access token) method.
If you solved this problem, let me know. :D

**Comment by vadimTovstik** [comment]
Yes, me too interest

**Comment by jemand771** [comment]
No. The official Instagram API uses the OAuth flow, I don't think we'll be able to replicate that with the internal API. Im not entirely sure though.

However what you can do to prevent the "new login" warnings is store and re-use the cookie.

**Comment by vadimTovstik** [comment]
> No. The official Instagram API uses the OAuth flow, I don't think we'll be able to replicate that with the internal API. Im not entirely sure though.
> 
> However what you can do to prevent the "new login" warnings is store and re-use the cookie.

Thanks for you answer. In some android apps, OAuth is somehow used. For example, here https://androidappsapk.co/download/com.screamingsnail.shakeitupseasons/ How did they do it? Not  private API approach?

**Comment by jemand771** [comment]
I sadly don't see where or how the app you linked is interacting with Instagram.
But if it's an official, well-known app, it'll probably use the official API like "normal" people/companies do.

**Comment by vadimTovstik** [comment]
Official? But official API not allow get all followers, all following, all likes for posts and so much more. Or not?

**Comment by jemand771** [comment]
I'm sorry, I did somehow not land on the right website/app. My bad! 😅 
You're right, there is no official endpoint for that. I'll look into it.

**Comment by jemand771** [comment]
Looks like it *is* possible, though not implemented in this library.
I tried to decompile the APK, but there was just too much code to read. Couldn't fully comprehend. There seems to be a login flow using facebook, which may just be the oauth flow requested in this issue. (Not the official one though, we're still talking internal private API)

You can also take a look at https://github.com/mgp25/Instagram-API/pull/1759 and try to implement it in java (PRs welcome!), personally.. I don't think it's worth it. Honestly, I don't see that feature coming anytime soon.
Just store the password somewhere safe.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
