### ISSUE TITLE
Failed to configure image: Transcode not finished yet. When try to upload video.

### ISSUE THREAD

**Issue by osmanmmz** [instagram4j/instagram4j#262]
Hi, i am getting an error when tring to repost. First downloading video from instagram this is perfect no problem here. Then uploading file mp4 but it giving an error like this.

`Exception in thread "main" java.lang.IllegalArgumentException: Failed to configure image: Transcode not finished yet.
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:117)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest.execute(InstagramUploadPhotoRequest.java:44)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.configureThumbnail(InstagramUploadVideoRequest.java:152)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:109)
	at org.brunocvcunha.instagram4j.requests.InstagramUploadVideoRequest.execute(InstagramUploadVideoRequest.java:52)
	at org.brunocvcunha.instagram4j.Instagram4j.sendRequest(Instagram4j.java:277)
	at denemeler.silllll.main(silllll.java:107)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\mmz\IdeaProjects\mmz.insta\theFile.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:01:00.16, start: 0.000000, bitrate: 553 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x640, 481 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\mmz\IdeaProjects\mmz.insta\theFile.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
  Duration: 00:01:00.16, start: 0.000000, bitrate: 692 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/bt709/bt709), 640x640, 621 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
`
 But not giving this error everytime. I got some successfull uploads.

my codes ;

````
InstagramFeedItem feedItem=feedResult.getItems().get(i);

                Tools.getUrlFromHref getUrlFromHref=new getUrlFromHref();
                String capion=getUrlFromHref.getTextFromCaption(String.valueOf(feedItem.getCaption()));
String url = getUrlFromFeedItem.getUrl(feedItem.getVideo_versions().toString());

                    main.urlF=url;
                    main.type="mp4";
String url = getUrlFromFeedItem.getUrl(feedItem.getVideo_versions().toString());

                    main.urlF=url;
                    main.type="mp4";
File theFile = new File("theFile."+main.type);
                try (BufferedInputStream in = new BufferedInputStream(new URL(main.urlF).openStream());
                     FileOutputStream fileOutputStream =new FileOutputStream("theFile."+main.type)) {

                    byte dataBuffer[] = new byte[1024];
                    int bytesRead;
                    while ((bytesRead = in.read(dataBuffer, 0, 1024)) != -1) {
                        fileOutputStream.write(dataBuffer, 0, bytesRead);
                    }

                } catch (IOException e) {
                    e.printStackTrace();

                }
try {
                        shareResult=instagram.sendRequest(new InstagramUploadVideoRequest(theFile,capion));
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
```

Any one getting this ? or any solution ?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
