### ISSUE TITLE
Upload Media with location / geo tag

### ISSUE THREAD

**Issue by 175-kavinski** [instagram4j/instagram4j#263]
Hey guys,

Is there a way to attach a geo tag/location to an upload already?
Just found the commit by @krismorte (https://github.com/brunocvcunha/instagram4j/pull/174/commits/6ebe75d11c8b80d08ad04018c01689f35a4c6f85) where he seems to use a constructor with a location in TesteUpload.java:46 , but apparently there is none in the current code.

Am I missing something?
Otherwise I'd implement one.

Thanks in advance,
kavinski.

**Comment by jumaskow** [comment]
I'd also appreciate, if someone could answer - thanks! :)

**Comment by danybony** [comment]
Anybody managed to solve this?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
