### ISSUE TITLE
Can i get user's website ,if i only know user id ?

### ISSUE THREAD

**Issue by heiyeliuying** [instagram4j/instagram4j#264]
Now i know the userid (pk= 448639377)  ,i want get his page(just like https://www.instagram.com/neckandneck_official/  ) .can you help me ?

**Comment by ilyk** [comment]
1. First request the [GetUserInfo](https://github.com/brunocvcunha/instagram4j/blob/master/src/main/java/org/brunocvcunha/instagram4j/requests/InstagramGetUserInfoRequest.java)
2. Then from the [answer](https://github.com/brunocvcunha/instagram4j/blob/master/src/main/java/org/brunocvcunha/instagram4j/requests/payload/InstagramSearchUsernameResult.java) get `user`.`username`
3. And finally concatenate "https://www.instagram.com/" + `username` + "/"

**Comment by heiyeliuying** [comment]
@ilyk  thanks a lot!

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
