### ISSUE TITLE
How to resume crawling latest userFollowers list by using getNext_max_id after weeks

### ISSUE THREAD

**Issue by tayfunyasar** [instagram4j/instagram4j#269]
I want to get userFollowers by using & saving getNext_max_id into my db.

Can i use getNext_max_id value to find out where did i left after days?

User's follower list is always changing day by day, gaining or going down. I dont want to crawl all his followers and find them all at the same time. I will setup a cron job and it will investigate once a week his followers.

Is it possible to use latest getNext_max_id to find out recent followers? Will it resume and find difference between last crawl time and now?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
