### ISSUE TITLE
Is there a way to send Verification Code, if needed?

### ISSUE THREAD

**Issue by gstroligo** [instagram4j/instagram4j#272]
Thank you much for this API. I've learned so much with it. 

I was wondering if it was possible, to find a solution for it.. if so, would any one help me?

After trying to login i've been getting challenge requirement.

Now i have to go to Instagram app and click on "it was me".

But I noticed in the response of the api, that returns a link for the challenge, that allows to send a verification code to e-mail or phone.

Is it possible, using the API, automatically choose e-mail or phone, send the code... and try to login again, after putting the code in the login request?
With somthing like this:

*let's say code is 123456.

InstagramLoginResult login = instagram.login("123456");

I've searched about it before here, and didn't find anything about it, but I guess something like that would be very helpful with challenges..

**Comment by ilyk** [comment]
Yes, here is the simple algo:
1. Make a GET request to the URL which found in the `loginResponse.challenge.url`
2. You'll need the following field value from the response: `challengeResponse.entry_data.Challenge[0].extraData.content[3].fields[0].values[0].value` which contains method for challenge (you can play around with the response to understand why this field is used and which field you can switch to)
3. Do POST request to the challenge url with content type **type application/x-www-form-urlencoded** and data: `"choice=" + fieldValue` (don't forget to add **referer** and **x-csrftoken** headers!)
4. Receive the code in the email or SMS. Either programmatically or manually put it into the program.
5. Do POST request to the challenge url with content **type application/x-www-form-urlencoded** and data: `"security_code=" + code` (don't forget to add **referer** and **x-csrftoken** headers!)

That's all in a very brief description. But beware, they could change that anytime, you'll need to keep an eye on the API and responses.

**Comment by gstroligo** [comment]
THANK YOU @ilyk ! It worked like a charm! 
Had some trouble trying to figure out how to send POST requests with x-csrftoken but I finally got it.

@brunocvcunha you can close it now. Thank you for this API.

**Comment by mkgerasimenko** [comment]
@gstroligo, could you please provide me the Post request for your example?

**Comment by newsbubbles** [comment]
Full instructions and solution here: https://github.com/brunocvcunha/instagram4j/issues/308#issuecomment-536248658

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
