### ISSUE TITLE
Images are pastel colored

### ISSUE THREAD

**Issue by MitchZinck** [instagram4j/instagram4j#273]
Occasionally when I upload an image it gets uploaded in pastel-like colors:

https://ibb.co/vw64CfZ -> uploaded
https://ibb.co/19mKLcn -> original

Anyone know the reason for this? I have tried saving the images as sRGB but to no avail.

**Comment by Cousin** [comment]
You have to convert the file to a jpg and it will upload fine

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
