### ISSUE TITLE
Dependencies - Not get the video jars

### ISSUE THREAD

**Issue by hellasengineering** [instagram4j/instagram4j#280]
Hi all, 

Using the instagram4j has grown my project times 5 in size. There are a ton of platform dependent jars that seem to be related to video. Anyone have a solution for excluding those from your local repository? 

Thanks, Kosta

**Comment by brunocvcunha** [comment]
Maybe you could exclude dependencies when importing instagram4j. I don't have plans to cleanup it in the short term :(

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
