### ISSUE TITLE
Error Logging In

### ISSUE THREAD

**Issue by 16GB** [instagram4j/instagram4j#286]
`Instagram4j instagram = Instagram4j.builder().username("hidden").password("hidden").build();
        instagram.setup();
        instagram.login();`
Throws this error:

Error:(12, 24) java: cannot access org.apache.http.client.ClientProtocolException
  class file for org.apache.http.client.ClientProtocolException not found

**Comment by eminakcil** [comment]
same problem

**Comment by hippolyto** [comment]
> Solve the problem, add
> `<dependencies> <dependency> <groupId>org.brunocvcunha.instagram4j</groupId> <artifactId>instagram4j</artifactId> <version>1.13</version> </dependency> </dependencies>`
> to pom.xml using Maven.

It did not solve here. Still getting the same error. Any ideas? Thank you.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
