### ISSUE TITLE
What is the latest version

### ISSUE THREAD

**Issue by mmabas77** [instagram4j/instagram4j#290]
I use maven 1.9-SNAPSHOT version >> is it the latest version ?
1.8 doesn't work on win 10 :-(

**Comment by DanielePancottini** [comment]
The latest version of instagram4j is the 1.10. Hope this will fix your problem

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
