### ISSUE TITLE
Users change names, but the PK doesn't. Anyway to get a user by PK? 

### ISSUE THREAD

**Issue by hellasengineering** [instagram4j/instagram4j#292]
It appears I can only get them by username, but not by PK. The issue happens when someone changes their handle and then I can't find them anymore programatically. I think this might be the same or very similiar to #78 and it seems that a fix might have been put in place, but I am not seeing it. Thank you! @brunocvcunha

**Comment by jemand771** [comment]
You can try the following (after login, of course):
```
InstagramSearchUsernameResult result = instagram.sendRequest(new InstagramGetUserInfoRequest(myUserId));
System.out.println(result.getUser().getUsername());
```
I do not know if the Result class is correct though and wasn't able to test it :/

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
