### ISSUE TITLE
Authenticate the Proxy

### ISSUE THREAD

**Issue by Soldrakon** [instagram4j/instagram4j#296]
Hello, the new proxy feature is pretty cool, but is there no way to set username and password for the proxy? all the posts about the problem were followed by DzianisH and his "Hey there will be proxies in 1.8" and no further explanation as to how to add username and password to HTTP host for authentication.

**Comment by alejandropablo** [comment]
```
HttpHost proxy = new HttpHost("host", "port", "http");
CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
        credentialsProvider.setCredentials(new AuthScope(AuthScope.ANY),
                new UsernamePasswordCredentials("login", "password"));
        
        
Instagram4j instagram = Instagram4j.builder().username("username").password("password").proxy(proxy).credentialsProvider(credentialsProvider).build();
instagram.setup();
instagram.login();
```

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
