### ISSUE TITLE
Caption id not always is long

### ISSUE THREAD

**Issue by juandelia** [instagram4j/instagram4j#301]
Some captions (I couldnt identify when happens) comes with a non long ID, but with a String id like "123123123123_caption" making the parsing of the feed response fail.

`     "caption": {
        "content_type": "comment",
        "user": {
          "pk": 645836308,
          "username": "trapichearg",
          "full_name": "Trapiche Argentina",
          "is_private": false,
          "profile_pic_url": "https://instagram.faep9-1.fna.fbcdn.net/vp/3811cc3fa3a7b901a47f7458fb3e16e5/5D4FA6CB/t51.2885-19/s150x150/49573749_730500927395192_1463617424459825152_n.jpg?_nc_ht=instagram.faep9-1.fna.fbcdn.net",
          "profile_pic_id": "1969213956719718802_645836308",
          "is_verified": true
        },
        "user_id": 645836308,
        **"pk": "2015387258663823970_caption",**
        "text": "#Puro&Impuro frutos de una misma cosecha. Criados lado a lado. Uno en barricas de roble, el otro en cubas de cemento. #ArmoniosamenteOpuestos",
        "type": 1,
        "created_at": 1554474666,
        "created_at_utc": 1554449466,
        "media_id": 2015387258663824000,
        "bit_flags": 0,
        "status": "Active"
      }`

Could you please make that field string?

I could fork it and make a PR if you want.

Thanks for your great job guys!

**Comment by tayfunyasar** [comment]
I'm having same problem. #260

**Comment by TheMalloum** [comment]
I'have the same problème

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
