### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by NicholasLaur** [instagram4j/instagram4j#303]
Hello, I would like to know if this API could be used in Android.
Thanks a lot.

**Comment by cemocanon** [comment]
yes available. but you should use this library.
https://github.com/charlieAndroidDev/Instagram4Android

**Comment by TeuF** [comment]
Try to add  this in yourroject/app/build.gradle inside android{}

android {      
      packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
      }          
}


src: https://stackoverflow.com/questions/44342455/more-than-one-file-was-found-with-os-independent-path-meta-inf-license

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
