### ISSUE TITLE
instagram.setup(); Problem AllowAllHostnameVerifier--

### ISSUE THREAD

**Issue by cemocanon** [instagram4j/instagram4j#307]
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966)
        at org.brunocvcunha.instagram4j.Instagram4j.setup(Instagram4j.java:176)

**Comment by imjd175** [comment]
@cemocanon  You need following dependencies in your environment, so install it
dependencies {
    compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'
}

**Comment by kanekifont** [comment]
i have this error, how can i resolve?

Duplicate class org.apache.http.Consts found in modules jetified-httpclient-android-4.3.5.jar (org.apache.httpcomponents:httpclient-android:4.3.5) and jetified-httpcore-4.4.10.jar (org.apache.httpcomponents:httpcore:4.4.10)

**Comment by HMY314** [comment]
I also met, how to solve it?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
