### ISSUE TITLE
[REQ] add ability to send/receive "link" type messages

### ISSUE THREAD

**Issue by jemand771** [instagram4j/instagram4j#311]
Receiving link type messages will probably have a similarly easy fix as adding media_share and story_share (#285 )

I do not know about the deep inner workings of instagram4j, but a solution for sending link messages has been suggested in [this comment](https://github.com/brunocvcunha/instagram4j/issues/104#issuecomment-431715792) in #104 

I know this issue partly is a duplicate to #243 and #244, I just wanted to summarize it all as a feature request.

The receive part is probably doable for me, the send part not really I'm afraid. Any help is greatly appreciated! :)

**Comment by jemand771** [comment]
Clarification as to what I mean by "link message"
![9b2ff598-aa78-48ab-9fc4-8fe08d06fd7d](https://user-images.githubusercontent.com/19669567/56838984-b9928280-6880-11e9-8409-2fb48652f9a2.jpg)

Property in `InstagramInboxThreadItem`: `item_type="link"`

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
