### ISSUE TITLE
Get paid brand mentions

### ISSUE THREAD

**Issue by farkascsanad** [instagram4j/instagram4j#319]
Is it possible to detect, that the post contains paid brand mentions?
Eg: https://www.instagram.com/p/BvpKdVmggr4/
 @coach is a paid brand mention.

Thanks

**Comment by farkascsanad** [comment]
"edge_media_to_sponsor_user":{
"edges":[
{
"node":{
"sponsor":{
"id":"9791606",
"username":"coach"
}
}
}
]
},

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
