### ISSUE TITLE
How to search posts?

### ISSUE THREAD

**Issue by bvn13** [instagram4j/instagram4j#324]
I found several disadvantages of using this API:
1) Searching posts by hashtag works only if it is english word
2) Searching posts by location... is it even implemented? I cannot imagine how to use this API for searching by location. I've played a little with InstagramSearchLocationsRequest and InstagramLocationFeedRequest requests. The first one brings all locations by latitude and longitude with their external ID (I don't actually understand what is the purpose of third param called query in its constructor). The last one is expected to search feed by location, but what should be passed in param of constructor? I guess it is related to InstagramSearchLocationsRequest result but I actually cannot pass the correct param from any response property tested by me.

So my question is: how to search posts / feed the right way? Can you provide an instance?

**Comment by bvn13** [comment]
I am working on this issue.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
