### ISSUE TITLE
is it possible to get user following hashtags ?

### ISSUE THREAD

**Issue by osmanmmz** [instagram4j/instagram4j#336]

**Comment by DanielePancottini** [comment]
@osmanmmz Not yet, if you need I can develop a request to satisfy your request 👍

**Comment by osmanmmz** [comment]
if you can it will be usefull

**Comment by DanielePancottini** [comment]
@osmanmmz I've tried to develop the request to get user following hashtags but the endpoint that should do this: `/users/{0}/following_tags_info/` seems to be deprecated. 😢

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
