### ISSUE TITLE
June 21st multiple accounts get Feedback Required spam true

### ISSUE THREAD

**Issue by alejandropablo** [instagram4j/instagram4j#340]
Starting June 21st afternoon around 3:00 GMT me and some friends with accounts started getting:

`InstagramRequest:132 - Reading StatusResult from {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked.`

When doing Follow request to other accounts. Different implementations between me and my friends, but all using this Java port. 

And still, to the day, all these accounts get the spam=true. If we use these accounts via web or a real mobile app, they work correctly.

Does anybody know anything about this? Did this happen to you?

**Comment by juandelia** [comment]
Having the same issue, please let me know if I can add any feedback or information you would need to troubleshoot this.

Thanks!

**Comment by rodrigae** [comment]
Same here, how do we respond. It gives you the option to respond, to let instagram know this is an error, but I can't seem to get the write post link for it.

**Comment by jose2016** [comment]
Hi do you solved this issue with feedback required?

**Comment by juandelia** [comment]
Making the accounts connect from a different IP sometimes solves the issue temporally, but its not definitive solution.

Is there any metrics or known limits that an account must follow in order to avoid this temp blocks?
Like how many likes, follows, unfollows, DMs per minute and per day that one could consider to avoid this behavior?

Thanks!

**Comment by jose2016** [comment]
Limits and restrictions according to official Instagram reference:

a maximum number of likes per hour: 60;
a maximum number of comments per hour: 60;
a maximum number of follows per hour: 60;
a maximum number of messages per hour: 60.
But if your account is fairly new, the limits are different:

a maximum number of likes per hour: 30;
a maximum number of comments per hour: 30;
a maximum number of follows/unfollows per hour: 30.
Important reminder. Instagram adds up the number of follows and unfollows as well as blocking the unwanted users. In total, you can’t take more than 1440 actions on your account daily. Make sure you spread out these actions accordingly.

https://support.nextpost.company/d/58-6-reasons-why-instagram-blocks-you-to-do-actions-if-you-get-banned-updated

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
