### ISSUE TITLE
Get link from instagram story

### ISSUE THREAD

**Issue by Damo1** [instagram4j/instagram4j#341]
Is there a way to get a link from an instagram story ? I'm referring to the "See More" section which redirects the user to a link that was shared along with the story. I am looking for a way to get that link.
![image](https://user-images.githubusercontent.com/34452502/60589517-9a890300-9d91-11e9-80ca-4c11880b9758.png)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
