### ISSUE TITLE
Not an Issue | How to record the Instagram api and https traffic from android

### ISSUE THREAD

**Issue by ketansgaikwad05** [instagram4j/instagram4j#346]
Like to know the exact process to capture the https requests from Instagram android app.
Can you please help me with this or redirect me to the working solution, I wanted the same for another similar app called Depop.

**Comment by HectorHumanes** [comment]
Not sure if is the answer you are looking for, but here is some light about sniffing requests (it's valid for IG or any other app you want)
https://www.eviltester.com/2014/09/using-wireshark-to-observer-mobile-http.html

Basically, you need to intercept the packets sent where them flows throught any network interface. 

On the other hand, note that what you are intented to sniff is http**S** traffic, which means all the info it contains it's encrypted. It's ok if you only want to see the endpoints used.

**Comment by ketansgaikwad05** [comment]
I have already tried all such utilities like Wireshark, Fiddler.
but an app that uses certificate pinning is hard to record and crack and you cannot see the content of all recorded requests.
So wanted to see how it is done here. it will be very helpful if anyone can share steps to crack it. Many Thanks.

**Comment by thomasz23** [comment]
A little late, but I'm pretty sure there's modded APK's that have SSL pinning removed. Also I believe you can downgrade to a lower version of Instagram that doesn't have SSL pinning.

**Comment by ketansgaikwad05** [comment]
Thanks Thomas, but it is very hard to find such apk and make the initial set up ready with such version of instagram apk. I wonder how the creators are continuously updating this repositories for new updates as well. Can someone provide some clue about such setup or working solution about how to remove the ssl pinning from any such apps.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
