### ISSUE TITLE
InstagramConfigVideoResult

### ISSUE THREAD

**Issue by pagu421** [instagram4j/instagram4j#349]
Hello,
Could you include the changes for Video Upload -  and create InstagramConfigVideoResult, so we can make edit the video and add user tags later on.

Even I tried to make the changes in InstagramUploadVideoRequest and return thumbnailResult  (InstagramConfigurePhotoResult) from configureThumbnail/execute method and used the media_id from response to edit - that works in my case but it would great - if you can combine the video_upload and thumbnailResult  - and generate InstagramConfigVideoResult  for futher operations.

Thank you for wonderful solution for Instagram.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
