### ISSUE TITLE
InstagramAutoCompleteUserListRequest: Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by panopticum** [instagram4j/instagram4j#357]
Hi Guys,

A couple of days ago I meet this issue, on the last step of the "login" statement 

`Sending request: org.brunocvcunha.instagram4j.requests.InstagramAutoCompleteUserListRequest`

it always responds the "Please wait a few minutes before you try again."

it's not an account-specific or ip-specific issue, I have tested it on different accounts and ip adresses

who had the same issue, how to resolve it?

Thanks

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
