### ISSUE TITLE
post.getCaption() throws NoSuchMethodError

### ISSUE THREAD

**Issue by sirdan13** [instagram4j/instagram4j#367]
Hi,
I'm getting 
`Exception in thread "main" java.lang.NoSuchMethodError: org.brunocvcunha.instagram4j.requests.payload.InstagramFeedItem.getCaption()Ljava/util/Map;`
when calling 
```
InstagramFeedResult userFeed = instagram.sendRequest(new InstagramUserFeedRequest(instagram.getUserId()));
for(InstagramFeedItem post : userFeed.getItems())
post.getCaption();
```
How is it possible?

Thanks.

**Comment by jemand771** [comment]
What IDE are you using? You may need to install the lombok plugin for the auto-generated Setters and Getters to work properly

**Comment by sirdan13** [comment]
I am using Eclipse. I'll give it a try and let you know. Thank you.

**Comment by sirdan13** [comment]
@jemand771 nope, didn't work. I installed lombok, added the lombok jar to my project, restarted Eclipse and rebuilt the project, but same result.

**Comment by brunocvcunha** [comment]
Are you using Maven to manage the dependencies? Sounds like something funny is going on.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
