### ISSUE TITLE
Get Online Users? ("user_presence")

### ISSUE THREAD

**Issue by GiorgosXou** [instagram4j/instagram4j#370]
Hello,

I was wondering if possible to get `"user_presence"` somehow _(which as i know, is what corresponds to things like the Online-status of a user and etc.)_ Just In case i am wrong **^** with what i am referencing,  just to be clear with my question: **Is there any way to get if a user is online or not?** _[and when was]_ **Because** from what i have tried until now: `new Date(user.getLast_activity_at() / 1000).toLocaleString()` **I am only able** to get the last time a user sent a message and not the last time it was active [...]

_(**PS**. **^** i am pretty new to Instagram's Private Api , **+** Nice job)_

Thanks in Advance,
George.

**Comment by GiorgosXou** [comment]
```java
InstagramInboxResult a = instagram.sendRequest(new InstagramGetInboxRequest());

System.out.println("test: " + a.status);
System.out.println("-- [DMs / Inbox] --");

for (InstagramInboxThread user : a.inbox.getThreads()) {
    System.out.print( user.thread_title + "  ("  + new Date(user.getLast_activity_at() / 1000).toLocaleString() + ")  " + user.getViewer_id());
}
```

**Comment by jemand771** [comment]
**this.**
this is what I want new issues to look like, thank you really much! <3
(a lot of details but no unnecessary info, code snippets, text formatting and a clear description of what you did)

Your solution with the String indeed seems a bit "brutal" as you call it, we usually just create new models for new requests. I'm currently quite busy but I'll look into this sometime later this week

**Comment by GiorgosXou** [comment]
Thanks you so much too!! I want to let you know that your kind words really made my day! (:

**Comment by GiorgosXou** [comment]
@jvogit 

**Thanks you** for taking the time to help me out with understanding the way things are being represented in java code. **But, the truth is** that althought i kind of get the idea of how that simple example works and by having a look in other classes too,  **in my situation** the issue is that while i really want to implement `user_presence` and way more other things, **the only thing that holds me back** is that i can't yet get the idea of how i would represent an actual number in this java model.

**To get you an idea of what my problem is**, lets say a hypothetical example of the same json you had as an example, with some minor changes: 
```json
{
    "users": {
        "01234":
            {
              "id": 1,
              "name": "Foo"
            },
        "43215":
            {
              "id": 2,
              "name":"Bar"
            }
    },
    "status":"ok"
}
```
**In this situation how would i reprisent that gap between `variables` and actual `"01234"` value in java code?** it might be something simple that i am stuck on but forgive me for that i am pretty new in this topic as i said before

And again thanks you [...] <3

**Comment by jvogit** [comment]
@GiorgosXou 

"users" field can be represented using a Map.

Here is example:
```java
@Getter
@Setter
public class Example {
    private Map<Integer, UserInfo> users;
    private String status;
    
    @Getter
    @Setter
    public static class UserInfo {
	private int id;
	private String name;
    }
    
    public static void main(String args[]) throws JsonParseException, JsonMappingException, IOException {
	ObjectMapper mapper = new ObjectMapper();
	Example ex = mapper.readValue(new File("example.json"), Example.class);
	System.out.println(ex.getStatus());
	ex.getUsers().forEach((id, user) -> {
	    System.out.println(id + " " + user.getId() + " " + user.getName());
	});
    }
}
```

Here is json:
```json
{
	"users":{
		"01234": {
			"id":1,
			"name":"Foo"
		},
		"02443":{
			"id":2,
			"name":"Bar"
		}
	},
	"status":"ok"
}
```

Output:
```
ok
1234 1 Foo
2443 2 Bar
```

I hope it'll help you understand!

**Comment by GiorgosXou** [comment]
@jvogit 

> _" I hope it'll help you understand! "_

**Yep 100%,  Thanks!**

So now that i "see", i think it was quite simple and that makes me feel wondering if this was the best or even the right solution or not (it's, like too good to be true), so just to be sure i will have the codes below before i proceed to any pull request...

**Why i am sceptical:**
Reason why, is mainly because i have seen `Map<>` being used in `getPayload()`  like in `InstagramCheckUsernameRequest.java` which i dont yet know where is being used for, something that makes me think that there might also exist other better solutions [...] ?

**[ Example-Use & Output ] :**

Example:
```java
public static void main(String[] args) throws Exception {

// Login Stuff
 ...

InstagramUsersPresenceResult p = instagram.sendRequest(new InstagramGetUsersPresenceRequest());
                
System.out.println("++ [Users's Presence] ++");
System.out.println(p.getStatus());

p.getUser_presence().forEach((UserPK, user) -> {
       System.out.println("Online: " + user.is_active() 
                        + " At " + new Date(user.getLast_activity_at_ms()).toLocaleString()
                        + " UserPK: "+  UserPK);
});
System.out.println("-- [Users's Presence] --");

}
```
Output:
```
ok
Online: False At 14 Sept 2019 2:00:00  pm UserPK: 123456789
Online: True  At 14 Sept 2019 3:57:08  pm UserPK: 123556759
Online: False At 14 Sept 2019 12:00:29 mm UserPK: 123456489
Online: False At 14 Sept 2019 12:40:17 pm UserPK: 623356789
Online: True  At 14 Sept 2019 4:00:56  pm UserPK: 823453789
Online: False At 14 Sept 2019 4:01:00  pm UserPK: 923457789
Online: False At 14 Sept 2019 4:02:51  pm UserPK: 423456789
Online: False At 14 Sept 2019 3:46:34  pm UserPK: 223436789
```

**[ Solution ] :**

> InstagramUserPresenceItem.java
```java
package org.brunocvcunha.instagram4j.requests.payload;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter	
@Setter
@ToString(callSuper = true)
public class InstagramUserPresenceItem {
	private boolean is_active;
	private long last_activity_at_ms;
}
```
> InstagramUsersPresenceResult.java
```java
package org.brunocvcunha.instagram4j.requests.payload;

import java.util.Map;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString(callSuper = true)
public class InstagramUsersPresenceResult extends StatusResult  {

	private Map<Long, InstagramUserPresenceItem> user_presence;
	private String status;
    
}
```
> InstagramGetUsersPresenceRequest.java
```java
package org.brunocvcunha.instagram4j.requests;

import org.brunocvcunha.instagram4j.requests.payload.InstagramUsersPresenceResult;
import lombok.SneakyThrows;

//@RequiredArgsConstructor
//@AllArgsConstructor
public class InstagramGetUsersPresenceRequest extends InstagramGetRequest<InstagramUsersPresenceResult> {


	@Override
	public String getUrl() {
		return "direct_v2/get_presence/";
	}

	@Override
	@SneakyThrows
	public String getPayload() {
		return null;
	}

	@Override
	@SneakyThrows
	public InstagramUsersPresenceResult parseResult(int statusCode, String content) {
		return parseJson(statusCode, content, InstagramUsersPresenceResult.class);
	}

}
```

(**PS.** I am sorry if i am destructing you from your main work by asking you all along [...])

**Comment by jvogit** [comment]
@GiorgosXou 
This is great! I do have one suggestion which is in the InstagramUsersPresenceResult
```java
    private String status;
```

This field is not required because it is inherited from the superclass StatusResult.
Besides a small revision everything looks great to me and hopefully will be seeing your pull request soon!

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
