### ISSUE TITLE
 InstagramGetUserFollowersRequest returns fewer followers than it actually has

### ISSUE THREAD

**Issue by chachoe** [instagram4j/instagram4j#375]
For some Instagram accounts, the procedure renders the NextFollowersId null before reaching the total number of followers it has.

An account has 800k followers, and it returns the pointer in null at 250k.

For other ones  it works fine! Here is the code:

`
while (true) {
	try {
		
		InstagramGetUserFollowersResult fr = instagram.get().sendRequest(new InstagramGetUserFollowersRequest(user.getUser_id(), fr.getNext_max_id()));
						
		if (fr.getStatus().equals("ok")){
			
			if (fr.getUsers().size()>0){
				//here do something
			}
			
			if (fr.getNext_max_id() == null) {
				break;
			}	
			
		}
		else{	
			try {TimeUnit.MINUTES.sleep(2); } catch (InterruptedException e) { e.printStackTrace(); }
		}
	}
	catch(Exception e){
		logger.info("{}",e.toString());}catch(Error e){logger.info("{}",e.toString());
	}
}
`

I can't find a reason why this is happening. Do you know why it can be and how to correct it?

**Comment by cozdenoglu** [comment]
Hi All,

I'm facing with the same issue.

The account has 746 followers but it returns 178 users.. :(

```
//....
followersList = instagram.sendRequest(new InstagramGetUserFollowersRequest(instagram.getUserId()));
	    	
List<InstagramUserSummary> usersFollowers = followersList.getUsers();

int size = usersFollowers.size();
//....
```

Can somebody help us to solve the issue? I couldn't figure out :( 

.ver info from pom.xml;

```
<groupId>org.brunocvcunha.instagram4j</groupId>
<artifactId>instagram4j</artifactId>
<version>1.13-SNAPSHOT</version>
```

**Comment by jemand771** [comment]
i am not sure about this, but maybe you are querrying too much data too quickly? the requests seem to be working for me

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
