### ISSUE TITLE
Get story URL in the new 1.12 version

### ISSUE THREAD

**Issue by Patatone** [instagram4j/instagram4j#376]
Can someone help me to find the correct code to get a story url in the new 1.12 version?
My previus code:
`InstagramFeedItem x = storyResult.getItems().get(i);
if (x.getMedia_type() == 1) {
System.out.println(x.getImage_versions2().getCandidates().get(0).getUrl());`

**Comment by jvogit** [comment]
I think #352 should address your issue if you're trying to get the story link (See More).

**Comment by Patatone** [comment]
> I think #352 should address your issue if you're trying to get the story link (See More).

There is an error in the code:
"The method getStory_cta() is undefined for the type InstagramItem"
![image](https://user-images.githubusercontent.com/34103646/65393665-d675a800-dd83-11e9-89e7-6c8bd9d2d7e0.png)

**Comment by jvogit** [comment]
> > I think #352 should address your issue if you're trying to get the story link (See More).
> 
> There is an error in the code:
> "The method getStory_cta() is undefined for the type InstagramItem"
> ![image](https://user-images.githubusercontent.com/34103646/65393665-d675a800-dd83-11e9-89e7-6c8bd9d2d7e0.png)

It's not yet merged. You can merge my branch into your local branch. (Or copy the modified files over)

**Comment by gss0** [comment]
@jvogit When the next merge ?

**Comment by jemand771** [comment]
i'm afraid that's a surprise xD

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
