### ISSUE TITLE
direct messaging to broadcast user specific details (which differs between users), to a closed group

### ISSUE THREAD

**Issue by fxpal-git** [instagram4j/instagram4j#38]
I am aware we can broadcast an already posted photo to a closed circle using InstagramDirectShareRequest as shown in readme.

`instagram.sendRequest(InstagramDirectShareRequest.builder(ShareType.MEDIA, recipients).mediaId(mid).message(message).build());`

Is it possible to make use of direct messaging to broad cast user specific details ( which differ from one user to another ) to a closed user group?

**Comment by Mykke24** [comment]
Are you able to execute the code you posted?
`instagram.sendRequest(InstagramDirectShareRequest.builder(ShareType.MEDIA, recipients).mediaId(mid).message(message).build());`

because I can't

Instagram responds with "Oops, an error occurred"
