### ISSUE TITLE
unable to fetch location feed results

### ISSUE THREAD

**Issue by ketansgaikwad05** [instagram4j/instagram4j#380]
The updated post method of InstagramLocationFeedRequest(**location**) returns error response when external_id is passed as parameter.

above **location** argument is the external_id parameter captured from the below request.
InstagramLocation = InstagramSearchLocationsRequest("40.7439862", "-73.998511", "some location name")
**Response of InstagramSearchLocationsRequest:** 
InstagramLocation{name='En La Puñeta Llegando Al Carajo', external_id_source='facebook_places', external_source='null', address='New York, New York', lat=40.81255, lng=-73.90296, external_id='**124264791569847**', facebook_places_id='null', city='null', pk='null', short_name='null', facebook_events_id='null', start_time='null', end_time='null', location_dict=null, type='null', profile_pic_url='null', profile_pic_username='null', time_granularity='null', timezone='null'}

**Please let me know if I am passing the correct location ID to InstagramLocationFeedRequest?**

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
