### ISSUE TITLE
CookieStore not working anymore

### ISSUE THREAD

**Issue by gsegatori** [instagram4j/instagram4j#381]
I have been using the cookiestore but from 3 days it's not working anymore, even if I regenerate cookie, it's going to ask me the two factor.
`	private static Instagram4j loginWithCookie(String username, String workspace) throws Exception {
		File cookieLogin = new File(workspace, username+".igc");
		if(!cookieLogin.exists())
			throw new Exception("File " + cookieLogin + " doesn't exists.");
		ObjectInputStream ois = new ObjectInputStream(new FileInputStream(cookieLogin));
		BasicCookieStore cookieStore = (BasicCookieStore) ois.readObject();
		String uuid = (String) ois.readObject();
		String usernameC = (String) ois.readObject();
		String password = (String) ois.readObject();
		ois.close();

		Instagram4j instagram = Instagram4j
										.builder()
										.username(usernameC)
										.password(password)
										.uuid(uuid)
										.cookieStore(cookieStore)
										.build();

		instagram.setup();
		instagram.login();
		
		return instagram;
	}`

Till now I didn't need to put password and username too (I just put "test" "test") and was working good in any case because it was getting the cookieStore

**Comment by jemand771** [comment]
please post the exception you get

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
