### ISSUE TITLE
how to disable log output?

### ISSUE THREAD

**Issue by lxknvlk** [instagram4j/instagram4j#384]
i seen one issue that suggested add a properties file, but it did not work

**Comment by jemand771** [comment]
try ```LogManager.getRootLogger().setLevel(Level.OFF);```
you can also set the logging level to ERROR, WARN, or something similar

**Comment by lxknvlk** [comment]
I would like to save the log output to file. 

1 )`LogManager.getLogManager().loggerNames` returned 2 loggers "global" and "". I made file handlers for then and the output was only my custom logs, not the instagram4j logs. 

2) LogManager does not have getRootLogger() method

**Comment by lxknvlk** [comment]
I have managed to turn off logger in such a way:

`    org.apache.log4j.Logger.getLogger(Instagram4j::class.java).level = org.apache.log4j.Level.OFF
    org.apache.log4j.Logger.getLogger(StatusResult::class.java).level = org.apache.log4j.Level.OFF
    org.apache.log4j.Logger.getLogger(InstagramSyncFeaturesResult::class.java).level = org.apache.log4j.Level.OFF
    org.apache.log4j.Logger.getLogger(InstagramLoginResult::class.java).level = org.apache.log4j.Level.OFF
    org.apache.log4j.Logger.getLogger(InstagramInboxResult::class.java).level = org.apache.log4j.Level.OFF
    org.apache.log4j.Logger.getLogger(InstagramSearchUsernameResult::class.java).level = org.apache.log4j.Level.OFF
    org.apache.log4j.Logger.getLogger(InstagramRequest::class.java).level = org.apache.log4j.Level.OFF
`

**Comment by tonnoz** [comment]
this worked instead for me:
`      org.apache.log4j.Logger.getLogger("org.brunocvcunha").setLevel(Level.OFF);
      org.apache.log4j.Logger.getLogger("org.brunocvcunha.instagram4j").setLevel(Level.OFF);
`

Hope helps someone.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
