### ISSUE TITLE
how to get top posts for hashtag

### ISSUE THREAD

**Issue by lxknvlk** [instagram4j/instagram4j#385]
`instagram.sendRequest(InstagramTagFeedRequest("tag")) `

Gets recent posts, not top posts. How can i get top posts per hashtag?

**Comment by lxknvlk** [comment]
meanwhile i have found a workaround using such an url

`https://www.instagram.com/explore/tags/<tag>/?__a=1`
and parse the results on my own

**Comment by deniben** [comment]
convert your string to unicode like "\u041e\u0434\u044f\u0433" and use InstagramTagFeedRequest("\u041e\u0434\u044f\u0433")
it works)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
