### ISSUE TITLE
I need your help!

### ISSUE THREAD

**Issue by huseyinkarael** [instagram4j/instagram4j#387]
I'm installing .jar in your "instagram4j" project into android studio but I get an error

> Invoke-customs are only supported starting with Android O (--min-api 26)

**Comment by huseyinkarael** [comment]
https://prnt.sc/poqpt6

**Comment by jemand771** [comment]
This library does not seem to be compatible with Android. For future questions, please take a minute to search existing issues before opening new ones https://github.com/brunocvcunha/instagram4j/issues?q=android
Maybe try to use Instagram4Android instead

**Comment by Suzanskiy** [comment]
> I'm installing .jar in your "instagram4j" project into android studio but I get an error
> 
> > Invoke-customs are only supported starting with Android O (--min-api 26)

You have to try catch this code, or add to method **throws IOException**

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
