### ISSUE TITLE
How to get second page of TimelineFeed results

### ISSUE THREAD

**Issue by noideaw** [instagram4j/instagram4j#39]
How can I get second page of TimelineFeed results?

**Comment by brunocvcunha** [comment]
Changed InstagramTimelineFeedRequest to pass pagination (maxId).

**Comment by charlieAndroidDev** [comment]
@brunocvcunha this doesn't work anymore.  You'll need to pass max_id and various other pagans as post parameters.  The post request however is NOT signed.

**Comment by charlieAndroidDev** [comment]
As a guide, the getTimelineFeed method here should help: https://github.com/mgp25/Instagram-API/blob/master/src/Request/Timeline.php

**Comment by yaniferhaoui** [comment]
To fix the Timeline pagination, you must to change 2 simple things:
 - Change the method getUrl() of the Class InstagramTimelineFeedRequest like that: 
`@Override`
`public String getUrl() {`
`      String url = "feed/timeline";`
`if (maxId != null && !maxId.isEmpty()) {`
`url += "?max_id=" + maxId;`
`}`
`return url;`
`}`

- Change the attribut `long pk;` of the Class InstagramComment to `String pk;`
