### ISSUE TITLE
Massive increase of file size when using version >= 1.12 with Gradle

### ISSUE THREAD

**Issue by DeBerk** [instagram4j/instagram4j#390]
I've been using version 1.11 and wanted to update it to 1.13 but noticed that the file size increases by 20 times with version higher than 1.11 when compiling with Gradle. 
Compiled file size with version 1.11:
![small](https://user-images.githubusercontent.com/52451262/68533665-d594d780-032b-11ea-88ca-eda3a4a2e6b2.PNG)
Compiled file size with version 1.12 or 1.13:
![big](https://user-images.githubusercontent.com/52451262/68533667-e0e80300-032b-11ea-9263-2f3ffc3ebd91.PNG)
Also versions lower than 1.10 seem to be as big as the new one. It'd be great if that could be fixed.

**Comment by NandanDesai** [comment]
I'm facing the same issue. Did you solve this?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
