### ISSUE TITLE
Your Account Was Compromised!

### ISSUE THREAD

**Issue by ketansgaikwad05** [instagram4j/instagram4j#392]
By using this repository i got this warning message and had to change my password.
I was following profiles with a very slow speed. 10 to 15 profiles an hour. Does anyone else get this warning? How to resolve this? I am using the latest release with updated device Information.

> **Your Account Was Compromised**
It looks like you shared your password with service to help you get more likes or followers, which goes against our Community Guidelines.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
