### ISSUE TITLE
How to get activity?

### ISSUE THREAD

**Issue by vadimTovstik** [instagram4j/instagram4j#394]
Need to get page activity likes, comments, who start follow you. Like this https://www.instagram.com/accounts/activity/?__a=1 but with this library. How I can do it?

**Comment by vadimTovstik** [comment]
Note: InstagramGetRecentActivityRequest. this is not wha me need. It's little bit different.

**Comment by jxin19** [comment]
@vadimTovstik 
need to customize that source. 
I had the same problem.
please note the below link. can get user information bout id, username, profile image and etc.

[https://github.com/brunocvcunha/instagram4j/pull/174](https://github.com/brunocvcunha/instagram4j/pull/174)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

**Comment by vadimTovstik** [comment]
sdfsdf
