### ISSUE TITLE
AccessToken

### ISSUE THREAD

**Issue by AleTassi** [instagram4j/instagram4j#395]
Hi, is there a way to get the access token generated by the login?

I was trying to do something like this 

```
instagram = Instagram4j.builder().username(username).password(password).build();
instagram.setup();
instagram.login();
		
CookieStore cookies = instagram.getCookieStore();
		
String sessionId = cookies.getCookies().stream()
				.filter(cookie -> "cookieName".equals(cookie.getName()))
				.findAny()
				.get()
				.getValue();
```

But I didn't find any cookie that help me

Any ideas?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
