### ISSUE TITLE
Login with session/Csrf, not by username/pass

### ISSUE THREAD

**Issue by erfanvaredi** [instagram4j/instagram4j#40]
How can i login without username/pass.
Can we just use Csrf to login?
I don't want to save users' password.
Thank u :)

**Comment by jalizadeh** [comment]
yes, check this **[issue](https://github.com/instagram4j/instagram4j/issues/71#issuecomment-336028154)**

the first time try to login, after the cookie file is created, comment login process and load the cookie now on
