### ISSUE TITLE
How to get all the media and not just 12?

### ISSUE THREAD

**Issue by Felnor96** [instagram4j/instagram4j#400]
Hi everyone, I'm trying to get all the likes of every media of an account (in this case github), but it only returns a part (depending on the account), not all of them. I tried to use the layout as many examples suggest, but nothing. I would like to get the likes of every media. Then why do I have to set minTime or maxTime? If I don't put them, it marks me as an error. Then I also set a 5/10 second pause so that many requests are not executed, but they always block the account. Why? I'm going crazy

`       

        InstagramSearchUsernameResult userResult = instagram.sendRequest(new 
        InstagramSearchUsernameRequest("github"));
            
        String nextMaxId = null;
        long maxTime = 1576108800;  // 2019-12-12
        long minTime = 1575975204 ; // 1970 - 01 -01
        
        while (true) {
                    InstagramFeedResult userFeed = instagram.sendRequest(new InstagramUserFeedRequest(userResult.getUser().getPk(), nextMaxId, minTime ,maxTime ));
                    for(InstagramFeedItem post : userFeed.getItems()) {
                        System.out.println(post.getLike_count());
                        nextMaxId = userFeed.getNext_max_id();
                        if (nextMaxId == null) {
                                break;
                        }
                         
                        Thread.sleep(5000);
                    }       
            
             }

        }`

Please help me with the code correction

**Comment by iizvv** [comment]
I also encountered this problem, did you solve it?

**Comment by jalizadeh** [comment]
If you want to fetch all post, well, it seems there is a problem with the class `InstagramUserFeedRequest`. The api url in this class should be changed. The fields `minTimestamp` and `maxTimestamp` should be removed, therefore change the api url. You can extend one modified class for yourself. Then use the following algorithm:

String nextMaxId = null;
do {
	InstagramFeedResult userFeed = instagram.sendRequest(new MyInstagramUserFeedRequest(userResult.getUser().getPk(), nextMaxId));
	for (InstagramFeedItem post : userFeed.getItems()) {
		System.out.println(post.getLike_count());
	}
	Thread.sleep(3000);
	nextMaxId = userFeed.getNext_max_id();
} while (nextMaxId != null);

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
