### ISSUE TITLE
How to get user's external_url and email ?

### ISSUE THREAD

**Issue by beansoy** [instagram4j/instagram4j#402]
I use user pk to get user info, like this:
_InstagramSearchUsernameResult  userResult = instagram.sendRequest(new InstagramGetUserInfoRequest(******));
InstagramUser user  = userResult.getUser();_
It worked befor, but recently the user info only contains name and avator, the external_url and follower_count is null. How can i get user's external_url?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
