### ISSUE TITLE
Can't send direct message (problem with InstagramDirectShareRequest.builder())

### ISSUE THREAD

**Issue by ML72** [instagram4j/instagram4j#404]
To share a message, the readme says to call
`instagram.sendRequest(InstagramDirectShareRequest.builder(ShareType.MESSAGE, recipients).message(message).build());`
but when I call it, Eclipse says 
`The method builder() in the type InstagramDirectShareRequest is not applicable for the arguments (InstagramDirectShareRequest.ShareType, List<String>)`

**Comment by ML72** [comment]
Update: I didn't know how builders worked in Java, and after quite a while of research I realized that I had to call it like
`...InstagramDirectShareRequest.builder().shareType(ShareType.MESSAGE).recipients(recipients).message("message")...`

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

**Comment by ipodovinnikov** [comment]
Could you please suggest what classes need to be used to send message in 2.0.7 version? There is no InstagramDirectShareRequest, there are only sendRrequest but can't find anything that fits for sending direct messages

**Comment by ErrorxCode** [comment]
> Could you please suggest what classes need to be used to send message in 2.0.7 version? There is no InstagramDirectShareRequest, there are only sendRrequest but can't find anything that fits for sending direct messages

See #716 & shift to [EasyInsta](https://github.com/ErrorxCode/ErrorxCode) now
