### ISSUE TITLE
 InstagramGetStoryViewersRequest of certein user story return only 20 items. 

### ISSUE THREAD

**Issue by Suzanskiy** [instagram4j/instagram4j#410]
Hello! 

I'm trying to get stories of user and got some problems. There are 100+ stories viewers, but API returns only 20. I spend two days to find out and I didn't found the way to use pagination. 

Please help

**Comment by Suzanskiy** [comment]
I didn't find the way how to use pagination. Can some one help me? Is it possible?

**Comment by adiel098** [comment]
hey , someone solve this problem?

**Comment by Suzanskiy** [comment]
> hey , someone solve this problem?

Still no

**Comment by adiel098** [comment]
we must solve this problem , i saw in other issues here that the problem happend else when try get 
user follower list and they solve it by "move next page" something with the next_max_id ,
but i dont know how to do it in this class.

see more example https://github.com/brunocvcunha/instagram4j/issues/13

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
