### ISSUE TITLE
Upload video.

### ISSUE THREAD

**Issue by rhatami7495** [instagram4j/instagram4j#412]
HttpResponseProxy{HTTP/1.1 400 Bad Request [Content-Type: text/html; charset=utf-8, x-instagram-trace-enabled: True, x-instagram-trace-token: NDVkODBiZjA0Y2I3NDVkODkxZDllNTg0OWU0MzNlMWZ8OTEuMjUxLjIxMC4xNzI=, Vary: Accept-Language, Cookie, Content-Language: en, Date: Sat, 25 Jan 2020 10:26:43 GMT, Strict-Transport-Security: max-age=31536000, Cache-Control: private, no-cache, no-store, must-revalidate, Pragma: no-cache, Expires: Sat, 01 Jan 2000 00:00:00 GMT, X-Frame-Options: SAMEORIGIN, content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests, X-Content-Type-Options: nosniff, X-XSS-Protection: 0, x-aed: 15, Access-Control-Expose-Headers: X-IG-Set-WWW-Claim, Set-Cookie: csrftoken=m1LjqYHAhV0HkbA1fAnTTmx0g95AbYbW; Domain=.instagram.com; expires=Sat, 23-Jan-2021 10:26:43 GMT; Max-Age=31449600; Path=/; Secure, Set-Cookie: rur=FTW; Domain=.instagram.com; HttpOnly; Path=/; Secure, Set-Cookie: urlgen="{\"91.251.210.172\": 197207}:1ivIeJ:Ywq0LxezRHv6ZulpTF3odTDMJFw"; Domain=.instagram.com; HttpOnly; Path=/; Secure, Date: Sat, 25 Jan 2020 10:26:43 GMT, Connection: keep-alive, Content-Length: 58] ResponseEntityProxy{[Content-Type: text/html; charset=utf-8,Content-Length: 58,Chunked: false]}}

**Comment by rhatami7495** [comment]
HttpResponseProxy{HTTP/1.1 400 Bad Request [Content-Type: text/html; charset=utf-8, x-instagram-trace-enabled: True, x-instagram-trace-token: NDVkODBiZjA0Y2I3NDVkODkxZDllNTg0OWU0MzNlMWZ8OTEuMjUxLjIxMC4xNzI=, Vary: Accept-Language, Cookie, Content-Language: en, Date: Sat, 25 Jan 2020 10:26:43 GMT, Strict-Transport-Security: max-age=31536000, Cache-Control: private, no-cache, no-store, must-revalidate, Pragma: no-cache, Expires: Sat, 01 Jan 2000 00:00:00 GMT, X-Frame-Options: SAMEORIGIN, content-security-policy: report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd blob:; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests, X-Content-Type-Options: nosniff, X-XSS-Protection: 0, x-aed: 15, Access-Control-Expose-Headers: X-IG-Set-WWW-Claim, Set-Cookie: csrftoken=m1LjqYHAhV0HkbA1fAnTTmx0g95AbYbW; Domain=.instagram.com; expires=Sat, 23-Jan-2021 10:26:43 GMT; Max-Age=31449600; Path=/; Secure, Set-Cookie: rur=FTW; Domain=.instagram.com; HttpOnly; Path=/; Secure, Set-Cookie: urlgen="{\"91.251.210.172\": 197207}:1ivIeJ:Ywq0LxezRHv6ZulpTF3odTDMJFw"; Domain=.instagram.com; HttpOnly; Path=/; Secure, Date: Sat, 25 Jan 2020 10:26:43 GMT, Connection: keep-alive, Content-Length: 58] ResponseEntityProxy{[Content-Type: text/html; charset=utf-8,Content-Length: 58,Chunked: false]}}

**Comment by kodmanyagha** [comment]
please add a little explanation about your problem. I can understand your question but this isn't appropriate style. put some source code, indent the code and error message etc.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
