### ISSUE TITLE
Login error because of different time zones

### ISSUE THREAD

**Issue by danielblanco96** [instagram4j/instagram4j#413]
I've been using this amazing API for more than a year now and last week I started to have problems on the login. I login in my app, it fails and when I open the Instagram app it shows a warning screen because the login was suspicious (I guess it's because the different time zone)

Any thoughts on that? Thank you!

**Comment by hdroid** [comment]
I'm facing the same issue. Did you solve this?

**Comment by OmidPvh** [comment]
I found a solution for this issue..
for user you login with different time zone , just go to instagram account and accept the request in login activity with tap on " This was me ".
after a while you can login with this API in your account.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
