### ISSUE TITLE
Add the ability to get a posts alt text.

### ISSUE THREAD

**Issue by thatcherclough** [instagram4j/instagram4j#414]
As of November 2018, Instagram added alt texts to posts. For people that don't enter custom ones, Instagram generates them based on the contents of the post. It would be great if you could add the ability to get alt texts from posts! Thanks :)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
