### ISSUE TITLE
Constant blocked requests

### ISSUE THREAD

**Issue by 200317314** [instagram4j/instagram4j#417]
Is adding followers no longer feasible? I have random sleeps between my actions of 90-120 seconds each. First it requests the profile, waits another random 90-120, then follows it, and repeats that for about 10-20 follows every 2 hours but before it even follows the 2nd or 3rd one it gets banned for a day.

**Comment by GetsEclectic** [comment]
I gave up trying to follow/unfollow/like using the api a few months ago because I experienced the same thing. I built some macros for my android phone using tasker, and I trigger them from my code using autoremote.

**Comment by Koupah** [comment]
My program seems to run fine, have followed over 100 people thus far without any issues other than "InstagramGetUserFollowersResult" failing.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
