### ISSUE TITLE
InstagramTimelineFeedRequest: InstagramFeedResult from {"message": "", "status": "fail"}

### ISSUE THREAD

**Issue by yaniferhaoui** [instagram4j/instagram4j#418]
Hello,

lately, when I send a InstagramTimelineFeedRequest, the status result is always 
InstagramFeedResult from {"message": "", "status": "fail"}...
I tried the request with the versions 1.10, 1.11, 1.12, 1.13, 1.14-SNAPSHOT, with a maxId = "", maxId = null or random parameter like maxId = "100", but always the same failed response.

Someone has the same problem ? Someone has a solution?

Thanks :)

**Comment by Koupah** [comment]
I have the same problem

**Comment by tonnoz** [comment]
same problem here as well

**Comment by tonnoz** [comment]
I updated to version 1.14 and now the request does not go to error but the getItems() method returns still null : https://github.com/instagram4j/instagram4j/pull/355#issuecomment-590123061 

anyone solved this ? @brunocvcunha ?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
