### ISSUE TITLE
{"message": "media_needs_reupload", "media": {"upload_id": "1581248903578", "device_timestamp": "1581248903578"}, "error_title": "bad image input extra:{}", "status": "ok"}

### ISSUE THREAD

**Issue by huss9922** [instagram4j/instagram4j#419]
i try upload image with new endpoint  "rupload_igphoto/". But configurephotorequest doesn't work. I receive this error {"message": "media_needs_reupload", "media": {"upload_id": "1581248903578", "device_timestamp": "1581248903578"}, "error_title": "bad image input extra:{}", "status": "ok"}

**Comment by jvogit** [comment]
Hi please see #393 .

I opened #411 you may use my fork for media uploads.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
