### ISSUE TITLE
Instagram4j.login() is giving an error message with JAR

### ISSUE THREAD

**Issue by NicholasWeiner** [instagram4j/instagram4j#422]
When I try the sample code displayed on the Readme, I get this error when I use`Instagram4j.login()`:

`The type org.apache.http.client.ClientProtocolException cannot be resolved. It is indirectly referenced from required .class files`

**Comment by hippolyto** [comment]
> 
> 
> When I try the sample code displayed on the Readme, I get this error when I use`Instagram4j.login()`:
> 
> `The type org.apache.http.client.ClientProtocolException cannot be resolved. It is indirectly referenced from required .class files`

Did you solve? How?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
