### ISSUE TITLE
[question] instagram fingerprint

### ISSUE THREAD

**Issue by bolds07** [instagram4j/instagram4j#423]
I would like to mock a real instagram app fingerprint in my project
by fingerprint i mean `device_id`,  `adid ` `phone_id ` `uuid `does anyone know which file instagram app persist these fields? so i can read it from a real phone (rooted)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
