### ISSUE TITLE
Confirm mail link

### ISSUE THREAD

**Issue by kodmanyagha** [instagram4j/instagram4j#424]
I can receive mail confirmation link from smtp. How can I confirm it with this library? THanks.

**Comment by yaniferhaoui** [comment]
Hi here the answer [#358 ](https://github.com/brunocvcunha/instagram4j/pull/358). 
If you want to change sms verification to email verification, change 
`challengeUrl = loginResult.getChallenge().getApi_path().substring(1);` 
to
`challengeUrl = loginResult.getChallenge().getApi_path().substring(0);`
or
`challengeUrl = loginResult.getChallenge().getApi_path().substring(2);`.
Else if that didn't function, juste remove your phone number from your Instagram account, and let only your email.

**Comment by kodmanyagha** [comment]
Thanks for your answer. I will check it.

**Comment by OmidPvh** [comment]
> Hi here the answer [#358 ](https://github.com/brunocvcunha/instagram4j/pull/358).
> If you want to change sms verification to email verification, change
> `challengeUrl = loginResult.getChallenge().getApi_path().substring(1);`
> to
> `challengeUrl = loginResult.getChallenge().getApi_path().substring(0);`
> or
> `challengeUrl = loginResult.getChallenge().getApi_path().substring(2);`.
> Else if that didn't function, juste remove your phone number from your Instagram account, and let only your email.

When i try getApi_path() return null and
when i try send -> InstagramGetChallengeRequest return JsonParseException.
What Should i do?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
