### ISSUE TITLE
Like a comment by id

### ISSUE THREAD

**Issue by Edeori** [instagram4j/instagram4j#428]
When I try to like a comment with InstagramLikeRequest, then I get the following result:

> Reading InstagramLikeResult from {"message": "Sorry, this media has been deleted", "like_error_key": "like_media_does_not_exist", "status": "fail"}

My code for this action is the following (please tell me if I'm wrong):

```
InstagramComment topComment = comments.get(0);

			instagram4j.sendRequest(new InstagramLikeRequest(topComment.getPk()));
```

Thank you!

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
