### ISSUE TITLE
Android Api

### ISSUE THREAD

**Issue by MuhammedAlmaz** [instagram4j/instagram4j#429]
https://github.com/charlieAndroidDev/Instagram4Android

This repo deleted. It's doesn't work anymore. Can i use this library on android ?

**Comment by jcagz96** [comment]
why was deleted?

**Comment by MuhammedAlmaz** [comment]
@jcagz96 idk my friend. I need alternative of it.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
