### ISSUE TITLE
.class not found

### ISSUE THREAD

**Issue by fulviob91** [instagram4j/instagram4j#431]
Ciao,
i have this error 
The type org.apache.http.client.ClientProtocolException cannot be resolved. It is indirectly referenced from required .class files
	The method login() from the type Instagram4j refers to the missing type ClientProtocolException

during login at this point (bold)
	Instagram4j instagram = Instagram4j.builder().username("username").password("password").build();
		instagram.setup();
		**instagram.login();**
	}

**Comment by MaMeini** [comment]
I got the same issue, any solutions found yet?

**Comment by kanekifont** [comment]
No solution guys?

**Comment by jackfetkovich** [comment]
I am having this problem as well

**Comment by Suzanskiy** [comment]
Hello! I assume you used this library as a .jar file, adding it to your project.But that's not entirely correct. It has dependencies on other libraries, which are solved through MAVEN. So you'll have to plug in like 
<dependency>
  <groupId>org.brunocvcunha.instagram4j</groupId>
  <artifactId>instagram4j</artifactId>
  <version>1.13</version>
</dependency>

**Comment by hippolyto** [comment]
> 
> 
> Hello! I assume you used this library as a .jar file, adding it to your project.But that's not entirely correct. It has dependencies on other libraries, which are solved through MAVEN. So you'll have to plug in like
> 
> ```
> <dependency>
>   <groupId>org.brunocvcunha.instagram4j</groupId>
>   <artifactId>instagram4j</artifactId>
>   <version>1.13</version>
> </dependency>
> ```

Sorry to ask... but.. how do I do it?

And which other way to solve? The apache .jar file?

**Comment by hippolyto** [comment]
> Hello! I assume you used this library as a .jar file, adding it to your project.But that's not entirely correct. It has dependencies on other libraries, which are solved through MAVEN. So you'll have to plug in like
> 
> ```
> <dependency>
>   <groupId>org.brunocvcunha.instagram4j</groupId>
>   <artifactId>instagram4j</artifactId>
>   <version>1.13</version>
> </dependency>
> ```

The problem remains. Any ideas? Thank you.

**Comment by saulneri1998** [comment]
You will have to build the jar including dependencies in case you want it as a standalone file.
Include the following in the pom file under pllugins:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-assembly-plugin</artifactId>
    <version>2.4</version>
    <configuration>
        <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
        <archive>
            <manifest>
                <mainClass>com.domain.Program</mainClass>
            </manifest>
        </archive>
    </configuration>
    <executions>
        <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
                <goal>single</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
The build again with ```man clean install```. The jar will be huge but it will include all dependencies
