### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by tonnoz** [instagram4j/instagram4j#434]
In development, I run many tests as you may expect and this result in many session that I have to terminate manually from the web client. Anybody is performing logout with I4J? If yes, how?

**Comment by tonnoz** [comment]
anyone?

**Comment by oguzose** [comment]
i think it's easy feature but I couldn't find it.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
