### ISSUE TITLE
What is the pupose of maxID in "InstagramGetUserFollowersRequest(@NonNull long userId, String maxId)"?

### ISSUE THREAD

**Issue by schreibermm** [instagram4j/instagram4j#439]
Hi, thanks for the great library!

Can you please explain how is the **maxId** used in **org.brunocvcunha.instagram4j.requests.InstagramGetUserFollowersRequest.java**?

Is it related to pagination?

Can you please provide an example of how to handle pagination?
For example a user has 1000 followers, how do I get them all? Currently the result brings only 185.

Thanks in advance.

**Comment by OmidPvh** [comment]
Hi

with maxId you can get about 15k followers of a user so this is example: 

InstagramGetUserFollowersResult followersResult = null;
maxId = null;
List<InstagramUserSummary> followers = new ArrayList<>();
while (followersResult == null || maxId != null) {
    try {
    followersResult =  instagram.sendRequest(new InstagramGetUserFollowersRequest(user_pk,maxId));

                if (followersResult != null) {
                    if (followersResult.getStatus().equals("ok")) {
                        maxId = followersResult.getNext_max_id();
                        followers.addAll(followersResult.getUsers());
                    }else{
                       break;
                    }
                }
   } catch (IOException e) {

                Thread.sleep(5000);
   }
}

**Comment by deniben** [comment]
> Hi
> 
> with maxId you can get about 15k followers of a user so this is example:
> 
> ```
>             InstagramGetUserFollowersResult followersResult = null;
>             String maxId = null;
>             List<InstagramUserSummary> followers = new ArrayList<>();
>             while (followersResult == null || maxId != null) {
>                     try {
>                            followersResult =  instagram.sendRequest(new 
>                                                         InstagramGetUserFollowersRequest(user_pk,maxId));
>                            if (followersResult != null) {
>                                   if (followersResult.getStatus().equals("ok")) {
>                                          maxId = followersResult.getNext_max_id();
>                                          followers.addAll(followersResult.getUsers());
>                                    }else{
>                                            break;
>                                    } 
>                              }
>                      } catch (IOException e) {
>                         Thread.sleep(5000);
>                      }
>             }
> ```

this is no full code. 
add 
```
if (nextMaxId == null) { break;}

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
