### ISSUE TITLE
in import has problem

### ISSUE THREAD

**Issue by behroozmaghsodi** [instagram4j/instagram4j#44]
hi dear 
when i want import project hase problem 
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (execution: default-compile, phase: compile)

plz help me
tanks

**Comment by patriotaki** [comment]
you need to download other libraries 
these are all the libraries i have imported in order to get the api to work

https://www.screencast.com/t/FEHcZi5tu

**Comment by behroozmaghsodi** [comment]
dear can you send me this folder

**Comment by patriotaki** [comment]
[IG API  JARS.zip](https://github.com/brunocvcunha/instagram4j/files/1231735/IG.API.JARS.zip)

**Comment by behroozmaghsodi** [comment]
tanks
when i import all jar  projact has very problen such as
image has attach

**Comment by behroozmaghsodi** [comment]
https://ibb.co/dzcHMa

error   when add  jar file

**Comment by brunocvcunha** [comment]
The project is managed by Maven. The best way to make it work is `mvn eclipse:eclipse` then import it in your IDE.

**Comment by krismorte** [comment]
Which edition?
