### ISSUE TITLE
How to login in correctly

### ISSUE THREAD

**Issue by AgressoRps** [instagram4j/instagram4j#440]
I’m trying to understand how to use the library, but since there are no lessons, it is extremely difficult to understand.
If you can tell me how to login in correctly. Any attempt requires the input of a code from the mail. I can enter it, but how then to store the session or cookies, all the login information in order to avoid this in the future.

The following question arises, if I keep the login information, then how to install it? I do not see set methods for cookies and other things

**Comment by AgressoRps** [comment]
Уже разобрался, спасибо

**Comment by TigerLvd** [comment]
How did you solve the problem?))
