### ISSUE TITLE
Continuous Timeout for send request ! 

### ISSUE THREAD

**Issue by OmidPvh** [instagram4j/instagram4j#445]
Hi

After a short time when i try send request , I get Timeout Exception for long time.
i Tested send request in Thread and again in Future with ExecutorService but still same problem!
How can i send request without get timeout in this situation?

Please help..

**Comment by jxin19** [comment]
let me see the code

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
