### ISSUE TITLE
Upload photo issue

### ISSUE THREAD

**Issue by csvolvan** [instagram4j/instagram4j#448]
When im trying to upload a photo to my feed it happens an npe exception, but file, description and Instagram4j vars are not null.

Console log: https://pastebin.com/2jhicKzP
the method in which I upload the photo
```
public void uploadPhoto(Instagram4j ig) throws IOException {
            ig.sendRequest(new InstagramUploadPhotoRequest(
                    new File("E:\\Descargas\\Pregunta.png"),
                    "sadasd"));
    }
```

**Comment by jxin19** [comment]
has the variable "ig"  instagram login information?
check again why occurred NullPointException.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
