### ISSUE TITLE
unblock doesnt work

### ISSUE THREAD

**Issue by patriotaki** [instagram4j/instagram4j#45]
when i try to unblock someone i have blocked i get null pointer exception
```
InstagramSearchUsernameResult userfrom = Instagram.sendRequest(newInstagramSearchUsernameRequest("luxcashery"));
instagram.sendRequest(new InstagramUnblockRequest(userfrom.getUser().pk));
```
`java.lang.NullPointerException`

**Comment by patriotaki** [comment]
any tips?

**Comment by BondarenkoEvgeny** [comment]
This code works without errors if "Instagram" not null.

**Comment by jumaskow** [comment]
Probably because the first request isn't done yet. I have the same problem.
