### ISSUE TITLE
Get post media from link

### ISSUE THREAD

**Issue by LukaskzB** [instagram4j/instagram4j#452]
How can I get the post media from a link?

**Comment by jxin19** [comment]
see the InstagramUserFeedRequest class.

**Comment by OmidPvh** [comment]
Hi 
InstagramUserFeedRequest class  is not good for a link!
imagine this link: https://www.instagram.com/p/CClpx7qsYm-/
we want get this post not searching a user post!
So how we can?

**Comment by OmidPvh** [comment]
Hi
InstagramUserFeedRequest class is not good for a link!
for example this link: https://www.instagram.com/p/CClpx7qsYm-/
we want get this post not searching a user post!
So how we can?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
