### ISSUE TITLE
Question marks instead letters

### ISSUE THREAD

**Issue by deniben** [instagram4j/instagram4j#455]
Hello! Have a problem when i try display some info i have ???????? instead letters. Example here: https://prnt.sc/t5m475
html page has ` <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>` 
When i display through console System.out.println() - correct works 
What is wrong?

**Comment by jxin19** [comment]
isn't it encoding problem?
what is original text?

**Comment by deniben** [comment]
I've solved it.
Just add  setCharacterEncoding("UTF-8") in ViewResolverRegistry
