### ISSUE TITLE
How to bring the username of all followers in instagram4j

### ISSUE THREAD

**Issue by mohamedYassen-Code** [instagram4j/instagram4j#461]
InstagramGetUserFollowersResult githubFollowers = aa.sendRequest(new InstagramGetUserFollowersRequest(userResult.getUser().usertags_count));
 List<InstagramUserSummary> users = githubFollowers.getUsers();
for (InstagramUserSummary user : users) {
       TAExWP.appendText(user.getUsername()+"\n");
       System.out.println(user.getUsername());
 }
I cannot fetch all the names of followers, when I try to get 134 results and the page has 4k + a solution to help me thanks

**Comment by jxin19** [comment]
check InstagramGetUserFollowersRequest class again.
you should add a parameter "maxId".
when request with "maxId", can respond NEXT PAGE.
Other APIs are the same.

**Comment by mohamedYassen-Code** [comment]
how

**Comment by jxin19** [comment]
@mohamedYassen-Code 
call the recursive method with 'maxId' parameter.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
