### ISSUE TITLE
how to upload a video for story?

### ISSUE THREAD

**Issue by cloud777** [instagram4j/instagram4j#464]
i found _InstagramUploadStoryPhotoRequest_ for upload a image for story, but i need upload video

**Comment by jvogit** [comment]
Currently this library does not offer uploading story video in the same manner. This has been addressed in the rewritten library (soon to push to public).

However, if you want to have a try right now the process is similar to uploading a photo. All is needed is to upload a resumable video request, a resumable photo request for a cover, a finish request and finally a configure request. You must provide the same upload_id to all requests.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
