### ISSUE TITLE
how to upload photo/album with geolocation?

### ISSUE THREAD

**Issue by jxin19** [instagram4j/instagram4j#465]
I can't find uploading photo/album with geoloation.

I think python API support that method. 
maybe related to 'kwargs' parameter on below link. 

[Python API](https://github.com/ping/instagram_private_api/blob/master/instagram_private_api/endpoints/upload.py)

how can help me? 🙂

**Comment by jvogit** [comment]
Hi, here is a sample payload to configure album/photo with geolocation that may help you right now. I assure you the rewritten library has taken care of this!
`{
   "upload_id":"1594542020056",
   "caption":"This is a test!",
   "location":"{\"external_id\":\"106048159426257\",\"name\":\"London Bridge\",\"external_source\":\"facebook_places\",\"lat\":34.4717,\"lng\":-114.347,\"address\":\"\",\"facebook_places_id\":\"106048159426257\"}",
   "media_latitude":"34.4717",
   "media_longitude":"-114.347",
   "geotag_enabled":"1",
   "posting_latitude":"34.4717",
   "posting_longitude":"-114.347"
}`

Note: location is stringified location json object. Location objects may be fetched from location_search endpoint. Notably, you must add a "facebook_places_id" with external_id as value to location object if fetched from that endpoint. I assume this may change depending on "external_source" field.

**Comment by jxin19** [comment]
@jvogit got it, I try above your mention 🙂

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
