### ISSUE TITLE
How to change profile pic

### ISSUE THREAD

**Issue by isOsman** [instagram4j/instagram4j#467]
Hi,i recently started using this lib(it great).How to upload/change logged user profile pic/avatar?

**Comment by jvogit** [comment]
I do not think this library in its current state has a request for changing profile picture.

The library is currently being rewritten, so support will be provided by then.. I can provide you steps on how to execute if you so wish to develop your own request right now.
1. Upload a resumable photo (there is a resumable photo upload request)
2. Pass the upload_id after uploading to the endpoint accounts/change_profile_picture/ to the payload under the key "upload_id"

Here is sample of correct payload:
```json
{
   "_csrftoken":"token here",
   "guid":"general uuid here",
   "device_id":"device id here",
   "phone_id":"phone id here",
   "upload_id":"1594806936039"
}
```
(just upload_id field added along with defaults for the payload)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
