### ISSUE TITLE
Need a quick response -> How get post by link like this link: https://www.instagram.com/p/CClpx7qsYm-/ ???

### ISSUE THREAD

**Issue by OmidPvh** [instagram4j/instagram4j#468]
Hi friends..
InstagramUserFeedRequest is not good for this.
so can i get post by link?

**Comment by deniben** [comment]
i used this method
`    public static String getMediaIdFromURL(String mediaCode) {
        String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
        long id = 0;
        for (int i = 0; i < mediaCode.length(); i++) {
            char c = mediaCode.charAt(i);
            id = id * 64 + alphabet.indexOf(c);
        }
        return id + "";
    }`
argument is CClpx7qsYm-, i didnt bother but you can use regex for input argument 'https://www.instagram.com/p/CClpx7qsYm-/'

**Comment by OmidPvh** [comment]
thanks but i mean get all the post by link not just Code or id.
the code you send is a part of code just for return id so what is next for get feed by id?

**Comment by OmidPvh** [comment]
> i used this method
> `
> 
> > public static String getMediaIdFromURL(String mediaCode) {
> > String alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
> > long id = 0;
> > for (int i = 0; i < mediaCode.length(); i++) {
> > char c = mediaCode.charAt(i);
> > id = id * 64 + alphabet.indexOf(c);
> > }
> > return id + "";
> > }
> 
> `
> argument is string 'CClpx7qsYm-', i didnt bother but you can use regex for input argument 'https://www.instagram.com/p/CClpx7qsYm-/'

Thanks.. but i mean get all the post by link not just return id.
the code you send is for return id so what is next for get feed by id?

**Comment by deniben** [comment]
i got it, but i can't to get feed by mediaCode. If i solved it i'll put here)

**Comment by jvogit** [comment]
Try with InstagramMediaInfoRequest to grab info for certain media
Make sure to pass in the media id (which is converted from short code from URL using method above).
Library does provide util methods to convert shortcode and back in InstagramCodeUtil but I think one is bugged there is a pull request opened with correct method for which you can use. #444

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
