### ISSUE TITLE
direct inbox

### ISSUE THREAD

**Issue by mehhrad** [instagram4j/instagram4j#47]
can i get my direct messages with this api?
 i'm gonna make a multi platform IG direct messenger : /

**Comment by koresuniku** [comment]
Join for request. Dear Bruno, using this API, can we extract conversations' content and send messages (text or picture) to the interlocutor?

**Comment by marceloferraz** [comment]
Could you guys solve it?
I am having the same doubt

**Comment by tayfunyasar** [comment]
is also getting chat history for a user possible?

**Comment by krismorte** [comment]
#154
