### ISSUE TITLE
How to get round limits "Please wait a few minutes before you try again."

### ISSUE THREAD

**Issue by deniben** [instagram4j/instagram4j#470]
org.brunocvcunha.instagram4j.requests.InstagramRequest  - Reading InstagramGetUserFollowersResult from {"message": "Please wait a few minutes before you try again.", "status": "fail"}
When i want get large amount of followers or comments i get this error because limits. Maybe do you have solutions that you using. Thanks

**Comment by jvogit** [comment]
This is limit placed by instagram temporarily if you are sending too many requests within a short period of time (also happens in app after certain time). I recommend setting a delay in between requests. What the delay is and what limits Instagram placed is not known. Please do not try to spam requests with library.

**Comment by deniben** [comment]
> This is limit placed by instagram temporarily if you are sending too many requests within a short period of time (also happens in app after certain time). I recommend setting a delay in between requests. What the delay is and what limits Instagram placed is not known. Please do not try to spam requests with library.

Okay, i got it)

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
