### ISSUE TITLE
login with challenge using Spring Boot

### ISSUE THREAD

**Issue by mariano97** [instagram4j/instagram4j#474]
I use Spring Boot and I am trying to log in and perform the instagram challenge in order to get the number of followers from the user, but when I ask for the security code an Exception is thrown.

**Comment by mhorizon** [comment]
it is my problem to.

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
