### ISSUE TITLE
Photo Uploaded but not showed in instagram

### ISSUE THREAD

**Issue by mhorizon** [instagram4j/instagram4j#475]
# Photo Uploaded successfully but not showed in instagram account in many many times!
 ## hi
i am using InstagramUploadPhotoRequest to upload photo to my Instagram account and uploading process finished completely and successfully. status in result is "ok" but uploaded photo not showed in my instagram account in many times.
**uploading stack trace:**
`- Setup...
- Device ID is: android-486d4feeeab9c28b, random id: 4443cfd4-c54f-4223-af23-c5361a3593ff
- Logging with user my.username and password ***********
- Sending request: org.brunocvcunha.instagram4j.requests.InstagramLoginRequest
- Reading InstagramLoginResult from {"logged_in_user": {"pk": 12345678909, "username": "my.username", "full_name": "", "is_private": false, "profile_pic_url": "https
- Sending request: org.brunocvcunha.instagram4j.requests.InstagramUploadPhotoRequest
- Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramUploadResumablePhotoRequest
- The upload id is 1596093606681
- Reading InstagramUploadPhotoResult from {"upload_id": "1596093606681", "xsharing_nonces": {}, "status": "ok"}
- Upload photo result: StatusResult(status=ok, message=null, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null)
- Sending request: org.brunocvcunha.instagram4j.requests.internal.InstagramConfigurePhotoRequest
- Reading InstagramConfigureMediaResult from {"media": {"taken_at": 1596093627, "pk": 2364527181927551152, "id": "2364527181927551152_39845003030", "device_timestamp": 15960
- Configure photo result: InstagramConfigureMediaResult(super=StatusResult(status=ok, message=null, spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), ................
`
========
### how solve this problem uploading is ok but not shown in my instagram account!!!
please help me to solve this problem
tnx

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.

Please reopen if issue persists in rewrite.
