### ISSUE TITLE
SocketTimeoutException Timeout

### ISSUE THREAD

**Issue by 200317314** [instagram4j/instagram4j#479]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ X] I read the README.md
- [ X] I looked over the examples and wiki
- [ X] my issue hasn't been asked or solved before

---

### Describe the bug

Please provide a concise description of your bug and relevant code.
I have a bot just monitoring the amount of people who follow my instagram page and prints their username.

### How to reproduce

1. Specify steps to reproduce
```java
client.getActions().users().findByUsername(username).performAction(FriendshipsActionRequest.FriendshipsAction.CREATE);
I have this go off every hour or so.
```
### Expected behavior

Please describe expected behavior or output

It was supposed to unfollow the user, but it got socket timed out.

### Actual behavior

Please post output log or result from the bug.

```Aug 06 17:58:45 dedi1 instagrambot[24905]: Exception in thread "main" java.net.SocketTimeoutException: timeout
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at com.github.instagram4j.instagram4j.IGClient.sendRequest(IGClient.java:121)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at com.github.instagram4j.instagram4j.IGClient.sendRequest(IGClient.java:110)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at com.github.instagram4j.instagram4j.requests.IGRequest.execute(IGRequest.java:41)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at com.github.instagram4j.instagram4j.actions.users.UserAction.performAction(UserAction.java:42)
Aug 06 17:58:45 dedi1 instagrambot[24905]:         at Main.main(Main.java:70)
```

**Comment by jvogit** [comment]
Perhaps try setting a larger timeout for OkHttpClient [here](https://stackoverflow.com/questions/40170666/java-net-sockettimeoutexception-in-okhttp)

Unfortunately it may happen from time to time due to various reasons. Try to handle timeouts if they occur and retry.

**Comment by 200317314** [comment]
For some reason the DESTROY action does not unfollow users.
```client.actions().users().findByUsername(user).performAction(FriendshipsActionRequest.FriendshipsAction.DESTROY);```
it does for like 1-2 of them but not all of them?

**Comment by jvogit** [comment]
> For some reason the DESTROY action does not unfollow users.
> `client.actions().users().findByUsername(user).performAction(FriendshipsActionRequest.FriendshipsAction.DESTROY);`
> it does for like 1-2 of them but not all of them?

You should enable and provide logs if you can. You may further add a logging interceptor like in this example [here](https://github.com/instagram4j/instagram4j/blob/4d6f313f02014fba64df6021a32ca3a6a749ea6e/src/examples/java/serialize/SerializeTestUtil.java#L55).

Unfortunately it sounds like you may be rate limited or temporarily banned. Instagram does not allow many repeated actions in a short time frame. I recall Instagram does have a set limited of actions such as follow/unfollow.

**Comment by 200317314** [comment]
I am not banned or rate limited, because on my phone i can follow and such with no prompt telling me im banned, i am also waiting a long time in between actions.
how can i get the PK's of all the users an account follows, about 100 or so.

**Comment by jvogit** [comment]
> I am not banned or rate limited, because on my phone i can follow and such with no prompt telling me im banned, i am also waiting a long time in between actions.
> how can i get the PK's of all the users an account follows, about 100 or so.

Without logs of the request or response I can't further explore that issue.

Use a FeedIterable along with a Friendships. An example of forming a request is [here](https://github.com/instagram4j/instagram4j/blob/4d6f313f02014fba64df6021a32ca3a6a749ea6e/src/examples/java/friendships/FriendshipsTest.java#L68). Example using a FeedIterable is [here](https://github.com/instagram4j/instagram4j/blob/4d6f313f02014fba64df6021a32ca3a6a749ea6e/src/examples/java/actions/FeedIterableTest.java#L21).

**Comment by jvogit** [comment]
Closed due to inactivity. I'm assuming the issue is partially resolved.
