### ISSUE TITLE
pre and post login flow requests

### ISSUE THREAD

**Issue by mokhtarabadi** [instagram4j/instagram4j#480]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ X ] I read the README.md
- [ X ] I looked over the examples and wiki
- [ X ] my issue hasn't been asked or solved before

---

### Describe your feature request

Please describe as concisely as possible request for new functionality or modifications to an existing one.

Can you implement pre-login and post-login requests, so we can exactly simulate Instagram android app to avoid detection or other things by Instagram 

for example, you can take a look at javascript private Instagram at [https://github.com/dilame/instagram-private-api/blob/master/src/services/simulate.service.ts](https://github.com/dilame/instagram-private-api/blob/master/src/services/simulate.service.ts)

**Comment by jvogit** [comment]
Feature implemented in new [build](https://github.com/instagram4j/instagram4j/issues/459)
[ ![Download](null/packages/instagram4j/maven/instagram4j/images/download.svg?version=develop-40333b6) ](https://bintray.com/instagram4j/maven/instagram4j/develop-40333b6/link)
