### ISSUE TITLE
 Error executing authentication with Challenge login

### ISSUE THREAD

**Issue by viktordart** [instagram4j/instagram4j#481]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ X] I read the README.md
- [ X] I looked over the examples and wiki
- [ X] my issue hasn't been asked or solved before

---

### Describe the bug

I execute example with challenge login and obtain error null pointer exception

Please provide a concise description of your bug and relevant code.

### How to reproduce

1. Specify steps to reproduce

> Scanner scanner = new Scanner(System.in);
> 
>     // Callable that returns inputted code from System.in
>     Callable<String> inputCode = () -> {
>         System.out.print("Please input code: ");
>         return scanner.nextLine();
>     };
> 
>     // handler for challenge login
>     LoginHandler challengeHandler = (client, response) -> {
>         // included utility to resolve challenges
>         // may specify retries. default is 3
>         return IGChallengeUtils.resolve(client, response, inputCode);
>     };
>         
>         IGClient client = IGClient.builder()
>         .username("XXXX")
>         .password("XXXX")
>         .onChallenge(challengeHandler)
>         .login();
>     }

### Expected behavior

Log in

### Actual behavior

[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending sync request. . .
[main] INFO com.github.instagram4j.instagram4j.IGClient - Response for com.github.instagram4j.instagram4j.requests.qe.QeSyncRequest : 200
[main] INFO com.github.instagram4j.instagram4j.IGClient - Encryption key id : 156
[main] INFO com.github.instagram4j.instagram4j.IGClient - Encryption key (truncated) : SUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFudExrQzZsMnErNDgwUmJtSXZkbgo1V25CbjFNb1dQWWpoNjRIVmF6dHlRY3BERUhFdG9DaXZBY2FjSWE1T1ZvaWxyWFJObVg4QTFpQ0w0dXBWOEMxCjFPNUJUdUhlUjFYdGxsV1EyN3pCRHZGMHNEQk92L2RyR0RMQWtYZGxkaUFUOWJrOW8wUlE0NzA1OE5meXNUREIKU3hFY080S2hXN0Izbk14bnhPaDN3YktWQUFVKzVKd2FsV0hLSk9QOFRYcEtHZkJyWGJvVXBTTElTL2xENjkxKwpHdVE3anBoRDZPZy9qdlhnN1V5bUV1NHBtMnV4R2JrL0RVajdRZytWaG1vZG0vQWc2U2ZqTGRkbzlBOVlYN1kxCm5mMmdSbGZ2MzFHQmF2Y01HUDBYZWNSamVtWlhSL1NQWDFIbkl2b2FyY3J6QVRsV0gzdUhVOTBMYXNTaEczcjQKaXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
[main] INFO com.github.instagram4j.instagram4j.IGClient - Logging in. . .
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : com.github.instagram4j.instagram4j.requests.accounts.AccountsLoginRequest
[main] INFO com.github.instagram4j.instagram4j.IGClient - Response for com.github.instagram4j.instagram4j.requests.accounts.AccountsLoginRequest : 400
[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : com.github.instagram4j.instagram4j.requests.challenge.ChallengeStateGetRequest
[main] INFO com.github.instagram4j.instagram4j.IGClient - Response for com.github.instagram4j.instagram4j.requests.challenge.ChallengeStateGetRequest : 400
Exception in thread "main" java.lang.NullPointerException
	at com.github.instagram4j.instagram4j.utils.IGChallengeUtils.resolve(IGChallengeUtils.java:57)
	at com.github.instagram4j.instagram4j.utils.IGChallengeUtils.resolve(IGChallengeUtils.java:83)
	at atribus.apiinstagram.ApiInstagram.lambda$main$1(ApiInstagram.java:37)
	at com.github.instagram4j.instagram4j.IGClient$Builder.login(IGClient.java:213)
	at atribus.apiinstagram.ApiInstagram.main(ApiInstagram.java:44)
/home/victor/.cache/netbeans/11.0/executor-snippets/run.xml:111: The following error occurred while executing this line:
/home/victor/.cache/netbeans/11.0/executor-snippets/run.xml:94: Java returned: 1
BUILD FAILED (total time: 2 seconds)

Thanks!

**Comment by jvogit** [comment]
Hi, if you could provide full response bodies that would be great. Please redact any personal, private, identifiable information.

Please see [here](https://github.com/instagram4j/instagram4j/blob/dbe44a32fa0d59169d85752c88e79cdeb8e472f6/src/examples/java/serialize/SerializeTestUtil.java#L55) to create a logging interceptor to OkHttpClient to log body responses (You will need to add logging [interceptor dependency](https://github.com/instagram4j/instagram4j/blob/dbe44a32fa0d59169d85752c88e79cdeb8e472f6/src/examples/java/serialize/SerializeTestUtil.java#L39)). Then set the new OkHttpClient to be used in IGClient. See [here](https://github.com/instagram4j/instagram4j/blob/dbe44a32fa0d59169d85752c88e79cdeb8e472f6/src/examples/java/serialize/SerializeTestUtil.java#L92) and [here](https://github.com/instagram4j/instagram4j/blob/dbe44a32fa0d59169d85752c88e79cdeb8e472f6/src/examples/java/serialize/SerializeTestUtil.java#L39).

Sorry for hassle on logging, I think I will log truncated responses by default in future and add a tutorial to enable full logging.

**Comment by viktordart** [comment]
I'm on vacation. in two weeks I test the comments and post the results. Thank you

**Comment by jvogit** [comment]
> I'm on vacation. in two weeks I test the comments and post the results. Thank you

I've pushed a new develop build. Please test and log your issue against new build if possible. Thanks!

**Comment by viktordart** [comment]
Hello,
I have tried the latest build. The result is:

[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/qe/sync/
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ : 200
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ with body (truncated) : {"experiments": [{"name": "ig_android_shopping_checkout_signaling", "group": "rollout", "additional_
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/accounts/login/
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ : 400
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ with body (truncated) : {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3953510691
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/challenge/39535106918/dzoMUlI6TH/?guid=d907cdf8-5f2d-4cff-bacf-75e6a0354e8e&device_id=android-fd7a21c30e900e1f
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/challenge/39535106918/dzoMUlI6TH/?guid=d907cdf8-5f2d-4cff-bacf-75e6a0354e8e&device_id=android-fd7a21c30e900e1f : 400
[OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/challenge/39535106918/dzoMUlI6TH/?guid=d907cdf8-5f2d-4cff-bacf-75e6a0354e8e&device_id=android-fd7a21c30e900e1f with body (truncated) : {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3953510691
Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: challenge_required
	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:88)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:154)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:138)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException: challenge_required
	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:151)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)

**Comment by jvogit** [comment]
> Hello,
> I have tried the latest build. The result is:
> 
> [main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/qe/sync/
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ : 200
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ with body (truncated) : {"experiments": [{"name": "ig_android_shopping_checkout_signaling", "group": "rollout", "additional_
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/accounts/login/
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ : 400
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ with body (truncated) : {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3953510691
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/challenge/39535106918/dzoMUlI6TH/?guid=d907cdf8-5f2d-4cff-bacf-75e6a0354e8e&device_id=android-fd7a21c30e900e1f
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/challenge/39535106918/dzoMUlI6TH/?guid=d907cdf8-5f2d-4cff-bacf-75e6a0354e8e&device_id=android-fd7a21c30e900e1f : 400
> [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/challenge/39535106918/dzoMUlI6TH/?guid=d907cdf8-5f2d-4cff-bacf-75e6a0354e8e&device_id=android-fd7a21c30e900e1f with body (truncated) : {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3953510691
> Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: challenge_required
> at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:88)
> at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:154)
> at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
> at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
> at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
> at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
> at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:138)
> at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException: challenge_required
> at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
> at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:151)
> at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
> at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
> 
> Do you want the test user?
> Thanks!

Instagram must've changed the way to handle challenges. If you could change log level to debug and post your logs it might be helpful. If you could provide me the test user through email that would also be good. If you have the means you can try to intercept the challenge flow requests and document them. Here is [guide.](https://github.com/instagram4j/instagram4j/wiki/Contributing-requests#intercepting-requests)

**Comment by viktordart** [comment]
OK!
In the last build, the message is correct. Account banned. 
Thanks!

**Comment by jvogit** [comment]
> Hi!
> Other different error:
> 
> `[main] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/qe/sync/ [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ : 200 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/qe/sync/ with body (truncated) : {"experiments": [{"name": "ig_android_shopping_checkout_signaling", "group": "rollout", "additional_ [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/accounts/login/ [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ : 400 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/accounts/login/ with body (truncated) : {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3955114269 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Sending request : https://i.instagram.com/api/v1/challenge/39551142698/n2aYx3XfwT/?guid=d4fcad73-8694-456b-a7b9-eb733bb7e2f4&device_id=android-01c8582cb8e94f53 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/challenge/39551142698/n2aYx3XfwT/?guid=d4fcad73-8694-456b-a7b9-eb733bb7e2f4&device_id=android-01c8582cb8e94f53 : 400 [OkHttp https://i.instagram.com/...] INFO com.github.instagram4j.instagram4j.IGClient - Response for https://i.instagram.com/api/v1/challenge/39551142698/n2aYx3XfwT/?guid=d4fcad73-8694-456b-a7b9-eb733bb7e2f4&device_id=android-01c8582cb8e94f53 with body (truncated) : {"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/3955114269 Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: challenge_required at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:85) at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5(IGClient.java:151) at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870) at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852) at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:135) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException: challenge_required at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72) at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4(IGClient.java:148) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ... 7 more `
> 
> Where is your email to send user?
> Thanks!

Email is on my profile.

**Comment by viktordart** [comment]
Ok!Sorry. I send email. Thanks

**Comment by jvogit** [comment]
> Ok!Sorry. I send email. Thanks

Hi, it seems the challenge requires entering a phone number first to verify. Please verify the account manually if possible. There is a request from the nodejs library to send a phone number although I'd imagine it'd be easier to verify manually.
