### ISSUE TITLE
InstagramGetUserFollowersRequest not working

### ISSUE THREAD

**Issue by oguzose** [instagram4j/instagram4j#486]
InstagramGetUserFollowersRequest not working today, Error message follows;

InstagramGetUserFollowersResult(super=StatusResult(status=fail, **message**=Please wait a few minutes before you try again., spam=false, lock=false, feedback_title=null, feedback_message=null, error_type=null, checkpoint_url=null), big_list=false, next_max_id=null, page_size=0, users=null)

**Comment by jvogit** [comment]
It seems you are using the old library. Support for it is discontinued because of the rewritten version. Although there are no stable releases yet, you may use the develop builds release, or jitpack to use the latest snapshot.
