### ISSUE TITLE
[1.14] InstagramEditMediaRequest cannot update IGTV post

### ISSUE THREAD

**Issue by cyrus07424** [instagram4j/instagram4j#488]
I am using instagram4j 1.14.
`InstagramEditMediaRequest` cannot update IGTV post.
When send `InstagramEditMediaRequest` it returns just `Oops, an error occurred.`

How to update IGTV post or how to detect IGTV post it is?

Here is my sample code.
```java
InstagramFeedResult instagramFeedResult = instagram4j.sendRequest(new InstagramUserFeedRequest(userId));
for (InstagramFeedItem instagramFeedItem : instagramFeedResult.getItems()) {
    if (instagramFeedItem.getMedia_type() == 2 && 60.067 < instagramFeedItem.getVideo_duration()) {
        // maybe IGTV post?
    }
}
```

**Comment by jvogit** [comment]
Edit request now has boolean field for igtv preview in 2.0.0 release. (set true in constructor)

[Here](https://github.com/instagram4j/instagram4j/blob/698af99417c75389a15fbe1f189d52f2797d8794/src/main/java/com/github/instagram4j/instagram4j/requests/media/MediaEditRequest.java#L18)
