### ISSUE TITLE
MediaId

### ISSUE THREAD

**Issue by EzxD** [instagram4j/instagram4j#490]
Hello how can I get a mediaid out of a link? 
best regards

**Comment by jvogit** [comment]
Example: https://www.instagram.com/p/CClpx7qsYm-/
```
// url code to pk (media id)
long media_id = IGUtils.fromCode("CClpx7qsYm-");
// vice versa
String url_code = IGUtils.toCode(media_id);
```

**Comment by EzxD** [comment]
Thats only working for public posts not for private posts. Private posts look like this: 
https://www.instagram.com/p/BtTnuFVhN0c-dH1F9Ma1DL134F9T9gdtlvVN8I0/

They are way longer

**Comment by jvogit** [comment]
It looks base64 encoded, but I do not currently know how to reverse it into proper id. Anyways, it is a private post, so I don't think it is right or useful to be able to reverse it. Usually the media id is already accessible by calling the user feed endpoint if the account is allowed to view posts from the private user. Library is only meant to replicate functions available to Android application. Perhaps someone can reverse it or I may try to look further into it if I have time.
