### ISSUE TITLE
How to Set device in client builder？

### ISSUE THREAD

**Issue by TomyKissy** [instagram4j/instagram4j#491]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ ] I read the README.md
- [ ] I looked over the examples and wiki
- [ ] my issue hasn't been asked or solved before

---

### Describe your feature request

Please describe as concisely as possible request for new functionality or modifications to an existing one.

**Comment by jvogit** [comment]
```
        IGClient client = IGClient.builder()
                .username(username)
                .password(password)
                .device(IGAndroidDevice.GOOD_DEVICES[1])
                .login();
```

For list of good android devices see [here](https://github.com/instagram4j/instagram4j/blob/abe7fcef2c494956d8005503e36f38112c9e47fc/src/main/java/com/github/instagram4j/instagram4j/IGAndroidDevice.java#L39). Or you may make your own custom device for custom user agent.
