### ISSUE TITLE
ProfilePic implements Serializable

### ISSUE THREAD

**Issue by TomyKissy** [instagram4j/instagram4j#493]
hi，I need to store userInfo but I found that the class ProfilePic didn't  implements Serializable.

**Comment by jvogit** [comment]
Not every class is serializable through Java, and if you need that functionality you may implement your own serializable class. 

Another way is to serialize/deserialize using json. Every model and response here is serializable through JSON using jackson.

``java
// serialize POJO into json string
IGUtils.objectToJson(userObject);
// deserialize json string into object
// e.g. attempting to deserialize json string into User object
IGUtils.jsonToObject(jsonString, User.class);
```
