### ISSUE TITLE
5xx Server Error

### ISSUE THREAD

**Issue by viktordart** [instagram4j/instagram4j#494]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [X] I read the README.md
- [X] I looked over the examples and wiki
- [X] my issue hasn't been asked or solved before

---

### Describe the bug

Search tag toquedequeda error 502 when recovery information pagination > 100

### How to reproduce

`if(pag==1){
                    response = igClient.sendRequest(new FeedTagRequest(searchApi.getSearch())).join();
                }else{
                    if(response!=null && response.getNext_max_id()!=null && response.isMore_available()){
                        Pagination.pause(logger);
                        response = new FeedTagRequest(searchApi.getSearch(), response.getNext_max_id()).execute(igClient).join();
                    }
                }`
### Expected behavior

```
Response for https://i.instagram.com/api/v1/feed/tag/toquedequeda/ with body (truncated) : <html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</h
```

Any idea?
Thanks!

**Comment by viktordart** [comment]
If the user logs in again, the error disappears

**Comment by jvogit** [comment]
5xx errors could just be due to temporary errors server side on Instagram. There's little to be done except handle it if arises client side. This can be done using CompletableFuture exceptionally or handle method.

**Comment by viktordart** [comment]
I have a note on this subject ...
I get the 5xx error if I make a few requests in a row UsersInfoRequest. If after the error I call UsersUsernameInfoRequest to get the user information, I don't get any error.
Any ideas?

Thanks

**Comment by jvogit** [comment]
Maybe you're making requests too fast? Again 5xx errors are server sided so it's anyones' guess on what happened to cause these 5xx errors.
