### ISSUE TITLE
How add this library into the java project

### ISSUE THREAD

**Issue by ramezanzade** [instagram4j/instagram4j#495]
I have a Java project and I can't add this repository as Maven or Gradle into my project,
So what should I do?

**Comment by jvogit** [comment]
You're not using any dependency managers?

You'll have to include all the dependencies listed in the gradle as well as any other dependencies that those dependencies depend on (e.g. for okhttpclient).

Unfortunately this is not a pure Java implementation. It's recommended to use a dependency manager like maven or gradle.
