### ISSUE TITLE
Not recovery caption from media

### ISSUE THREAD

**Issue by viktordart** [instagram4j/instagram4j#496]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [X] I read the README.md
- [X] I looked over the examples and wiki
- [X] my issue hasn't been asked or solved before

---

### Describe the bug

Not recovery caption from some items

### How to reproduce

`IGResponse response =
                new MediaInfoRequest(IGUtils.fromCode("CE2EEL3FNhI") + "").execute(client).join();`

### Expected behavior

Get caption from media

### Actual behavior

Caption and message is null

**Comment by jvogit** [comment]
Working as intended. Some posts have no caption. This one doesn't.
