### ISSUE TITLE
FriendshipsShowManyRequest returns wrong isFollowed_by()

### ISSUE THREAD

**Issue by GabryDX** [instagram4j/instagram4j#497]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Describe the bug

Trying to use FriendshipsShowManyRequest giving an array of Longs (the PKs) in order to retrieve Frienship informations over a good number of PKs. I'm interested in getting the isFollowed_by() value but appears to be false even when must be true. If I use FriendshipsShowRequest it returns the correct value, with FriendshipsShowManyRequest. The following value seems to work fine instead.

### How to reproduce

I think the error can be easily reproduced, especially if you put a good number of PKs.
I'm using the lastest develop-SNAPSHOT version.

```java
IGClient client = myClient;
FriendshipsShowManyRequest show = new FriendshipsShowManyRequest(pkLongArray);
FriendshipsShowManyResponse response = show.execute(client).join();
for (Long pk : pkLongArray) {
  Friendship friendship = response.getFriendship_statuses().get(pk+"");
  System.out.println(friendship.isFollowed_by());
}
```

### Expected behavior

Response with Frienship object with correct followed_by values.

### Actual behavior

Response with Frienship object return all false followed_by values.

Thank you very much for your pacience and hoping not to bother you.

**Comment by jvogit** [comment]
The show many request does not include follow by value and many other values. Here is a sample json response.

```
{
  "friendship_statuses":{
    "18428658":{
      "following":true,
      "incoming_request":false,
      "is_bestie":false,
      "is_private":false,
      "is_restricted":false,
      "outgoing_request":false
    }
  },
  "status":"ok"
}
```

I think I will make a separate model for show many friendships object to reflect this instead of the full Friendship object. If you need this info you must use the FriendshipsShowRequest

**Comment by GabryDX** [comment]
Ok thank you very much for such a clarification.
