### ISSUE TITLE
NoClassDefFoundErorr - IGClient.builder() ... 

### ISSUE THREAD

**Issue by hooldj** [instagram4j/instagram4j#498]
I implement instagram4j library by gradle and have this code which i use on android project : 

```
public boolean login(String l, String p){
        try {
            IGConstants.client = IGConstants.client.builder().username(l).password(p).login();
        } catch (IGLoginException e) {
            log.error(String.valueOf(e));
        }
        log.info("Is logged in:"+IGConstants.client.isLoggedIn());
        return IGConstants.client.isLoggedIn();
    }
```
_(IGConstants class is not class from instagram4j lib, its my local. IGConstants.client  == IGClient client)_
This code cause next error: 
```
 Caused by: java.lang.NoClassDefFoundError: com.github.instagram4j.instagram4j.-$$Lambda$IGClient$Builder$JvEqm0HBCQNTN7uVNiGD4nlZOww
        at com.github.instagram4j.instagram4j.IGClient$Builder.<init>(IGClient.java:228)
        at com.github.instagram4j.instagram4j.IGClient.builder(IGClient.java:193)
```

**But if i try to create a new object of other classes ( for example, IGClient client = new IGClient(l,p); ) all works well.**

build.gradle file : 
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.2"
    
    defaultConfig {
        applicationId "com.example.integram_v2"
        minSdkVersion 14
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    lintOptions {
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    repositories {
        google()
        jcenter()
        maven{
            url 'https://dl.bintray.com/instagram4j/maven'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.3.0-alpha02'
    // For loading and tinting drawables on older versions of the platform
    implementation 'androidx.appcompat:appcompat-resources:1.3.0-alpha02'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    // Instagram4J lib :
    implementation 'com.github.instagram4j:instagram4j:develop-22c2bee'

    // OkHttp
    implementation 'com.squareup.okhttp3:okhttp:4.7.2'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.7.2'
    // jackson data-bind
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.11.0'
. . .
}
```

How i can resolve this problem or maybe its libraries bug?

**Comment by jvogit** [comment]
This may be due to your proguard settings. Try to exclude the library from being obfuscated. Specifically it is having trouble with LoginHandler class located inside the Builder class inside the IGClient [here](https://github.com/instagram4j/instagram4j/blob/26e3aaa0c12e8af2f201e976b3d220068c0818cb/src/main/java/com/github/instagram4j/instagram4j/IGClient.java#L285).

**Comment by hooldj** [comment]
> This may be due to your proguard settings. Try to exclude the library from being obfuscated. Specifically it is having trouble with LoginHandler class located inside the Builder class inside the IGClient [here](https://github.com/instagram4j/instagram4j/blob/26e3aaa0c12e8af2f201e976b3d220068c0818cb/src/main/java/com/github/instagram4j/instagram4j/IGClient.java#L285).
I set useProguard to false, but it does not help

**Comment by hooldj** [comment]
> This may be due to your proguard settings. Try to exclude the library from being obfuscated. Specifically it is having trouble with LoginHandler class located inside the Builder class inside the IGClient [here](https://github.com/instagram4j/instagram4j/blob/26e3aaa0c12e8af2f201e976b3d220068c0818cb/src/main/java/com/github/instagram4j/instagram4j/IGClient.java#L285).

I set useProguard to false but it does not help

**Comment by jvogit** [comment]
> > This may be due to your proguard settings. Try to exclude the library from being obfuscated. Specifically it is having trouble with LoginHandler class located inside the Builder class inside the IGClient [here](https://github.com/instagram4j/instagram4j/blob/26e3aaa0c12e8af2f201e976b3d220068c0818cb/src/main/java/com/github/instagram4j/instagram4j/IGClient.java#L285).
> 
> I set useProguard to false but it does not help

Try to clean and rebuild the app. I have tried this library in android and it is working for me. I don't know much of Android development to pinpoint your issue specifically, but I don't think it is related to the library. If you have more on this issue or future issue, I've made a gitter to avoid using GitHub issues for usage of library.
[![Gitter](https://badges.gitter.im/instagram4j/instagram4j.svg)](https://gitter.im/instagram4j/instagram4j?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
