### ISSUE TITLE
How to get the detail response of FeedReelsMediaRequest?

### ISSUE THREAD

**Issue by TomyKissy** [instagram4j/instagram4j#499]
public void testName() throws Exception {
        IGClient client = SerializeTestUtil.getClientFromSerialize("igclient.ser", "cookie.ser");
        IGResponse response =
                new FeedReelsMediaRequest("archiveDay:18116528737123990").execute(client).join();
        Assert.assertEquals("ok", response.getStatus());
        log.debug("Success");
    }

**Comment by jvogit** [comment]
What do you mean detail response?

**Comment by TomyKissy** [comment]
the likers info and the commenters info

**Comment by jvogit** [comment]
I don't think reel media has those info.
