### ISSUE TITLE
how to import it into an android project?

### ISSUE THREAD

**Issue by knissophiliac** [instagram4j/instagram4j#5]
with gradle, while building it says "Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.2 is ignored for release as it may be conflicting with the internal version provided by Android."

what should i do?

**Comment by brunocvcunha** [comment]
@knissophiliac will take a look on this! thanks for reporting this.

**Comment by brunocvcunha** [comment]
What version of Android you are using?
Found some content here that might help: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client

**Comment by Kolyall** [comment]
sdk 23 doen't support http-client, so now we can add this to gradle:
```
android {
    useLibrary 'org.apache.http.legacy'
...
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    // the support libs
    compile('org.apache.httpcomponents:httpmime:4.3.6') {
        exclude module: 'httpclient'
    }
    compile 'org.apache.httpcomponents:httpclient-android:4.3.5'
```
but your lib still have a lot of warnings, such as `MyImageUtils` and other

**Comment by Kolyall** [comment]
@brunocvcunha any updates?

**Comment by charlieNiekirk** [comment]
Posted this in the other issue but I guess it might help here as well.

Seeing as this is still open, I made a new project called Instagram4Android which is extremely heavily based in this project but also has many modifications. For example it internally uses OkHttp for the requests and I've fixed many of the bugs that Android was facing with this project. It's still very early days though and I haven't done much of a readme :)

**Comment by Kolyall** [comment]
@charlieNiekirk does your project work? can it post images to instagram?

**Comment by charlieNiekirk** [comment]
With the app I've made so far I haven't actually tested uploading, but literally all the endpoints I've tried have worked.  I could try it now if you like?

**Comment by charlieNiekirk** [comment]
OK, I've just tested uploading a photo and it works, this was the request I was most worried about because I had to make pretty drastic changes to the code but it's working great :)

**Comment by charlieNiekirk** [comment]
If you need any help getting it to work then do open an issue :)
