### ISSUE TITLE
How can get video cover (or thumbnail)

### ISSUE THREAD

**Issue by mokhtarabadi** [instagram4j/instagram4j#500]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ x ] I read the README.md
- [ x ] I looked over the examples and wiki
- [ x ] my issue hasn't been asked or solved before

---

### Question

Ask your question here. Please make sure your question has not been answered previously and you have looked over relevant examples. Please post any example code that may help others help you!

Hey, I want to get video (as feed mean TimelineVideoMedia) thumbnail but I don't know how doing that
Do I need doing it by capture a frame in video or Instagram has a cover & thumbnail image for videos, I think there is a thumbnail image because when I see user timelines in the Instagram app, the app doesn't download videos but show a thumbnail

**Comment by mokhtarabadi** [comment]
I found the problem, the TimelineVideoMedia must have image_versions2 property which contains the thumbnails

**Comment by jvogit** [comment]
Thanks, I've added the property.
