### ISSUE TITLE
How to like pictures?

### ISSUE THREAD

**Issue by An-Ngu** [instagram4j/instagram4j#501]
Dear instagram4j team,

I really appreciate the work you put into this library, thank you alot for this.
After few days i still couldn't find the method to like photos. Is it even possible or am I little blind?

I would be thankful for answer:)

Best regards, An

**Comment by jvogit** [comment]
Sorry, better documentation is needed when I have time!

Here is request.

[MediaActionRequest](https://github.com/instagram4j/instagram4j/blob/develop/src/main/java/com/github/instagram4j/instagram4j/requests/media/MediaActionRequest.java)
