### ISSUE TITLE
DiscoverTopicalExploreRequest is outdated and nonfunctional. Please create explore end point.

### ISSUE THREAD

**Issue by mayurmunshi009** [instagram4j/instagram4j#509]
### Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored.

Please do not post screenshots of code output
Wrap code in a codeblock
exhibiting spam behavior or "evil" behavior will have the issue ignored
Please make sure your issue hasn't been asked before
Please complete the checklist below (mark boxes [ ] with [x]).

---

### Pre-Checklist
I made sure...

[X ] I read the README.md
[X ] I looked over the examples and wiki
[X] my issue hasn't been asked or solved before

---

### Describe your feature request

The link for DiscoverTopicalExploreRequest is outdated and nonfunctional. The link has been removed as legacy api is non functional. Please replace it with /explore endpoint and create a process to consume the information- paginated or non-paginated in the form of JSON

**Comment by jvogit** [comment]
Is the topical explore feed endpoint not working?

It seems to still work, unless there is a new endpoint in the new Instagram versions which I may not have been caught up on.

Can you elaborate more?
