### ISSUE TITLE
Feature to read/ consume '/explore'

### ISSUE THREAD

**Issue by mayurmunshi009** [instagram4j/instagram4j#510]
### Issue Template Requirements
Issue must be of the specified template and follow these requirements or it will be ignored.

Please do not post screenshots of code output
Wrap code in a codeblock
exhibiting spam behavior or "evil" behavior will have the issue ignored
Please make sure your issue hasn't been asked before
Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist
I made sure...

[X ] I read the README.md
[X] I looked over the examples and wiki
[ X] my issue hasn't been asked or solved before

---

### Describe your feature request

With topical explore broken and /explore working please create a system to consume /explore and its contents in JSON form as paginated or non paginated form. This could be supported by IG Client

**Comment by jvogit** [comment]
Since an issue is already created on this.
