### ISSUE TITLE
Feature to fetch media and its details such as User name, caption, likes of media of followed account/other user in json format

### ISSUE THREAD

**Issue by mayurmunshi009** [instagram4j/instagram4j#511]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored.

Please do not post screenshots of code output
Wrap code in a codeblock
exhibiting spam behavior or "evil" behavior will have the issue ignored
Please make sure your issue hasn't been asked before
Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x ] I read the README.md
- [x ] I looked over the examples and wiki
- [x ] my issue hasn't been asked or solved before

---

### Describe your feature request

Feature to fetch media and its details such as User name, caption, likes of media of followed account/other user in json format

**Comment by jvogit** [comment]
Is [MediaInfoRequest](https://github.com/instagram4j/instagram4j/blob/develop/src/main/java/com/github/instagram4j/instagram4j/requests/media/MediaInfoRequest.java) suited for your needs?
