### ISSUE TITLE
Fetch own publication

### ISSUE THREAD

**Issue by Miloune** [instagram4j/instagram4j#512]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

Hello,
I would like to know if it's possible to retrieve the instagram post on which account i'm logged in?
Regards

**Comment by jvogit** [comment]
How do you mean? Are you trying to fetch posts from a user?

**Comment by Miloune** [comment]
Yes, especially my own posts

**Comment by jvogit** [comment]
Use [FeedUserRequest](https://github.com/instagram4j/instagram4j/blob/develop/src/main/java/com/github/instagram4j/instagram4j/requests/feed/FeedUserRequest.java)

[Example](https://github.com/instagram4j/instagram4j/blob/develop/src/examples/java/feed/FeedUserRequestTest.java)

**Comment by Miloune** [comment]
Thank you, exactly what I was looking for :)
