### ISSUE TITLE
Why this library always use same device?

### ISSUE THREAD

**Issue by mokhtarabadi** [instagram4j/instagram4j#515]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [ x ] I read the README.md
- [ x ] I looked over the examples and wiki
- [ x ] my issue hasn't been asked or solved before

---

### Question

Ask your question here. Please make sure your question has not been answered previously and you have looked over relevant examples. Please post any example code that may help others help you!

I see IGClient always uses the same android device (Samsung SM-G935F), this is a bug or other thing?

I mean [here](https://github.com/instagram4j/instagram4j/blob/ce2ccb28c9a57d3adfb02160a8fa366fa1ad067f/src/main/java/com/github/instagram4j/instagram4j/IGClient.java#L63)

**Comment by samcortezzz** [comment]
Not sure why, but i'm assuming this is just for the sake of it. There is an array with multiple devices and the first key in this array seems to work. Have not tested others yet but you could change the key in this line or add a randomizer for the key.

`private IGDevice device = IGAndroidDevice.GOOD_DEVICES[0];
`

**Comment by jvogit** [comment]
The builder and IGClient should have a device setter method where you can set your device to any one of the good devices listed in IGANdroidDevice GOOD_DEVICES array or even supply your own. (It is device() for the builder). AFAIK, this library has always chosen this device but I suppose I can add a randomized device instead.
