### ISSUE TITLE
How does the login (and its encryption) work? I can login with different passwords

### ISSUE THREAD

**Issue by samcortezzz** [instagram4j/instagram4j#517]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

I noticed I can login with 2 different passwords. Lets say my password is test1234, that obviously works. But then I tried to login with test12342 and test12345 which should be incorrect, but weirdly that works as well! However test1233 and similar variants doesn't work. How is this possible?

How does the encryption of the password at login work? I'm assuming it has something to do with that.

I tried looking into the code but it seems like the encrypted password is sent as payload/body to Instagram to perform a login, how can Instagram login with an encrypted password? Especially when the password encryptor contains a randomizer?

**Comment by jvogit** [comment]
The password is encrypted with Instagram's public key (received from header) and sent as a payload. From there, it is Instagram servers that decode and retrieve the password. Previously, passwords were sent plain text in payload, but newer versions introduced this extra encryption step. This is as far as I know.

I've also experienced this behavior, and I suspect it might be some collision on their end.
