### ISSUE TITLE
Logging in with multiple users

### ISSUE THREAD

**Issue by Athamax** [instagram4j/instagram4j#52]
If I try to login with two users one after the other, the second user gets an "Oops, something went wrong.." error and cannot login.

Basically it appears as though only one session can be active at a time.

Any workaround for this ?

**Comment by brunocvcunha** [comment]
Can you paste the output? Where it gives the error?
I already ran using multiple users without a problem. Doesn't seem to have anything static in the Instagram4j, so you have to create another instance of that class.
