### ISSUE TITLE
How does instagram4j work?

### ISSUE THREAD

**Issue by OnlyOneMoreHour** [instagram4j/instagram4j#521]
Hello 

I am trying to figure out how instagram4j works. Does it emulate the android device itself or is it transmitting my login information to some other server which runs the android emulation?

Kind regards,

**Comment by jvogit** [comment]
It is essentially a client for Instagram in Java. It uses the same requests as Android (This is the simulation). In theory, this client acts like the Instagram app for Android. This does not connect to any other server except Insatgram's.
