### ISSUE TITLE
How to catch the CompletionException to handle a bad response?

### ISSUE THREAD

**Issue by samcortezzz** [instagram4j/instagram4j#522]
Hi,

I'm trying to handle bad responses like "feedback required" which is caused by an IG action block. Eventually I want to program everything in completable futures but for now I'm trying this:

```
try {
    IGResponse ir = new MediaCommentRequest("invalid", "Nice!").execute(c).join();
} catch (IGResponseException e) {
    System.out.println("[(" + e.getResponse().getStatus() + ") " + e.getResponse().getFeedback_title() + "] " + e.getResponse().getMessage() + ": " + e.getResponse().getFeedback_message());
}
```

I can't catch the IGResponseException because it throws a CompletionException first like this:
`Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: feedback_required`

The best thing I could came up with was the following piece of code:
```
System.out.println("Comment");
IGResponse r = null;
try {
    try {
        r = new MediaCommentRequest("invalid", "Nice!").execute(c).join();
    } catch (CompletionException e) {
        throw e.getCause();
    }
} catch (IGResponseException e) {
    System.out.println("[(" + e.getResponse().getStatus() + ") " + e.getResponse().getFeedback_title() + "] " + e.getResponse().getMessage() + ": " + e.getResponse().getFeedback_message());
}
System.out.println("Done");
return r;
```
This does however seem a little bad. How can I receive the response in the first try catch?

How do I read the response programmatically?

**Comment by jvogit** [comment]
> Hi,
> 
> I'm trying to handle bad responses like "feedback required" which is caused by an IG action block. Eventually I want to program everything in completable futures but for now I'm trying this:
> 
> ```
> try {
>     IGResponse ir = new MediaCommentRequest("invalid", "Nice!").execute(c).join();
> } catch (IGResponseException e) {
>     System.out.println("[(" + e.getResponse().getStatus() + ") " + e.getResponse().getFeedback_title() + "] " + e.getResponse().getMessage() + ": " + e.getResponse().getFeedback_message());
> }
> ```
> 
> I can't catch the IGResponseException because it throws a CompletionException first like this:
> `Exception in thread "main" java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException: feedback_required`
> 
> The best thing I could came up with was the following piece of code:
> 
> ```
> System.out.println("Comment");
> IGResponse r = null;
> try {
>     try {
>         r = new MediaCommentRequest("invalid", "Nice!").execute(c).join();
>     } catch (CompletionException e) {
>         throw e.getCause();
>     }
> } catch (IGResponseException e) {
>     System.out.println("[(" + e.getResponse().getStatus() + ") " + e.getResponse().getFeedback_title() + "] " + e.getResponse().getMessage() + ": " + e.getResponse().getFeedback_message());
> }
> System.out.println("Done");
> return r;
> ```
> 
> This does however seem a little bad. How can I receive the response in the first try catch?
> 
> How do I read the response programmatically?

Please look over how to use Java's CompletableFutures to handle exceptions by using exceptionally.

Here is an [example](https://github.com/instagram4j/instagram4j#simple-example).

Here is an [example function](https://github.com/instagram4j/instagram4j/blob/ce2ccb28c9a57d3adfb02160a8fa366fa1ad067f/src/main/java/com/github/instagram4j/instagram4j/utils/IGChallengeUtils.java#L20) that deals when an exception occurs.

To get the actual IGResponseException please use CompletionException throwable.getCause() since it is wrapped.
From there you can inspect the response from IGResponse
