### ISSUE TITLE
How to detect a sponsored post?

### ISSUE THREAD

**Issue by samcortezzz** [instagram4j/instagram4j#523]
Hi,

When receiving the feed. is there any way to detect a sponsored post? I know IG shows an ad / sponsored post every 5th, but sometimes when receiving the feed the ad is not on the 5th element.

**Comment by jvogit** [comment]
From a feed, check if sponsor_tags field is not null. Perhaps something like
```
item.get("sponsor_tags") != null
```

to filter out ads i guess
