### ISSUE TITLE
how i can follow or unfollow

### ISSUE THREAD

**Issue by lucas-tassis** [instagram4j/instagram4j#525]
i need to follow some predefined profiles, which method should i invoke? and to unfollow?

**Comment by jvogit** [comment]
I believe FriendshipsActionRequest is needed with a CREATE FriendshipAction.

A related (example)[https://github.com/instagram4j/instagram4j/blob/ce2ccb28c9a57d3adfb02160a8fa366fa1ad067f/src/examples/java/friendships/FriendshipsTest.java#L48]

**Comment by jvogit** [comment]
If you have any other questions on usage, please ask them on our [Discord](https://discord.com/invite/gR2EPwZGEZ).
