### ISSUE TITLE
Login with TwoFactor/Challenge on device without console

### ISSUE THREAD

**Issue by axel0070** [instagram4j/instagram4j#527]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

I cannot use the scanner.nextLine() for the onTwoFactor/challenge because I am using it on android, and the code will have to be input inside an EditText then be valide by the user. (Here the problem is for android, but could be anywhere the application have to request the user to write it inside an UI interface.)
My question is how can I be notify that the user should input a code (if needed) and how can I "pause" the login process until the user click on a button to confirm his input?

**Comment by jvogit** [comment]
Please see this example (here)[https://github.com/instagram4j/instagram4j#two-factor-login]

The inputCode for reslolving is just a callable that must return the code. You can perform your retrieval via that callable.

**Comment by jvogit** [comment]
If you have any other questions on usage, please ask them on our [Discord](https://discord.com/invite/gR2EPwZGEZ).

**Comment by ErrorxCode** [comment]
Sorry but I still can't figure it out. Can you please show an example in which you are taking code from **UI/edittext** and resolving **two factor?**
