### ISSUE TITLE
How to post album?

### ISSUE THREAD

**Issue by gmyrzamuratov** [instagram4j/instagram4j#528]

**Comment by jvogit** [comment]
See this [example](https://github.com/instagram4j/instagram4j/blob/698af99417c75389a15fbe1f189d52f2797d8794/src/examples/java/actions/TimelineActionTest.java#L62)

**Comment by gmyrzamuratov** [comment]
Thank you very much.

**Comment by jvogit** [comment]
If you have any other questions on usage, please ask them on our [Discord](https://discord.com/invite/gR2EPwZGEZ).
