### ISSUE TITLE
How can I get users how liked some post ?

### ISSUE THREAD

**Issue by LearnJava** [instagram4j/instagram4j#537]
Hello!
How can I get users how liked some post ?
Thx.

**Comment by jvogit** [comment]
Hi, we have discord for this kind of support on usage in order to not clutter the issues tab.

If you can please elaborate in the chat, I'd be happy to help you.
[![Discord](https://img.shields.io/discord/777326687326044171?label=chat)](https://discord.com/invite/gR2EPwZGEZ)

**Comment by khale11** [comment]
Hi👋
