### ISSUE TITLE
Android apps crash when try to use instagram4j method

### ISSUE THREAD

**Issue by abeliojuniar** [instagram4j/instagram4j#54]
Hi, I would like to try instagram4j lib in my android studio project. But when I tried to run the project, the apps crash when calling one of the library method. Here's my simple code:

- - - -
package com.digitaloxxy.myapplication;
import android.support.v7.app.AppCompatActivity;`
import android.os.Bundle;`
import org.brunocvcunha.instagram4j.Instagram4j;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Instagram4j instagram = Instagram4j.builder().username("username").password("password").build();
        //instagram.setup(); -- commented to try the builder only
        //instagram.login(); -- commented to try the builder only
    }
}
- - - -

I wonder whether there's something wrong with my build config or the code. Or perhaps could you please give me a referrence the example code that I can refer? Thanks

**Comment by mehhrad** [comment]
use [Instagram4android](https://github.com/charlieAndroidDev/Instagram4Android) same library for android
