### ISSUE TITLE
upload image and video with url in web

### ISSUE THREAD

**Issue by gojm** [instagram4j/instagram4j#547]
i suggest possibility uploading with url like 

> https://dsddsdj.dsd.jpg

> or how to know upload image with byte array
is it possible uplad directly

**Comment by jvogit** [comment]
There is already method to upload a byte array [here](https://github.com/instagram4j/instagram4j/blob/76333472e9412eb3c0e65b04c6fd407b4fbd58a3/src/main/java/com/github/instagram4j/instagram4j/actions/timeline/TimelineAction.java#L38)

**Comment by gojm** [comment]
but url uploading is not added

**Comment by jvogit** [comment]
> but url uploading is not added

You may read the data from the url into a byte array and upload it that way
