### ISSUE TITLE
SidecarPhoto how to upload album

### ISSUE THREAD

**Issue by gojm** [instagram4j/instagram4j#548]
CompletableFuture<String> completableFuture = igClient.actions()
                    .timeline()
                    .uploadAlbum(infos, "king in the north")

how to new info list

**Comment by jvogit** [comment]
There is an example [here](https://github.com/instagram4j/instagram4j/blob/76333472e9412eb3c0e65b04c6fd407b4fbd58a3/src/examples/java/actions/TimelineActionTest.java#L62)

We have a Discord when you can join for support [![Discord](https://img.shields.io/discord/777326687326044171?label=chat)](https://discord.com/invite/gR2EPwZGEZ)

It is much better than opening issues here. Thank you!

**Comment by gojm** [comment]
@jvogit  thanks
i have a question how can save and load user authentication like cookie 
i don't want to login each time of testing 
i see you load `      IGClient lib = SerializeTestUtil.getClientFromSerialize("igclient.ser", "cookie.ser");`
but how to before save to load

**Comment by gojm** [comment]
i found it :))
https://github.com/instagram4j/instagram4j/blob/2cf582dca46f6e95183b165018cf94bfcc03ad49/src/examples/java/serialize/SerializeTestUtil.java#L45

**Comment by gojm** [comment]
@jvogit 
your style of coding is functional and declarative 
where are you learn this style programing 
yoour work is very great
