### ISSUE TITLE
Sharing a Backdate Post

### ISSUE THREAD

**Issue by oguzhancevik** [instagram4j/instagram4j#554]
Hi, Is it possible to share a backdate post or change the date of the existing post?

**Comment by jvogit** [comment]
> Hi, Is it possible to share a backdate post or change the date of the existing post?

I'm not aware of that functionality so it's not likely it's present in this library. If it's possible in the app, then it is possible to implement a request in this library here by making your own. If you do, I encourage you to open a pull request.

[Here](https://github.com/instagram4j/instagram4j/wiki/Contributing-requests) is guide to intercept requests from the app, and creating your own requests using this library as the framework.

We also have a discord for more questions like these.
[![Discord](https://img.shields.io/discord/777326687326044171?label=chat)](https://discord.com/invite/gR2EPwZGEZ)
