### ISSUE TITLE
How to get login history?

### ISSUE THREAD

**Issue by holden321** [instagram4j/instagram4j#558]
There is a web page with login history:
https://www.instagram.com/session/login_activity/
But is it possible to get it by API?
I can't find the end-point.
This won't work:
/api/v1/session/login_activity/
or there should be some special params in request.

**Comment by jvogit** [comment]
> There is a web page with login history:
> https://www.instagram.com/session/login_activity/
> But is it possible to get it by API?
> I can't find the end-point.
> This won't work:
> /api/v1/session/login_activity/
> or there should be some special params in request.

I do not know the specific endpoint, but it can be added in when inspecting requests from the app. When I have time I might investigate this further.

**Comment by holden321** [comment]
How are you going to inspect requests from the app?
I tried through Fiddler or Charles but without success.
Changing contents of fb_network_security_config.xml and rebuilding the app does nothing :(

**Comment by jvogit** [comment]
> How are you going to inspect requests from the app?
> I tried through Fiddler or Charles but without success.
> Changing contents of fb_network_security_config.xml and rebuilding the app does nothing :(

Hi refer to this guide: https://github.com/itsMoji/Instagram_SSL_Pinning#root-method

This provides patched apk that you can inspect requests from.

**Comment by holden321** [comment]
Wow, cool, it works, thanks.
It's just /api/v1/session/login_activity/?device_id=XXX
