### ISSUE TITLE
How to get feed post of the current user ?

### ISSUE THREAD

**Issue by rahman9868** [instagram4j/instagram4j#560]
i want to get list of feed ,  what the funcion i have to use ?

**Comment by jvogit** [comment]
[Here](https://github.com/instagram4j/instagram4j/blob/master/src/examples/java/feed/FeedUserRequestTest.java) is example

```java
new FeedUserRequest(client.getSelfProfile().getPk()).execute(client)
.thenAccept(response -> {
    // act on response
});
```
