### ISSUE TITLE
Reels feed request give stories insted of reels

### ISSUE THREAD

**Issue by UwUDev** [instagram4j/instagram4j#566]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Bug description

I'm trying to get de feed reel by using `FeedReelsTrayRequest()` but it returns me the stories

### How i am trying to do it

```java
public static void main(String[] args) throws IOException {
        IGClient client = IGClient.builder()
                .username("cool username")
                .password("p@ssw0rd")
                .login();

        List<Reel> reels = new ArrayList<>();
        List<String> links = new ArrayList<>();

        new FeedReelsTrayRequest().execute(client) // not FeedUserStoryRequest
                .thenAccept(response -> {
                    reels.addAll(response.getTray());
                }).join();

        for (Reel reel : reels) {
            List<ReelMedia> medias = reel.getItems();
            try {
                for (ReelMedia media : medias) {
                    System.out.println("Media: " + IGUtils.getMediaURLFromReel(media.toString()));
                    links.add(IGUtils.getMediaURLFromReel(media.toString()));
                }
            } catch (Exception ignored){System.out.println("Media : null");}
        }

        for (String link : links)
            IGUtils.saveMedia(link);
    }
```

The code works perfectly, i have no errors but i am getting stories insted of reels

**Comment by jvogit** [comment]
Internally, the Instagram Stories were always called "Reels" (before the contemporary Instagram Reels came out). Currently there are no requests for the contemporary Instagram Reels but feel free to add them and open a PR!

**Comment by UwUDev** [comment]
Okay thanks you, I will try it with this tutorial https://github.com/instagram4j/instagram4j/wiki/Contributing-requests
It may not be a success but if it succeeds I will make a pull request

**Comment by bloworlf** [comment]
I just found this issue. @UwUDev , have you made any progress regarding fetching the "contemporary" reels?
