### ISSUE TITLE
SearchTag users

### ISSUE THREAD

**Issue by 0utplay** [instagram4j/instagram4j#579]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

Hey, is there a way to get some of the pictures that are posted with a specific hashtag?

I found IGClient#getActions#search#searchTag, but I cannot find a way to get a picture or a user from there

**Comment by jvogit** [comment]
See this example: https://github.com/instagram4j/instagram4j/blob/5f97cf0d89c247d58e5abd1a6a501cd04f9c7b7b/src/examples/java/feed/FeedTagTest.java#L18

You must use FeedTagRequest
