### ISSUE TITLE
Question to X-IG-Capabilities

### ISSUE THREAD

**Issue by Mykke24** [instagram4j/instagram4j#58]
Hey guys, is **3Q4=** a constant? Can I change this value and would the request still work?
post.addHeader("X-IG-Capabilities", "3Q4=");

I analysed other IG APIs and there are different varieties of this constant:
X-IG-Capabilities: 36oD
X_IG_Capabilities: 3R4=
X_IG_Capabilities: 3Ro=
X-IG-Capabilities: 3QI=
X-IG-Capabilities: 3ToAAA==
X-IG-Capabilities: AQ==

Does it depend on the IG Version? Or is it random?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
