### ISSUE TITLE
How i can get live comments ?

### ISSUE THREAD

**Issue by zain84** [instagram4j/instagram4j#582]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

Ask your question here. Please make sure your question has not been answered previously and you have looked over relevant examples. Please post any example code that may help others help you!

**Comment by jvogit** [comment]
See this [example](https://github.com/instagram4j/instagram4j/blob/5f97cf0d89c247d58e5abd1a6a501cd04f9c7b7b/src/examples/java/live/LiveActionsTest.java#L51)
