### ISSUE TITLE
story photo is overfitted not fitting image....

### ISSUE THREAD

**Issue by lusicsmusics1** [instagram4j/instagram4j#583]

**Comment by unldenis** [comment]
what do you mean?

**Comment by lusicsmusics1** [comment]
i mean :this shoe overd fit the screen and is not appropriate and interesting for bussiness,
insta in app has a boolean option to fit picture to screen when we uploading ..

![image](https://user-images.githubusercontent.com/78613940/123453361-b0cea000-d5f4-11eb-9550-d6d8d0c61588.png)

**Comment by lusicsmusics1** [comment]
@unldenis ?

**Comment by jvogit** [comment]
you must make sure the image is properly sized. this library does offer any image processing because it's mainly a client for API endpoints, so it's up to you if you want to add image processing to your app.
