### ISSUE TITLE
Mention in Story Upload

### ISSUE THREAD

**Issue by mhdihso** [instagram4j/instagram4j#587]
Hi, I have a question about uploading story.
Is there any way to add text in story upload and use mention feature in the instagram story (@)?

**Comment by jvogit** [comment]
Yes there is a way.
See this example in attaching metadata to your story (polls, location, mentions, etc.)
https://github.com/instagram4j/instagram4j/blob/master/src/examples/java/upload/UploadStoryPhotoTest.java
You will need this item: https://github.com/instagram4j/instagram4j/blob/94ecd67381a10f9152c94da4fa73315540bc726f/src/main/java/com/github/instagram4j/instagram4j/models/media/reel/item/ReelMentionsItem.java
