### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by calves07** [instagram4j/instagram4j#598]
Hey,

Sometimes I get an UnknownHostException related to address i.instagram.com when I'm trying to make a DirectGetPresenceRequest. This does not happen often but it happened a couple of times already. I even added some logic to just repeat the request in case it fails due to this reason for a maximum of 5 times and after it failed the first first, it immediately failed the next 5 attempts. After running the application again, it worked fine tho. Any ideia what's causing this? Thanks.

**Comment by jvogit** [comment]
I'm not sure, could be a problem on Instagram's or your end. 

I say it's good solution to retry the requests.
