### ISSUE TITLE
how to get other user's posts after logining with my own account

### ISSUE THREAD

**Issue by rocky-peng** [instagram4j/instagram4j#602]

**Comment by jvogit** [comment]
see this example: https://github.com/instagram4j/instagram4j/blob/00e4eeae64f828fb922204de48a08fa0fa8f47e2/src/examples/java/feed/FeedUserRequestTest.java#L27

Replace with your desired user's pk (a user id basically)

You can fetch a request for their pk here: https://github.com/instagram4j/instagram4j/blob/00e4eeae64f828fb922204de48a08fa0fa8f47e2/src/examples/java/users/UserInfoRequestTest.java#L25
