### ISSUE TITLE
getViewers() only returns the first five elements

### ISSUE THREAD

**Issue by Alligator84** [instagram4j/instagram4j#603]
Hi, how to get all users who viewed stories? Now the method getViewers() produces only the first 5
Thanks!

**Comment by jvogit** [comment]
See this request.
https://github.com/instagram4j/instagram4j/blob/27b0dd000b6ebedf8c02bf7ec3947ccb63db6948/src/main/java/com/github/instagram4j/instagram4j/responses/media/MediaListReelMediaViewerResponse.java

It is paginated feed so requires multiple requests for all users. 

There is a utility FeesIterable or FeedIterator that does this for you. Follow example here:
https://github.com/instagram4j/instagram4j/blob/27b0dd000b6ebedf8c02bf7ec3947ccb63db6948/src/examples/java/actions/FeedIterableTest.java#L22

we also have a discord where you can chat for questions. https://discord.com/invite/gR2EPwZGEZ
