### ISSUE TITLE
How to get Stream Key to start a live?

### ISSUE THREAD

**Issue by hamedsharifi** [instagram4j/instagram4j#605]
## Issue Template Requirements

Issue must be of the specified template and follow these requirements or it will be ignored. 
- Please do not post screenshots of code output
- Wrap code in a codeblock
- exhibiting spam behavior or "evil" behavior will have the issue ignored
- Please make sure your issue hasn't been asked before
- Please complete the checklist below (mark boxes [ ] with [x])

---

### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

Hello. Thanks for great work. How can I get Stream Key to start a live ?

**Comment by jvogit** [comment]
See this request from a sample app using instagram4j to start a livestream from CLI:
https://github.com/instagram4j/i4jlive/blob/daccf826c6a5beb7d11afe8703a383bbfe17ae3c/src/main/java/i4jlive/LiveBroadcastProcess.java#L18
