### ISSUE TITLE
 anonymous access 

### ISSUE THREAD

**Issue by 89z** [instagram4j/instagram4j#619]
Is it possible to get post information, from a public page such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

without login?

**Comment by jvogit** [comment]
It is possible but not through this library. This library concerns with the internal RESTful endpoints in the Instagram app. I think for the web app, graphql queries are used. The web api is not in this library.

**Comment by 89z** [comment]
The Instagram app cannot access the media elements of a post?

**Comment by jvogit** [comment]
> The Instagram app cannot access the media elements of a post?

The internal RESTful endpoints used here I think require Authorization so no anonymous access. The web api is something you need to look into. I believe to use the Instagram mobile app you need to be logged in anyways.

**Comment by 89z** [comment]
OK then, thanks for the information!

**Comment by jvogit** [comment]
> OK then, thanks for the information!

Glad to help. And you can always scrape the site since it is public anyways using Selenium or something similar.
