### ISSUE TITLE
InstagramTagFeedRequest Top Posts?

### ISSUE THREAD

**Issue by jacksonw765** [instagram4j/instagram4j#63]
I want to get the top posts for a hashtag not the most recent use of a hashtag. Any idea how this could be done?

**Comment by lxknvlk** [comment]
same question here. 
nstagram.sendRequest(InstagramTagFeedRequest("tag")) 
gives recent posts, not top posts
any help?

**Comment by jvogit** [comment]
Addressed in [rewrite](https://github.com/instagram4j/instagram4j/tree/develop) or no longer relevant.
