### ISSUE TITLE
New way of fetching direct message ?

### ISSUE THREAD

**Issue by ErrorxCode** [instagram4j/instagram4j#645]
### Pre-Checklist

I made sure...
- [✔] I read the README.md
- [✔] I looked over the examples and wiki
- [✔] my issue hasn't been asked or solved before

---

### New way of reading the direct message?
Earlier #144, we were able to fetch direct messages from the `InstagramThreadItem` model class. But after this library is re-written, This class was changed to `ThreadItem` class. The weird thing is that this class does not seem to have the message of the chat. 

Please tell me how can fetch a direct message from a particular chat/thread.

**Comment by exmike** [comment]
Maybe this will help you @ErrorxCode 
((ThreadTextItem) response.getInbox().getThreads().get(0).getItems().get(0)).getText();

**Comment by exmike** [comment]
can someone tell me how to get information about received messages? a listener or something similar? I need to understand when a user has written something to me and react to it ?

**Comment by ErrorxCode** [comment]
I figured it out.

```java
List<ThreadItem> list = new ArrayList<>();
IGThread thread = getThread(username); // returns thread by username
String cursor = thread.getOldest_cursor();
list.add(thread.getItems().get(0));

while (cursor != null) {
    thread = client.sendRequest(new DirectThreadsRequest(thread.getThread_id(), cursor)).get().getThread();
    list.addAll(thread.getItems());
    cursor = thread.getOldest_cursor();
}
return list;
```
This will return all the messages of a chat from beginning to last. The ThreadItem in the list can be or cannot be `TextThreadItem`. You have to check and cast it accordingly.

If you want to only fetch some messages then use for-loop wisely. wisely because every time it will return you 20 messages.
For **example** if you want to retrieve 40 messages:
```java
for (int i = 0; i < 2; i++){
    thread = client.sendRequest(new DirectThreadsRequest(thread.getThread_id(), cursor)).get().getThread();
    list.addAll(thread.getItems());
    cursor = thread.getOldest_cursor();
    if (cursor == null)
        break;
}
```
