### ISSUE TITLE
Commenting an own video -> IGResponseException: failed to mention

### ISSUE THREAD

**Issue by xXSkyWalkerXx1** [instagram4j/instagram4j#656]
### Pre-Checklist

I made sure...
- [Y] I read the README.md
- [Y] I looked over the examples and wiki
- [Y] my issue hasn't been asked or solved before

Y...yes

---

### Question

If I comment my own videos and mention some users I get the named exception.
Sometimes it happens after the 10. mention, sometime after the 15. mention (in one comment) - it seems to be random.

Does anyone of you know what's the reason for?

_Regards._

**Comment by ErrorxCode** [comment]
Maybe Instagram has limits on the number of mentions.

**Comment by xXSkyWalkerXx1** [comment]
> Maybe Instagram has limits on the number of mentions.

Yes, they have, but that can't be the reason for why the exception happens on random count of mentions.

**Comment by ErrorxCode** [comment]
You might be trying to mention a person who **don't allow everyone to mention**

BTW, can you please share the code ?
