### ISSUE TITLE
How can I send a message to a follower?

### ISSUE THREAD

**Issue by trebsoj** [instagram4j/instagram4j#665]
### Pre-Checklist

I made sure...
- [ x] I read the README.md
- [ x] I looked over the examples and wiki
- [ x] my issue hasn't been asked or solved before

---

In the examples directory I have not seen any example to do it.
Questions from other users asking the same thing no longer work, because the code has changed.

**Comment by trebsoj** [comment]
I found the solution:

kotlin:
```
var client = IGClient.builder().username(user).password(password).login()
DirectThreadsBroadcastRequest(BroadcastTextPayload("Test https://google.com", id_user)).execute(client).join()
```

**Comment by ErrorxCode** [comment]
Are you still using this library? LoL.
Have a look at this #666 issue
