### ISSUE TITLE
Telegram Group?

### ISSUE THREAD

**Issue by patriotaki** [instagram4j/instagram4j#68]
Maybe we should make a Telegram Group
so we can discuss and get answers faster?

**Comment by patriotaki** [comment]
for real? can i make the group?

**Comment by brunocvcunha** [comment]
I think the best way is to have everything here on Github. 
It will also help newcomers with their questions, as well as encourage new people to take tasks and open pull requests for this repo.

I don't have a lot of time to maintain the repo, so I am trying to go through the tasks, but it's hard to catch up with all of them.

If you see any specific reason on why a chatting group would help, let me know and we can consider this.

**Comment by patriotaki** [comment]
Hello,
I appreciate all your help
But as you said you cant keep up,but we as a community we can keep up.
I see many apis have their own Telegram Group.

For example if a newcomer doesnt know how to iterate the pages to get following list etc that could be a very fast response in Telegram than Here .. 
plus we can discuss about other stuff too, create a bond between us

Its easier to reply on Telegram trust me.. i have a 3.500 Group and 4 different Teelgram accounts for bussiness use.. its easy to be active there than here

**Comment by patriotaki** [comment]
i still believe it would be much easier
