### ISSUE TITLE
Fix variable naming

### ISSUE THREAD

**Issue by Taz03** [instagram4j/instagram4j#703]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Describe the bug

In the code base some places uses lower camel case for variable naming which is the correct way to do it in java, but in some places it uses snake case which is not only wrong but makes the code inconsistent.

### How to reproduce

N/A

### Expected behavior

Consistent variable naming across the code base. lower camel case

### Actual behavior

Inconsistent variable naming

**Comment by yamin8000** [comment]
I don't think it's fair to label this issue as a bug, it's rather a code styling problem.

**Comment by Taz03** [comment]
> I don't think it's fair to label this issue as a bug, it's rather a code styling problem.

yea i should've selected the "Question and other" category, but nothing i can do about it now, i can't edit tags
