### ISSUE TITLE
How to setup the project locally

### ISSUE THREAD

**Issue by Taz03** [instagram4j/instagram4j#705]
### Pre-Checklist

I made sure...
- [x] I read the README.md
- [x] I looked over the examples and wiki
- [x] my issue hasn't been asked or solved before

---

### Question

I'm unable to setup this project locally, i tried eclipse and intellij both errors out. `./gradlew build` is working and gives successful output. But i don't get any auto completion or intellisense. How do u guys setup this project locally. Any help is appreciated

**Comment by bloworlf** [comment]
Don't just close the issue without telling others if and how you hot it solved.

This library is using lombok and it generates the getters and setters on compile. While coding, you won't have autocompletion/intelli-sense for getters and setters but the project will compile anyways. Just make sure you have good practice while writing down the getThis(), setThat(value) methods.

**Comment by Taz03** [comment]
> Don't just close the issue without telling others if and how you hot it solved.
> 
> This library is using lombok and it generates the getters and setters on compile. While coding, you won't have autocompletion/intelli-sense for getters and setters but the project will compile anyways. Just make sure you have good practice while writing down the getThis(), setThat(value) methods.

it is not "fixed", i closed the issue coz i don't know what info is relevant and if someone will able to help me with it.

**Comment by Taz03** [comment]
ok so it is working find after i upgraded java to version 18 and gradle to latest available version(build.gradle and gradle.properties file), also added this in build.gradle
```
lombok {
    version = "1.18.24"
}
```
everything works fine now, i.e. eclipse jdt works and build passes successfully

**Comment by bloworlf** [comment]
I am using android studio (latest version supports lombok natively) and here's what I did:
After importing the project as a module, there were a lots of errors so I had to make some modifications to the build.gradle file

build.gradle
```
plugins {
    id 'java-library'
    id 'io.freefair.lombok' version '6.6.1'
    id 'net.nemerosa.versioning' version '2.15.1'
}

version = "${versioning.info.branchType == 'release' ? versioning.info.display : versioning.info.full}"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    // OkHttp
    api 'com.squareup.okhttp3:okhttp:5.0.0-alpha.11'
    api 'com.squareup.okhttp3:okhttp-urlconnection:5.0.0-alpha.11'
    // jackson data-bind
    api 'com.fasterxml.jackson.core:jackson-databind:2.13.4'
    api 'com.fasterxml.jackson.core:jackson-annotations:2.13.4'
    api 'org.slf4j:slf4j-api:2.0.6'
    // Test utilities
    testImplementation 'org.slf4j:slf4j-reload4j:2.0.6'
    testImplementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.11'
    testImplementation 'log4j:log4j:1.2.17'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'pl.pragmatists:JUnitParams:1.1.1'
    testImplementation 'org.apache.maven:maven-compat:4.0.0-alpha-3'
}

task sourcesJar(type: Jar, dependsOn: classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

javadoc.failOnError = false
task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

task createJar(type: Copy) {
    from('build/intermediates/bundles/release/')
    into('libs/jars/')
    include('classes.jar')
    rename('classes.jar', 'instagram4j.jar')
}
```

MinSdk version should be 26. If you plan to support lower version (sdk 24 as I did) you'll have to add [Base64](https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/Base64.java) class yourself as java.util.Base64 was only added in android 8.
I created a Base64.java file in `com.github.instagram4j.instagram4j.utils` and changed the import in `com.github.instagram4j.instagram4j.utils.IGUtils`

Also, in the main project build.gradle, add the Desugaring dependency:

```
dependencies {
//Desugaring
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
}
```
