### ISSUE TITLE
How to send image from direct messages?

### ISSUE THREAD

**Issue by spapapan** [instagram4j/instagram4j#706]
What I have tried so far but didn't work:
 
public static void directImage(IGClient client,
                                          long userID, File photo)
    {
           DirectThreadsBroadcastRequest.BroadcastPayload payload =
                           new DirectThreadsBroadcastRequest.BroadcastConfigurePhotoPayload(photo.getName(), userID); 
          client.sendRequest(request).get(5, TimeUnit.SECONDS); 
  }

Any ideas?

**Comment by bloworlf** [comment]
Don't worry, I'll share my code with you later when I get to my PC.

**Comment by spapapan** [comment]
> Don't worry, I'll share my code with you later when I get to my PC.

Thanks man.

**Comment by bloworlf** [comment]
First of all, the image you're sending must be in a squared (I think) format `.setAspectRatio(1080, 1080)`. I think that's the maximum size allowed. And only jpeg or png are allowed (you'll have to test because I don't remember)

I am on android, I use [Android Image Cropper](https://github.com/ArthurHub/Android-Image-Cropper) to crop my images:
```
//on activity result, get selected image uri
CropImage.activity(selectedImageUri)
                        .setAspectRatio(1080, 1080)
                        .setAutoZoomEnabled(true)
                        .start(this);
```

And now, onActivityResult for the CropImage activity, get the uri of the cropped file
```
File photo = new File(resultUri.getPath());

                            new TaskRunner().executeAsync(new RestRequest2(Conversation.this, getClient()).sendImageDM(photo, igThread.getThread_id()), (data) -> {
                                if (data == null) {
                                    return;
                                }

                                if (data.getStatusCode() == 200) {
                                    //good, image sent
                                }
                            });
```

And the function that sends the request
```
@NonNull
    public Callable<IGResponse> sendImageDM(File image, String thread_id) {
        if (this.shouldCancelRequest || settingsPrefs().getBoolean("disable_requests", false)) {
            return () -> null;
        }
        return () -> {
            FileInputStream is = null;
            try {
                is = new FileInputStream(image);

                byte[] bytes = new byte[(int) image.length()];
                is.read(bytes);

                String uploadId = String.valueOf(System.currentTimeMillis());

                RuploadPhotoRequest req = new RuploadPhotoRequest(bytes, "1", uploadId, false);
                RuploadPhotoResponse res = req.execute(client).join();

                updateRequestCount();
                return new DirectThreadsBroadcastRequest(new DirectThreadsBroadcastRequest.BroadcastConfigurePhotoPayload(uploadId, thread_id)).execute(client).join();
            } catch (Exception e) {
                Logger.e(e);
                handleException(context, e, null);
                return null;
            } finally {
                if (is != null) {
                    try {
                        is.close();
                    } catch (IOException e) {
                        Logger.e(e);
                    }
                }
            }
        };
    }
```

Sendind a video via DM requires one more step. Let me know if you need more help.

**Comment by spapapan** [comment]
Thanks for taking the time to reply. I tried this code with a 1080x1080 .png and .jpeg but nothing happened. Also I didn't get any error. Is there any way I can debug it, or maybe something is missing?

**Comment by spapapan** [comment]
I refactored this code to this:



    @NonNull
    public static Callable<IGResponse> sendImageDM(IGClient client, File image, String thread_id)
    {
        Print.e("Sending image: " + image.getName());
        Print.e("Thread id: " + thread_id);
        return () ->
        {
            FileInputStream is = null;
            try {
                is = new FileInputStream(image);

                byte[] bytes = new byte[(int) image.length()];
                is.read(bytes);

                String uploadId = String.valueOf(System.currentTimeMillis());

                RuploadPhotoRequest req = new RuploadPhotoRequest(bytes, "1", uploadId, false);
                RuploadPhotoResponse res = req.execute(client).join();

                return new DirectThreadsBroadcastRequest(new DirectThreadsBroadcastRequest.
                        BroadcastConfigurePhotoPayload(uploadId, thread_id)).execute(client).join();
            }
            catch (Exception e)
            {
                e.printStackTrace(); 
                return null;
            }
            finally {
                if (is != null) {
                    try {
                        is.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
    }

I tried with 1080x1080 .png and .jpeg but nothing happend. Not even an error. Am I missing something?

**Comment by bloworlf** [comment]
I'm sorry, I sent you the code as it was in my project.

If you already have your project set up, just use the try/catch/finally block.

```
private void someFunction(IGClient client, File image, String thread_id){
FileInputStream is = null; try { is = new FileInputStream(image); byte[] bytes = new byte[(int) image.length()]; is.read(bytes); String uploadId = String.valueOf(System.currentTimeMillis()); RuploadPhotoRequest req = new RuploadPhotoRequest(bytes, "1", uploadId, false); RuploadPhotoResponse res = req.execute(client).join(); return new DirectThreadsBroadcastRequest(new DirectThreadsBroadcastRequest. BroadcastConfigurePhotoPayload(uploadId, thread_id)).execute(client).join(); } catch (Exception e) { e.printStackTrace(); return null; } finally { if (is != null) { try { is.close(); } catch (IOException e) { e.printStackTrace(); } } }
}
```

Sent from my phone.

**Comment by spapapan** [comment]
> I'm sorry, I sent you the code as it was in my project.
> 
> If you already have your project set up, just use the try/catch/finally block.
> 
> ```
> private void someFunction(IGClient client, File image, String thread_id){
> FileInputStream is = null; try { is = new FileInputStream(image); byte[] bytes = new byte[(int) image.length()]; is.read(bytes); String uploadId = String.valueOf(System.currentTimeMillis()); RuploadPhotoRequest req = new RuploadPhotoRequest(bytes, "1", uploadId, false); RuploadPhotoResponse res = req.execute(client).join(); return new DirectThreadsBroadcastRequest(new DirectThreadsBroadcastRequest. BroadcastConfigurePhotoPayload(uploadId, thread_id)).execute(client).join(); } catch (Exception e) { e.printStackTrace(); return null; } finally { if (is != null) { try { is.close(); } catch (IOException e) { e.printStackTrace(); } } }
> }
> ```
> 
> Sent from my phone.

That's the same function as the one I wrote before. Are you sure it's working? Have you tried it lately? Because for me it doesn't do anything.

**Comment by bloworlf** [comment]
Of course, here's a demo: https://gfycat.com/ringedinnocenticeblueredtopzebra  

I'm using the thread's ID instead of user's ID.
And on success, I auto refresh the page to load the new elements.

**Comment by spapapan** [comment]
public static IGResponse sendImageDM(IGClient client, File image, String thread_id)
    {
        Print.e("Sending image: " + image.getName());
        Print.e("Thread id: " + thread_id);

        FileInputStream is = null;
        try
        {
            is = new FileInputStream(image);

            Print.e("File size: " + is.available());
            byte[] bytes = new byte[(int) image.length()];
            is.read(bytes);
            Print.e("Bytes size: " + bytes.length);

            String uploadId = String.valueOf(System.currentTimeMillis());

            Print.e("Creating upload photo request");
            RuploadPhotoRequest req = new RuploadPhotoRequest(bytes, "1", uploadId, false);

            Print.e("Sending request");
            RuploadPhotoResponse res = req.execute(client).join();

            if (res!=null)
            {
                Print.e("RuploadPhotoResponse getMessage: " + res.getMessage());
                Print.e("getUpload_id: " + res.getUpload_id());
                Print.e("getCheckpoint_url: " + res.getCheckpoint_url());
                Print.e("getStatusCode: " + res.getStatusCode());
            }

            Print.e("Trying to send image...");
            IGResponse response = new DirectThreadsBroadcastRequest(new DirectThreadsBroadcastRequest.
                    BroadcastConfigurePhotoPayload(uploadId, thread_id)).execute(client).join();

            Print.e("Get response");
            if (response != null)
            {
                Print.e("response: " + response.getStatus());
                Print.e("response: " + response.getMessage());
                Print.e("response: " + response.getStatusCode());
                Print.e("response: " + response.getFeedback_message());
                Print.e("response: " + response.getFeedback_title());
                Print.e("response: " + response.getCheckpoint_url());
            }

            return response;
        }
        catch (Exception e)
        {
            Print.e("Exception: " + e.getMessage());

            e.printStackTrace();
            return null;
        }
        finally
        {
            if (is != null)
            {
                try
                {
                    is.close();
                } catch (IOException e)
                {
                    Print.e("finally Error: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        }
    }

In this line I get an error:

`RuploadPhotoResponse res = req.execute(client).join();    `  

 
> 2023-01-29 12:12:17.675  W  java.util.concurrent.CompletionException: com.github.instagram4j.instagram4j.exceptions.IGResponseException
> 2023-01-29 12:12:17.675  W  	at com.github.instagram4j.instagram4j.IGClient$1.handle(IGClient.java:88)
> 2023-01-29 12:12:17.675  W  	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$5$com-github-instagram4j-instagram4j-IGClient(IGClient.java:157)
> 2023-01-29 12:12:17.676  W  	at com.github.instagram4j.instagram4j.IGClient$$ExternalSyntheticLambda1.apply(Unknown Source:6)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:962)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:946)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:482)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2049)
> 2023-01-29 12:12:17.676  W  	at com.github.instagram4j.instagram4j.IGClient$2.onResponse(IGClient.java:141)
> 2023-01-29 12:12:17.676  W  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
> 2023-01-29 12:12:17.676  W  	at java.lang.Thread.run(Thread.java:1012)
> 2023-01-29 12:12:17.676  W  Caused by: com.github.instagram4j.instagram4j.exceptions.IGResponseException
> 2023-01-29 12:12:17.676  W  	at com.github.instagram4j.instagram4j.requests.IGRequest.parseResponse(IGRequest.java:72)
> 2023-01-29 12:12:17.676  W  	at com.github.instagram4j.instagram4j.IGClient.lambda$sendRequest$4$com-github-instagram4j-instagram4j-IGClient(IGClient.java:154)
> 2023-01-29 12:12:17.676  W  	at com.github.instagram4j.instagram4j.IGClient$$ExternalSyntheticLambda0.apply(Unknown Source:6)
> 2023-01-29 12:12:17.676  W  	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:618)
> 2023-01-29 12:12:17.676  W  	... 7 more

But it doesn't say what is wrong. Have you ever got an error like this?

**Comment by spapapan** [comment]
Actually it need to be .jpg and not .png. It worked! Thanks a lot for your time and effort to respond. You are the best!

**Comment by bloworlf** [comment]
Glad I could help.
