### ISSUE TITLE
My account got blocked only from testing the library.

### ISSUE THREAD

**Issue by mikebgrep** [instagram4j/instagram4j#707]
I just got blocked with two accounts that I use with another API Library for long time and I don't have problem there. I just build an application that use this library and on testing with small results I got blocked. If anybody can say different, e.g. does not have problem to use the library to say his opinion, but my opinion is that the instagram4j is not safe for use.

First account: We restrict certain activity to protect our community
Second account: Want selfie for verification.

The application I use is same as the another API Library which I use from more than 1 year.

**Comment by vasilywang** [comment]
Have you found solution for this issue? I encountered the same issue too.

**Comment by ErrorxCode** [comment]
Same issue too, I lost my account that is unrecoverable now

Looks like instagram updated their security detection towards the use of their service

**Comment by mikebgrep** [comment]
Maybe the problem is with the configuration of the devices which are used in the library I see they are from 2016, but I don't see the owner to make any changes on the project...

**Comment by boydtech761** [comment]
Message https://t.me/boydtech on telegram he’s the best on account recovering

**Comment by animexxx** [comment]
same issue
