### ISSUE TITLE
login_required, deserializing, No ID Given after sendLoginRequest

### ISSUE THREAD

**Issue by noirtier-villefort** [instagram4j/instagram4j#713]
- [ +] I read the README.md
- [ +] I looked over the examples and wiki
- [+ ] my issue hasn't been asked or solved before

### Question

Hi! I get login_required after deserializing. So i tried sendLoginRequest before any other requests and get _(fail 400) No ID given error._

Maybe it can be resolved with [this](https://github.com/instagram4j/instagram4j/issues/694), because deserialized **IGClient** object **doesnt** **contain** _encryptionId, encryptionKey, authorization fields_, as ErrorxCode explain [here](https://github.com/instagram4j/instagram4j/issues/669#issuecomment-1139314501).

Code that i use:
```
igClient = IGClient.deserialize(clientFile, cookieFile);
igClient.sendLoginRequest()
                    .exceptionally(tr->{
                        // No ID given here
                        return null;
                    });


igClient.getActions().users()
        .findByUsername(igClient.getSelfProfile().getUsername())
        .exceptionally(throwable -> {
         // login_required here
...              
```

**Comment by ErrorxCode** [comment]
This issue will remain open for like this and nothing will happen. This library is inactive since **january 2022**

I am building another great Instagram library with web Api of Instagram. You are always welcome to contribute in it.

Here is the link : https://github.com/ErrorxCode/EasyInsta#announcement-
