### ISSUE TITLE
There's a InstagramSearchUserIDRequest?

### ISSUE THREAD

**Issue by krismorte** [instagram4j/instagram4j#78]
When a use InstagramSearchUsernameRequest sometimes the user change the Profilename but the ID always be the same.

**Comment by brunocvcunha** [comment]
Yes. `users/{userId}/info/` Will add it later in the API.

**Comment by brunocvcunha** [comment]
This was added, can you validate, please?

**Comment by krismorte** [comment]
@brunocvcunha this requesta was add in the 1.6 version?

**Comment by krismorte** [comment]
@brunocvcunha I can use the new request, but different that the `InstagramSearchUsernameRequest` the  `InstagramGetUserInfoRequest` gives me a exception when the ID is not finded instead return the null object

**Comment by hellasengineering** [comment]
Hey there! We are having the same issues and I don't see a fix in the API to pass in a PK and get a user by the PK. Anyone figure this out?
