### ISSUE TITLE
login verification code?

### ISSUE THREAD

**Issue by patriotaki** [instagram4j/instagram4j#97]
is there any way i can detect if login failed and instagram asks for verification code?
if it asks is it possible to make a popup enter the code send it to ig and then relogin?

**Comment by ChrisJSt** [comment]
any update on this? Im getting stuck in a login verification loop.

**Comment by patriotaki** [comment]
sadly no..
i want to have the ability to enter phone code when ig asks for it and then continue what i was doing

**Comment by patriotaki** [comment]
can someone solve this?

**Comment by charlieAndroidDev** [comment]
You can fork the repo and add the functionality yourself then send a pull request.  It wouldn't be very tricky, look at the PHP repo.

**Comment by brunocvcunha** [comment]
I have been busy lately and can look in a few days. But if someone is willing to submit a PR, I'll gladly review and accept it. 
My suggestion is to add a checkpoint listener in the login request, so you can react however you want to the checkpoint request, as well as adding a specific request to submit the verification code.

**Comment by patriotaki** [comment]
@brunocvcunha im not very experienced to do that..if someone is able to fix that please do
i need it because im running 100+ accounts and need to verify them through app

**Comment by charlieAndroidDev** [comment]
@patrriotaki that seems like very Sammy behaviour which isn't allowed with this repo.

**Comment by charlieAndroidDev** [comment]
@patriotaki that seems like very Sammy behaviour which isn't allowed with this repo.

**Comment by patriotaki** [comment]
@charlieAndroidDev well ye..but again login verification can happen even with 1 account when using proxy

**Comment by patriotaki** [comment]
any update on this?
