### ISSUE TITLE
Checkpoint required loop

### ISSUE THREAD

**Issue by ChrisJSt** [instagram4j/instagram4j#98]
Right now, when using a proxy to login to a separate user's account, I get the checkpoint required. When the user verifies the checkpoint on their end and I try to login afterwards, I receive the checkpoint required again. Could this be as a result of using different uuID's or android-id's causing instagram to not link the login+verification together?

In any case, is it possible to spawn a verification checkpoint after a login attempt?

**Comment by justindelisle** [comment]
Issue with your proxy, nothing to do with instagram4j - the account is simply being flagged.

**Comment by patriotaki** [comment]
@ChrisJSt is there anyway we can detect when it needs verifcation and then submit the code to the ig api?
